//! Append-only event log: every engine event is persisted with a
//! gapless per-session sequence BEFORE it is delivered to observers, so a
//! crashed run can be reconstructed exactly.

use serde::{Deserialize, Serialize};

use leveler_core::{SessionId, Timestamp, TurnId};

use crate::database::{Database, StorageError};

/// The payload format version written for new events. Replay rejects any
/// persisted version greater than this (a newer writer's event an older reader
/// cannot understand) instead of guessing.
pub const EVENT_SCHEMA_VERSION: i64 = 1;

/// A persisted event row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow)]
pub struct EventRecord {
    /// Primary key, generated by the caller.
    pub id: String,
    /// Owning session. Sequencing is scoped to this value.
    pub session_id: String,
    /// Owning turn, or `None` for session-level events that belong to no turn.
    pub turn_id: Option<String>,
    /// Position in this session's gapless sequence, assigned on append. A gap
    /// means events were lost, which replay treats as corruption.
    pub sequence: i64,
    /// The event's type tag (queryable without parsing the payload).
    pub event_type: String,
    /// The event's JSON payload.
    pub payload: String,
    /// When the event was recorded, as RFC 3339 text. Not used for ordering —
    /// [`Self::sequence`] is authoritative.
    pub created_at: String,
    /// The payload format version (see [`EVENT_SCHEMA_VERSION`]).
    pub schema_version: i64,
}

/// Read/write access to the `events` table.
pub struct EventRepository<'a> {
    db: &'a Database,
}

impl<'a> EventRepository<'a> {
    /// Borrow `db` for the lifetime of this repository handle.
    pub fn new(db: &'a Database) -> Self {
        Self { db }
    }

    /// Append one event, assigning the next per-session sequence atomically.
    /// Returns the persisted record (with its sequence).
    pub async fn append(
        &self,
        session_id: &SessionId,
        turn_id: Option<&TurnId>,
        event_type: &str,
        payload: &str,
        now: Timestamp,
    ) -> Result<EventRecord, StorageError> {
        let id = leveler_core::EventId::generate().into_inner();
        // Structure-aware redaction (R007 F2): scrub string values only, never
        // the serialized document — and refuse loudly BEFORE the INSERT, so a
        // rejected payload can never corrupt the log or consume a sequence.
        let payload = crate::redact_json_payload_for_session(
            &format!("event (type '{event_type}')"),
            payload,
            Some(session_id.as_str()),
        )?;
        // The sequence is assigned inside the INSERT so concurrent appends on
        // one connection pool cannot race a read-then-write; the UNIQUE index on
        // (session_id, sequence) is the backstop that turns any residual race
        // into a loud failure instead of silent reordering.
        sqlx::query(
            "INSERT INTO events \
             (id, session_id, turn_id, sequence, type, payload, created_at, schema_version) \
             SELECT ?1, ?2, ?3, COALESCE(MAX(sequence), 0) + 1, ?4, ?5, ?6, ?7 \
             FROM events WHERE session_id = ?2",
        )
        .bind(&id)
        .bind(session_id.as_str())
        .bind(turn_id.map(|t| t.as_str().to_string()))
        .bind(event_type)
        .bind(&payload)
        .bind(now.to_rfc3339())
        .bind(EVENT_SCHEMA_VERSION)
        .execute(self.db.pool())
        .await?;
        let row = sqlx::query_as::<_, EventRecord>(
            "SELECT id, session_id, turn_id, sequence, type AS event_type, payload, created_at, \
             schema_version FROM events WHERE id = ?1",
        )
        .bind(&id)
        .fetch_one(self.db.pool())
        .await?;
        Ok(row)
    }

    /// Append many events as one transaction, assigning one contiguous
    /// sequence range in the order given.
    ///
    /// Same durability and redaction contract as [`Self::append`]; the
    /// difference is cost. Per-event append pays a `MAX(sequence)` aggregate,
    /// an INSERT and a readback SELECT — two round-trips each. A real
    /// Multi-Agent turn (parent plus three explorer children, all emitting into
    /// one bounded channel) out-produced that drain rate, overflowed the
    /// channel, and the run was cancelled. Here the aggregate and the commit
    /// are paid once for the whole burst, and each record is built from what
    /// was just written instead of read back.
    ///
    /// Every payload is redacted and validated **before** any INSERT, so one
    /// malformed member refuses the whole batch without consuming a sequence
    /// or persisting a sibling.
    pub async fn append_batch(
        &self,
        session_id: &SessionId,
        turn_id: Option<&TurnId>,
        events: &[(&str, &str)],
        now: Timestamp,
    ) -> Result<Vec<EventRecord>, StorageError> {
        if events.is_empty() {
            return Ok(Vec::new());
        }
        let prepared = events
            .iter()
            .map(|(event_type, payload)| {
                let payload = crate::redact_json_payload_for_session(
                    &format!("event (type '{event_type}')"),
                    payload,
                    Some(session_id.as_str()),
                )?;
                Ok((
                    leveler_core::EventId::generate().into_inner(),
                    (*event_type).to_string(),
                    payload,
                ))
            })
            .collect::<Result<Vec<_>, StorageError>>()?;

        let created_at = now.to_rfc3339();
        let turn = turn_id.map(|t| t.as_str().to_string());
        let mut tx = self.db.pool().begin().await?;
        // One aggregate for the whole range. The transaction plus the UNIQUE
        // index on (session_id, sequence) is what makes that safe against a
        // concurrent writer: a racing batch fails loudly rather than
        // interleaving silently.
        let (base,): (i64,) =
            sqlx::query_as("SELECT COALESCE(MAX(sequence), 0) FROM events WHERE session_id = ?1")
                .bind(session_id.as_str())
                .fetch_one(&mut *tx)
                .await?;

        let mut records = Vec::with_capacity(prepared.len());
        for (offset, (id, event_type, payload)) in prepared.into_iter().enumerate() {
            let sequence = base + offset as i64 + 1;
            sqlx::query(
                "INSERT INTO events \
                 (id, session_id, turn_id, sequence, type, payload, created_at, schema_version) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
            )
            .bind(&id)
            .bind(session_id.as_str())
            .bind(&turn)
            .bind(sequence)
            .bind(&event_type)
            .bind(&payload)
            .bind(&created_at)
            .bind(EVENT_SCHEMA_VERSION)
            .execute(&mut *tx)
            .await?;
            records.push(EventRecord {
                id,
                session_id: session_id.as_str().to_string(),
                turn_id: turn.clone(),
                sequence,
                event_type,
                payload,
                created_at: created_at.clone(),
                schema_version: EVENT_SCHEMA_VERSION,
            });
        }
        tx.commit().await?;
        Ok(records)
    }

    /// All events of a session in sequence order.
    pub async fn load(&self, session_id: &SessionId) -> Result<Vec<EventRecord>, StorageError> {
        self.load_after(session_id, 0).await
    }

    /// The highest sequence persisted for a session — the resync anchor a
    /// snapshot advertises. `None` when the session has no events yet.
    pub async fn latest_sequence(
        &self,
        session_id: &SessionId,
    ) -> Result<Option<i64>, StorageError> {
        let row: Option<(Option<i64>,)> =
            sqlx::query_as("SELECT MAX(sequence) FROM events WHERE session_id = ?1")
                .bind(session_id.as_str())
                .fetch_optional(self.db.pool())
                .await?;
        Ok(row.and_then(|(seq,)| seq))
    }

    /// Events with `sequence > after`, in sequence order.
    pub async fn load_after(
        &self,
        session_id: &SessionId,
        after: i64,
    ) -> Result<Vec<EventRecord>, StorageError> {
        let rows = sqlx::query_as::<_, EventRecord>(
            "SELECT id, session_id, turn_id, sequence, type AS event_type, payload, created_at, \
             schema_version FROM events WHERE session_id = ?1 AND sequence > ?2 ORDER BY sequence",
        )
        .bind(session_id.as_str())
        .bind(after)
        .fetch_all(self.db.pool())
        .await?;
        Ok(rows)
    }

    /// Inclusive sequence window `[from_seq, to_seq]`.
    pub async fn load_window(
        &self,
        session_id: &SessionId,
        from_seq: i64,
        to_seq: i64,
    ) -> Result<Vec<EventRecord>, StorageError> {
        let rows = sqlx::query_as::<_, EventRecord>(
            "SELECT id, session_id, turn_id, sequence, type AS event_type, payload, created_at, \
             schema_version FROM events \
             WHERE session_id = ?1 AND sequence >= ?2 AND sequence <= ?3 ORDER BY sequence",
        )
        .bind(session_id.as_str())
        .bind(from_seq)
        .bind(to_seq)
        .fetch_all(self.db.pool())
        .await?;
        Ok(rows)
    }

    /// Per-type counts for a session.
    pub async fn count_by_type(
        &self,
        session_id: &SessionId,
    ) -> Result<Vec<(String, i64)>, StorageError> {
        let rows: Vec<(String, i64)> = sqlx::query_as(
            "SELECT type, COUNT(*) FROM events WHERE session_id = ?1 GROUP BY type ORDER BY MIN(sequence)",
        )
        .bind(session_id.as_str())
        .fetch_all(self.db.pool())
        .await?;
        Ok(rows)
    }

    /// Events whose `type` is in `types`, in sequence order.
    ///
    /// Observatory session-wide aggregates use this so a query loads only the
    /// relevant lifecycle rows (e.g. `tool_call_started` / `tool_call_finished`)
    /// instead of the full session log. Not a TUI dump.
    pub async fn load_by_types(
        &self,
        session_id: &SessionId,
        types: &[&str],
    ) -> Result<Vec<EventRecord>, StorageError> {
        if types.is_empty() {
            return Ok(Vec::new());
        }
        let types_json = serde_json::to_string(types)
            .map_err(|e| StorageError::InvalidData(format!("load_by_types type list: {e}")))?;
        let rows = sqlx::query_as::<_, EventRecord>(
            "SELECT id, session_id, turn_id, sequence, type AS event_type, payload, created_at, \
             schema_version FROM events \
             WHERE session_id = ?1 AND type IN (SELECT value FROM json_each(?2)) \
             ORDER BY sequence",
        )
        .bind(session_id.as_str())
        .bind(&types_json)
        .fetch_all(self.db.pool())
        .await?;
        Ok(rows)
    }

    /// The newest event of `event_type`, optionally scoped to one turn — an
    /// indexed single-row lookup so "latest plan/ledger/snapshot" seeding never
    /// scans the whole session log.
    pub async fn load_last_by_type(
        &self,
        session_id: &SessionId,
        event_type: &str,
        turn_id: Option<&leveler_core::TurnId>,
    ) -> Result<Option<EventRecord>, StorageError> {
        let row = sqlx::query_as::<_, EventRecord>(
            "SELECT id, session_id, turn_id, sequence, type AS event_type, payload, created_at, \
             schema_version FROM events \
             WHERE session_id = ?1 AND type = ?2 AND (?3 IS NULL OR turn_id = ?3) \
             ORDER BY sequence DESC LIMIT 1",
        )
        .bind(session_id.as_str())
        .bind(event_type)
        .bind(turn_id.map(|t| t.as_str()))
        .fetch_optional(self.db.pool())
        .await?;
        Ok(row)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::session_repo::{SessionRecord, SessionRepository};
    use crate::turn_repo::TurnRepository;

    async fn db_with_session() -> (Database, SessionId) {
        let db = Database::connect_in_memory().await.unwrap();
        let record = SessionRecord::new("/repo", "goal", "mock/m", leveler_core::now());
        SessionRepository::new(&db).create(&record).await.unwrap();
        let id = SessionId::new(record.id);
        (db, id)
    }

    #[tokio::test]
    async fn load_window_is_inclusive_and_bounded() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);
        for i in 0..5 {
            repo.append(
                &session,
                None,
                "task_started",
                &format!(r#"{{"i":{i}}}"#),
                leveler_core::now(),
            )
            .await
            .unwrap();
        }
        let window = repo.load_window(&session, 2, 4).await.unwrap();
        let seqs: Vec<i64> = window.iter().map(|r| r.sequence).collect();
        assert_eq!(seqs, vec![2, 3, 4]);
        let counts = repo.count_by_type(&session).await.unwrap();
        assert_eq!(counts, vec![("task_started".into(), 5)]);
    }

    #[tokio::test]
    async fn load_by_types_returns_only_requested_types_in_sequence() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);
        for i in 0..3 {
            repo.append(
                &session,
                None,
                "assistant_message",
                &format!(r#"{{"i":{i}}}"#),
                leveler_core::now(),
            )
            .await
            .unwrap();
            repo.append(
                &session,
                None,
                "tool_call_started",
                &format!(r#"{{"i":{i}}}"#),
                leveler_core::now(),
            )
            .await
            .unwrap();
            repo.append(
                &session,
                None,
                "tool_call_finished",
                &format!(r#"{{"i":{i}}}"#),
                leveler_core::now(),
            )
            .await
            .unwrap();
        }
        let rows = repo
            .load_by_types(&session, &["tool_call_started", "tool_call_finished"])
            .await
            .unwrap();
        let tags: Vec<&str> = rows.iter().map(|r| r.event_type.as_str()).collect();
        assert_eq!(
            tags,
            [
                "tool_call_started",
                "tool_call_finished",
                "tool_call_started",
                "tool_call_finished",
                "tool_call_started",
                "tool_call_finished",
            ]
        );
        let seqs: Vec<i64> = rows.iter().map(|r| r.sequence).collect();
        assert_eq!(seqs, vec![2, 3, 5, 6, 8, 9]);
        assert!(repo.load_by_types(&session, &[]).await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn append_assigns_gapless_sequences() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);

        for i in 0..5 {
            let rec = repo
                .append(
                    &session,
                    None,
                    "task_started",
                    &format!(r#"{{"i":{i}}}"#),
                    leveler_core::now(),
                )
                .await
                .unwrap();
            assert_eq!(rec.sequence, i + 1, "sequences are 1-based and gapless");
        }

        let loaded = repo.load(&session).await.unwrap();
        assert_eq!(
            loaded.iter().map(|e| e.sequence).collect::<Vec<_>>(),
            vec![1, 2, 3, 4, 5]
        );
        assert_eq!(loaded[0].event_type, "task_started");
        assert_eq!(loaded[2].payload, r#"{"i":2}"#);
    }

    /// A batch is one transaction assigning one contiguous sequence range.
    /// The pump persists bursts this way: a real Multi-Agent turn (parent plus
    /// three explorer children, session `446c71ad`) produced canonical events
    /// faster than one-INSERT-plus-one-readback per event could drain them, the
    /// bounded channel overflowed, and the run was cancelled. Ordering and
    /// gaplessness are what must survive the change.
    #[tokio::test]
    async fn append_batch_assigns_one_contiguous_range_in_order() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);

        repo.append(
            &session,
            None,
            "task_started",
            r#"{"i":0}"#,
            leveler_core::now(),
        )
        .await
        .unwrap();

        let payloads: Vec<String> = (1..=4).map(|i| format!(r#"{{"i":{i}}}"#)).collect();
        let batch: Vec<(&str, &str)> = payloads
            .iter()
            .map(|p| ("tool_call_finished", p.as_str()))
            .collect();
        let rows = repo
            .append_batch(&session, None, &batch, leveler_core::now())
            .await
            .unwrap();

        assert_eq!(
            rows.iter().map(|r| r.sequence).collect::<Vec<_>>(),
            vec![2, 3, 4, 5],
            "a batch continues the session's sequence without gaps"
        );

        let loaded = repo.load(&session).await.unwrap();
        assert_eq!(
            loaded.iter().map(|e| e.sequence).collect::<Vec<_>>(),
            vec![1, 2, 3, 4, 5]
        );
        assert_eq!(
            loaded
                .iter()
                .map(|e| e.payload.as_str())
                .collect::<Vec<_>>(),
            vec![
                r#"{"i":0}"#,
                r#"{"i":1}"#,
                r#"{"i":2}"#,
                r#"{"i":3}"#,
                r#"{"i":4}"#
            ],
            "emission order is preserved inside the batch"
        );
    }

    /// An empty batch is a no-op: not an error, and it consumes no sequence.
    #[tokio::test]
    async fn append_batch_of_nothing_touches_nothing() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);
        assert!(
            repo.append_batch(&session, None, &[], leveler_core::now())
                .await
                .unwrap()
                .is_empty()
        );
        assert!(repo.load(&session).await.unwrap().is_empty());
    }

    /// Redaction and validation run before any INSERT, exactly as for a single
    /// append: one malformed member refuses the whole batch without consuming a
    /// sequence or landing a sibling.
    #[tokio::test]
    async fn a_malformed_member_rejects_the_whole_batch_before_insert() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);
        let outcome = repo
            .append_batch(
                &session,
                None,
                &[
                    ("task_started", r#"{"ok":1}"#),
                    ("task_started", "{not json"),
                ],
                leveler_core::now(),
            )
            .await;
        assert!(
            outcome.is_err(),
            "a malformed payload must be refused loudly"
        );
        assert!(
            repo.load(&session).await.unwrap().is_empty(),
            "no sibling may be persisted when the batch is refused"
        );
    }

    #[tokio::test]
    async fn sequences_are_scoped_per_session() {
        let (db, a) = db_with_session().await;
        let record = SessionRecord::new("/repo", "other", "mock/m", leveler_core::now());
        SessionRepository::new(&db).create(&record).await.unwrap();
        let b = SessionId::new(record.id);

        let repo = EventRepository::new(&db);
        repo.append(&a, None, "x", "{}", leveler_core::now())
            .await
            .unwrap();
        let rec = repo
            .append(&b, None, "x", "{}", leveler_core::now())
            .await
            .unwrap();
        assert_eq!(rec.sequence, 1, "sequences must not leak across sessions");
    }

    #[tokio::test]
    async fn new_events_carry_the_current_schema_version() {
        let (db, session) = db_with_session().await;
        let rec = EventRepository::new(&db)
            .append(&session, None, "x", "{}", leveler_core::now())
            .await
            .unwrap();
        assert_eq!(rec.schema_version, EVENT_SCHEMA_VERSION);
    }

    #[tokio::test]
    async fn duplicate_sequence_is_rejected_by_the_unique_index() {
        let (db, session) = db_with_session().await;
        EventRepository::new(&db)
            .append(&session, None, "x", "{}", leveler_core::now())
            .await
            .unwrap();
        // A manual row colliding on (session_id, sequence=1) must be refused —
        // the log can never silently reorder or overwrite.
        let dup = sqlx::query(
            "INSERT INTO events \
             (id, session_id, turn_id, sequence, type, payload, created_at, schema_version) \
             VALUES (?1, ?2, NULL, 1, 'x', '{}', ?3, 1)",
        )
        .bind(leveler_core::EventId::generate().into_inner())
        .bind(session.as_str())
        .bind(leveler_core::now().to_rfc3339())
        .execute(db.pool())
        .await;
        assert!(
            dup.is_err(),
            "duplicate sequence must violate the unique index"
        );
    }

    #[tokio::test]
    async fn load_after_returns_only_newer_events() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);
        for _ in 0..3 {
            repo.append(&session, None, "x", "{}", leveler_core::now())
                .await
                .unwrap();
        }
        let newer = repo.load_after(&session, 1).await.unwrap();
        assert_eq!(
            newer.iter().map(|e| e.sequence).collect::<Vec<_>>(),
            vec![2, 3]
        );
    }

    #[tokio::test]
    async fn events_can_belong_to_a_turn() {
        let (db, session) = db_with_session().await;
        let turn = TurnRepository::new(&db)
            .start(&session, "user", None, leveler_core::now())
            .await
            .unwrap();
        let repo = EventRepository::new(&db);
        let rec = repo
            .append(
                &session,
                Some(&leveler_core::TurnId::new(turn.id.clone())),
                "turn_started",
                "{}",
                leveler_core::now(),
            )
            .await
            .unwrap();
        assert_eq!(rec.turn_id.as_deref(), Some(turn.id.as_str()));
    }

    /// Legacy-shaped rows (pre-0003 columns omitted) must read the migration
    /// defaults — this is what an existing database sees after upgrading.
    #[tokio::test]
    async fn legacy_rows_read_migration_defaults() {
        let (db, session) = db_with_session().await;
        // A pre-0003 sessions row never wrote mode/sandbox/kind/outcome.
        let (mode, sandbox, kind, outcome): (String, i64, String, Option<String>) =
            sqlx::query_as("SELECT mode, sandbox, kind, outcome FROM sessions WHERE id = ?1")
                .bind(session.as_str())
                .fetch_one(db.pool())
                .await
                .unwrap();
        // 0003 default was workspace_write; 0012/0013 remap to assisted profiles.
        assert_eq!(mode, "assisted");
        assert_eq!(sandbox, 0);
        assert_eq!(kind, "direct");
        assert_eq!(outcome, None);
    }

    /// R007 F2 accident regression: an assistant narration containing
    /// `secret PASSWORD:"…"` must never persist as malformed JSON. Pre-fix,
    /// the serialized-text scrubber swallowed the JSON string's closing quote
    /// and the structural bytes after it; replay then hard-failed the whole
    /// session ("unreplayable event payload"). If this test is deleted, that
    /// exact R007 corruption can return unnoticed.
    #[tokio::test]
    async fn append_never_persists_malformed_json_when_redacting() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);
        // Byte-exact R007 corrupting shape (narration ends with `PASSWORD:` at
        // the string boundary) + a companion shape carrying a real secret.
        let accident = r#"{"payload":{"text":"Secrets 标签页有 \"Add new\" 按钮。点击添加 secret PASSWORD:"},"type":"assistant_message"}"#;
        let with_secret = r#"{"payload":{"text":"add secret PASSWORD:\"hunter2-secret-value\""},"type":"assistant_message"}"#;
        for payload in [accident, with_secret] {
            let record = repo
                .append(
                    &session,
                    None,
                    "assistant_message",
                    payload,
                    leveler_core::now(),
                )
                .await
                .unwrap();
            let value: serde_json::Value = serde_json::from_str(&record.payload)
                .expect("persisted payload must stay valid JSON");
            assert_eq!(value["type"], "assistant_message");
        }
        assert!(
            !repo.load(&session).await.unwrap()[1]
                .payload
                .contains("hunter2-secret-value"),
            "secret must not persist"
        );
        // The whole log must stay loadable AND parseable — the replay contract.
        for row in repo.load(&session).await.unwrap() {
            serde_json::from_str::<serde_json::Value>(&row.payload)
                .expect("every persisted event must parse");
        }
    }

    /// A payload that is not valid JSON is refused loudly BEFORE any sequence
    /// is assigned — a failed append must never leave a gap (§42).
    #[tokio::test]
    async fn invalid_payload_is_refused_without_consuming_a_sequence() {
        let (db, session) = db_with_session().await;
        let repo = EventRepository::new(&db);
        repo.append(&session, None, "x", r#"{"i":1}"#, leveler_core::now())
            .await
            .unwrap();
        let err = repo
            .append(&session, None, "x", r#"{"truncated":"#, leveler_core::now())
            .await
            .expect_err("malformed payload must be refused");
        assert!(
            matches!(err, StorageError::InvalidData(_)),
            "refusal must be the typed invalid-data error, got: {err:?}"
        );
        let rec = repo
            .append(&session, None, "x", r#"{"i":2}"#, leveler_core::now())
            .await
            .unwrap();
        assert_eq!(rec.sequence, 2, "failed append must not consume a sequence");
        let seqs: Vec<i64> = repo
            .load(&session)
            .await
            .unwrap()
            .iter()
            .map(|e| e.sequence)
            .collect();
        assert_eq!(seqs, vec![1, 2], "gapless after a refused append");
    }

    /// R007 F6 accident regression, durable-echo half: once a value has been
    /// identified as a secret for this session, it must not re-enter durable
    /// storage even when it arrives as ordinary prose with no key/value shape
    /// left for the structural pass to recognise.
    #[tokio::test]
    async fn registered_session_secret_is_scrubbed_from_assistant_prose() {
        let (db, session) = db_with_session().await;
        let secret = "hunter2-durable-echo-unique";
        leveler_core::clear_session_secrets(session.as_str());
        leveler_core::register_session_secrets(
            session.as_str(),
            &[leveler_core::DetectedSecret {
                value: secret.to_string(),
                key: "API_PASSWORD".to_string(),
            }],
        );

        let payload = serde_json::json!({
            "type": "assistant_message",
            "payload": {"text": format!("The API password is {secret}, noted.")}
        })
        .to_string();
        let record = EventRepository::new(&db)
            .append(
                &session,
                None,
                "assistant_message",
                &payload,
                leveler_core::now(),
            )
            .await
            .unwrap();

        assert!(
            !record.payload.contains(secret),
            "prose echo of a known secret must not persist: {}",
            record.payload
        );
        // The sentence around it survives, and the row is still valid JSON.
        let value: serde_json::Value = serde_json::from_str(&record.payload).unwrap();
        assert!(
            value["payload"]["text"]
                .as_str()
                .unwrap()
                .contains("The API password is"),
            "{record:?}"
        );
        leveler_core::clear_session_secrets(session.as_str());
    }

    /// A secret registered for one session must not be scrubbed out of a
    /// different session's rows — the registry is session-scoped.
    #[tokio::test]
    async fn registered_secrets_do_not_cross_sessions() {
        let (db, session_a) = db_with_session().await;
        let record = SessionRecord::new("/repo", "other", "mock/m", leveler_core::now());
        SessionRepository::new(&db).create(&record).await.unwrap();
        let session_b = SessionId::new(record.id);

        let secret = "alpha-cross-session-value";
        leveler_core::clear_session_secrets(session_a.as_str());
        leveler_core::clear_session_secrets(session_b.as_str());
        leveler_core::register_session_secrets(
            session_a.as_str(),
            &[leveler_core::DetectedSecret {
                value: secret.to_string(),
                key: "TOKEN".to_string(),
            }],
        );

        let payload =
            serde_json::json!({"type": "diagnostic", "payload": {"text": secret}}).to_string();
        let repo = EventRepository::new(&db);
        let in_a = repo
            .append(
                &session_a,
                None,
                "diagnostic",
                &payload,
                leveler_core::now(),
            )
            .await
            .unwrap();
        let in_b = repo
            .append(
                &session_b,
                None,
                "diagnostic",
                &payload,
                leveler_core::now(),
            )
            .await
            .unwrap();

        assert!(!in_a.payload.contains(secret), "own session must scrub");
        assert!(
            in_b.payload.contains(secret),
            "another session must be unaffected: {}",
            in_b.payload
        );
        leveler_core::clear_session_secrets(session_a.as_str());
        leveler_core::clear_session_secrets(session_b.as_str());
    }

    #[tokio::test]
    async fn append_redacts_json_secrets() {
        let (db, session) = db_with_session().await;
        let record = EventRepository::new(&db)
            .append(
                &session,
                None,
                "diagnostic",
                r#"{"Authorization":"Bearer event-secret-value"}"#,
                leveler_core::now(),
            )
            .await
            .unwrap();
        assert!(!record.payload.contains("event-secret-value"), "{record:?}");
        assert!(record.payload.contains("[REDACTED]"), "{record:?}");
    }
}
