//! Persistence for normalized model-request diagnostics.

use leveler_core::{SessionId, Timestamp};

use crate::{Database, StorageError};

/// Which lane a model call belongs to. The drive loop's rounds are the work;
/// everything else is overhead the runtime chose to spend, and cost
/// attribution has to be able to tell them apart.
///
/// The stored tokens are the stable contract shared with the engine's
/// taxonomy; this crate keeps its own mirror because it does not depend on the
/// engine. A token that is not recognized reads as [`Self::Round`], the
/// migration's backfill for rows written before the column existed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModelCallKind {
    /// A main-loop round: the model deciding what to do next.
    Round,
    /// The summarization behind a compaction fold.
    Compaction,
    /// Semantic memory-candidate extraction from the user's own turns.
    MemoryExtraction,
    /// An idle prompt suggestion.
    PromptSuggestion,
    /// An idle "welcome back" summary.
    AwaySummary,
    /// The bounded wording pass for a manual recap.
    SemanticRecap,
    /// An explicit `/btw` side question.
    SideQuestion,
    /// A provider health probe (never a session's cost).
    ProviderProbe,
    /// A bounded call the runtime makes on its own account. Never a second
    /// model judging the first — that class of call no longer exists.
    Advisory,
}

impl ModelCallKind {
    /// The stored token. Stable: it is a persisted value, not a display name.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Round => "round",
            Self::Compaction => "compaction",
            Self::MemoryExtraction => "memory_extraction",
            Self::PromptSuggestion => "prompt_suggestion",
            Self::AwaySummary => "away_summary",
            Self::SemanticRecap => "semantic_recap",
            Self::SideQuestion => "side_question",
            Self::ProviderProbe => "provider_probe",
            Self::Advisory => "advisory",
        }
    }

    /// Parse a stored token. An unknown one reads as `Round`, matching the
    /// migration's backfill: every row written before the column existed was
    /// a main-loop round.
    pub fn from_stored(value: &str) -> Self {
        match value {
            "compaction" => Self::Compaction,
            "memory_extraction" => Self::MemoryExtraction,
            "prompt_suggestion" => Self::PromptSuggestion,
            "away_summary" => Self::AwaySummary,
            "semantic_recap" => Self::SemanticRecap,
            "side_question" => Self::SideQuestion,
            "provider_probe" => Self::ProviderProbe,
            "advisory" => Self::Advisory,
            _ => Self::Round,
        }
    }
}

/// One model attempt, recorded for diagnostics rather than replay: this
/// row holds no prompt or response text, only the shape of the exchange.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelRequestRecord {
    /// Goal/root-turn budget owner. None for legacy or session-only auxiliary calls.
    pub budget_scope: Option<String>,
    /// Admission estimate kept separately from observed provider token totals.
    pub estimated_tokens: Option<u64>,
    /// Caller-supplied primary key, generated by the runtime. It is NOT the
    /// provider's request id: a duplicate of those used to abort the turn
    /// over a diagnostics row (see migration 0021).
    pub id: String,
    /// The provider's own request id, when it reported one. A diagnostic
    /// attribute — repeats are the provider's business, not this table's.
    pub provider_request_id: Option<String>,
    /// Owning session. Not stored on read-back from [`ModelRequestRepository::load_for_session`];
    /// it is filled in from the queried session instead.
    pub session_id: SessionId,
    /// Provider key as configured (e.g. `deepseek`), not the vendor's own name.
    pub provider: String,
    /// Provider-side model id actually sent on the wire, which may differ from
    /// the local alias the user typed.
    pub model: String,
    /// Prompt tokens reported by the provider. Persisted as a signed 64-bit
    /// integer, so a value above `i64::MAX` is clamped on write.
    pub input_tokens: u64,
    /// Completion tokens, clamped on write like [`Self::input_tokens`].
    pub output_tokens: u64,
    /// Prompt tokens the provider served from its own prefix cache — a SUBSET
    /// of [`Self::input_tokens`], not an addition to it. `None` means the
    /// writer did not record it (every row older than migration 0022);
    /// `Some(0)` means the provider reported no cache hit. The two must not be
    /// collapsed: one is an absence of measurement, the other a measurement.
    pub cached_input_tokens: Option<u64>,
    /// Completion tokens the provider attributed to reasoning — a SUBSET of
    /// [`Self::output_tokens`], never an amount to add to it.
    ///
    /// `None` means the provider reported no breakdown on this call (or the
    /// row predates migration 0030); `Some(0)` means it reported that no
    /// reasoning tokens were spent. The distinction is the same one
    /// [`Self::cached_input_tokens`] makes: one is an absence of measurement,
    /// the other a measurement.
    pub reasoning_tokens: Option<u64>,
    /// The runtime's own estimate of the prompt it sent, priced by the ONE
    /// shared estimator over the provider-visible request projection.
    ///
    /// Beside — never instead of — [`Self::input_tokens`]: the provider's
    /// number is what was billed, this is what the runtime expected to send,
    /// and the pair is what makes an estimate error visible. `None` means no
    /// projection was measured (an auxiliary call such as a compaction
    /// summary, a sub-agent record that carried none, or a row written before
    /// this column existed).
    pub projected_input_tokens: Option<u64>,
    /// The runtime's own estimate of how much of that projected prompt was the
    /// historical-reasoning channel — the replayed thinking this route carried.
    ///
    /// A slice of the INPUT, and therefore a different figure from
    /// [`Self::reasoning_tokens`] (a subset of the provider's OUTPUT).
    /// `Some(0)` means the request was projected and carried no reasoning;
    /// `None` means no projection was measured for this call.
    pub projected_reasoning_tokens: Option<u64>,
    /// Estimated cost of this call in micro-USD, computed from the usage above
    /// and the model's configured pricing at the time it ran. `None` when no
    /// pricing was configured, so a session's cost sums only over rows that
    /// actually have one.
    pub cost_usd_micros: Option<u64>,
    /// The sub-agent that made the call, or `None` for the root session's own
    /// calls. This is what lets a reviewer's spend be separated from the work
    /// it was reviewing.
    pub agent_id: Option<String>,
    /// Provider's stop reason (`stop`, `length`, `tool_calls`, …). `None` when
    /// the call never reached a normal end — see [`Self::error_kind`].
    pub finish_reason: Option<String>,
    /// Failure classification when the call did not complete. Mutually
    /// exclusive with [`Self::finish_reason`] in practice, though nothing
    /// enforces that here.
    pub error_kind: Option<String>,
    /// Wall-clock duration of the attempt. `None` when it was never measured.
    /// Legacy rows may aggregate a logical call including retry backoff.
    pub latency_ms: Option<u64>,
    /// Wall-clock duration of the attempt whose output was used. The gap
    /// between this and [`Self::latency_ms`] is retry and backoff overhead.
    /// `None` for rows older than migration 0031.
    pub attempt_ms: Option<u64>,
    /// Request start to response headers. `None` for rows older than
    /// migration 0031.
    pub connect_ms: Option<u64>,
    /// Request start to the first stream event — the real time-to-first-token.
    /// `None` when the provider never produced an event, or for rows older
    /// than migration 0031. It is NOT a measured zero for an old row.
    pub ttft_ms: Option<u64>,
    /// Longest stretch inside the stream with no event at all: the stall a
    /// user would have seen as a frozen screen. `None` for rows older than
    /// migration 0031.
    pub max_event_gap_ms: Option<u64>,
    /// Retry contribution: 1 for a retried attempt, 0 for an initial attempt.
    /// Legacy rows store total retries for a logical call. Summation preserves
    /// total retry count; row count is not exact physical traffic for legacy data.
    pub retry_count: u32,
    /// Which lane this call belongs to.
    pub kind: ModelCallKind,
    /// When the call finished. Stored as RFC 3339 text and re-parsed on read,
    /// so an unparseable value surfaces as [`StorageError::InvalidData`].
    pub created_at: Timestamp,
    /// The reasoning effort the call requested, as sent on the wire. `None`
    /// for a request that named none and for rows older than migration 0026.
    pub reasoning_effort: Option<String>,
}

/// One `model_requests` row as the loader reads it.
///
/// A named struct rather than a positional tuple: `reasoning_tokens` pushed the
/// SELECT past SQLx's 16-element `FromRow` tuple bound, and naming the columns
/// makes the mapping checkable against the query instead of counting positions.
#[derive(sqlx::FromRow)]
struct ModelRequestRow {
    budget_scope: Option<String>,
    estimated_tokens: Option<i64>,
    id: String,
    provider: String,
    model: String,
    input_tokens: i64,
    output_tokens: i64,
    finish_reason: Option<String>,
    error_kind: Option<String>,
    latency_ms: Option<i64>,
    attempt_ms: Option<i64>,
    connect_ms: Option<i64>,
    ttft_ms: Option<i64>,
    max_event_gap_ms: Option<i64>,
    retry_count: i64,
    created_at: String,
    kind: String,
    provider_request_id: Option<String>,
    cached_input_tokens: Option<i64>,
    cost_usd_micros: Option<i64>,
    agent_id: Option<String>,
    reasoning_effort: Option<String>,
    reasoning_tokens: Option<i64>,
    projected_input_tokens: Option<i64>,
    projected_reasoning_tokens: Option<i64>,
}

/// Read/write access to the `model_requests` table, borrowed from a [`Database`].
pub struct ModelRequestRepository<'a> {
    db: &'a Database,
}

impl<'a> ModelRequestRepository<'a> {
    /// Borrow `db` for the lifetime of this repository handle.
    pub fn new(db: &'a Database) -> Self {
        Self { db }
    }

    /// Append one record. Token counts and latency are clamped into the signed
    /// range SQLite stores; no other normalization happens.
    ///
    /// # Errors
    ///
    /// Fails if the row cannot be written — including a duplicate
    /// [`ModelRequestRecord::id`], which the database rejects.
    pub async fn insert(&self, record: &ModelRequestRecord) -> Result<(), StorageError> {
        sqlx::query(
            "INSERT INTO model_requests \
             (id, session_id, provider, model, input_tokens, output_tokens, finish_reason, \
              error_kind, latency_ms, retry_count, created_at, kind, \
              provider_request_id, cached_input_tokens, cost_usd_micros, agent_id, \
              reasoning_effort, reasoning_tokens, attempt_ms, connect_ms, ttft_ms, \
              max_event_gap_ms, projected_input_tokens, projected_reasoning_tokens, budget_scope, estimated_tokens) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26)",
        )
        .bind(&record.id)
        .bind(record.session_id.as_str())
        .bind(&record.provider)
        .bind(&record.model)
        .bind(record.input_tokens.min(i64::MAX as u64) as i64)
        .bind(record.output_tokens.min(i64::MAX as u64) as i64)
        .bind(&record.finish_reason)
        .bind(&record.error_kind)
        .bind(
            record
                .latency_ms
                .map(|value| value.min(i64::MAX as u64) as i64),
        )
        .bind(i64::from(record.retry_count))
        .bind(record.created_at.to_rfc3339())
        .bind(record.kind.as_str())
        .bind(&record.provider_request_id)
        .bind(
            record
                .cached_input_tokens
                .map(|value| value.min(i64::MAX as u64) as i64),
        )
        .bind(
            record
                .cost_usd_micros
                .map(|value| value.min(i64::MAX as u64) as i64),
        )
        .bind(&record.agent_id)
        .bind(&record.reasoning_effort)
        .bind(
            record
                .reasoning_tokens
                .map(|value| value.min(i64::MAX as u64) as i64),
        )
        .bind(record.attempt_ms.map(|value| value.min(i64::MAX as u64) as i64))
        .bind(record.connect_ms.map(|value| value.min(i64::MAX as u64) as i64))
        .bind(record.ttft_ms.map(|value| value.min(i64::MAX as u64) as i64))
        .bind(
            record
                .max_event_gap_ms
                .map(|value| value.min(i64::MAX as u64) as i64),
        )
        .bind(
            record
                .projected_input_tokens
                .map(|value| value.min(i64::MAX as u64) as i64),
        )
        .bind(
            record
                .projected_reasoning_tokens
                .map(|value| value.min(i64::MAX as u64) as i64),
        )
        .bind(&record.budget_scope)
        .bind(record.estimated_tokens.map(|value| value.min(i64::MAX as u64) as i64))
        .execute(self.db.pool())
        .await?;
        Ok(())
    }

    /// Every record for `session_id`, oldest first (ties broken by insertion
    /// order, so calls made within the same second keep their sequence).
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::InvalidData`] if a stored timestamp does not
    /// parse; the whole load fails rather than skipping the bad row.
    pub async fn load_for_session(
        &self,
        session_id: &SessionId,
    ) -> Result<Vec<ModelRequestRecord>, StorageError> {
        let rows = sqlx::query_as::<_, ModelRequestRow>(
            "SELECT id, provider, model, input_tokens, output_tokens, finish_reason, error_kind, \
                    latency_ms, retry_count, created_at, kind, provider_request_id, \
                    cached_input_tokens, cost_usd_micros, agent_id, reasoning_effort, \
                    reasoning_tokens, attempt_ms, connect_ms, ttft_ms, max_event_gap_ms, \
                    projected_input_tokens, projected_reasoning_tokens, budget_scope, estimated_tokens \
             FROM model_requests WHERE session_id = ?1 ORDER BY created_at, rowid",
        )
        .bind(session_id.as_str())
        .fetch_all(self.db.pool())
        .await?;

        rows.into_iter()
            .map(|row| {
                let ModelRequestRow {
                    budget_scope,
                    estimated_tokens,
                    id,
                    provider,
                    model,
                    input_tokens,
                    output_tokens,
                    finish_reason,
                    error_kind,
                    latency_ms,
                    attempt_ms,
                    connect_ms,
                    ttft_ms,
                    max_event_gap_ms,
                    retry_count,
                    created_at,
                    kind,
                    provider_request_id,
                    cached_input_tokens,
                    cost_usd_micros,
                    agent_id,
                    reasoning_effort,
                    reasoning_tokens,
                    projected_input_tokens,
                    projected_reasoning_tokens,
                } = row;
                {
                    Ok(ModelRequestRecord {
                        budget_scope,
                        estimated_tokens: estimated_tokens.map(|value| value.max(0) as u64),
                        id,
                        session_id: session_id.clone(),
                        provider,
                        model,
                        input_tokens: input_tokens.max(0) as u64,
                        output_tokens: output_tokens.max(0) as u64,
                        finish_reason,
                        error_kind,
                        latency_ms: latency_ms.map(|value| value.max(0) as u64),
                        attempt_ms: attempt_ms.map(|value| value.max(0) as u64),
                        connect_ms: connect_ms.map(|value| value.max(0) as u64),
                        ttft_ms: ttft_ms.map(|value| value.max(0) as u64),
                        max_event_gap_ms: max_event_gap_ms.map(|value| value.max(0) as u64),
                        retry_count: retry_count.clamp(0, i64::from(u32::MAX)) as u32,
                        kind: ModelCallKind::from_stored(&kind),
                        provider_request_id,
                        cached_input_tokens: cached_input_tokens.map(|value| value.max(0) as u64),
                        cost_usd_micros: cost_usd_micros.map(|value| value.max(0) as u64),
                        agent_id,
                        created_at: created_at.parse::<Timestamp>().map_err(|error| {
                            StorageError::InvalidData(format!("model request timestamp: {error}"))
                        })?,
                        reasoning_effort,
                        reasoning_tokens: reasoning_tokens.map(|value| value.max(0) as u64),
                        projected_input_tokens: projected_input_tokens
                            .map(|value| value.max(0) as u64),
                        projected_reasoning_tokens: projected_reasoning_tokens
                            .map(|value| value.max(0) as u64),
                    })
                }
            })
            .collect()
    }
}

/// What a session's recorded model calls add up to, split by who made them.
///
/// Summed from the rows themselves rather than from a running counter, so it
/// answers the question a running counter cannot: *is the durable record
/// complete?* A session whose parent spent six million tokens while its
/// reviewer spent another half million left, before migration 0022, a ledger
/// saying one number and a database holding a different one with no way to see
/// the gap.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SessionUsageTotals {
    /// How many recorded attempts were summed; legacy rows may aggregate retries.
    pub requests: u64,
    /// Prompt tokens, cached and uncached together.
    pub input_tokens: u64,
    /// Summed over rows that recorded it. Rows that did not are counted in
    /// [`Self::rows_without_cached_usage`] instead of contributing zero.
    pub cached_input_tokens: u64,
    /// Completion tokens.
    pub output_tokens: u64,
    /// Summed over rows that reported a reasoning breakdown — a subset of
    /// [`Self::output_tokens`], not an amount to add to it. Rows that reported
    /// none are counted in [`Self::rows_without_reasoning_usage`].
    pub reasoning_tokens: u64,
    /// Summed over rows that recorded a runtime projection estimate. Rows that
    /// did not are counted in [`Self::rows_without_projected_usage`] instead of
    /// contributing zero.
    pub projected_input_tokens: u64,
    /// Summed projected historical-reasoning tokens over rows that recorded a
    /// projection — a slice of [`Self::projected_input_tokens`]. Rows that
    /// recorded none are counted in [`Self::rows_without_projected_usage`].
    pub projected_reasoning_tokens: u64,
    /// Summed over rows that carry a cost. Rows without pricing are counted in
    /// [`Self::rows_without_cost`].
    pub cost_usd_micros: u64,
    /// Rows whose cached usage was never recorded — pre-0022 rows. They are
    /// counted, not treated as zero cache hits.
    pub rows_without_cached_usage: u64,
    /// Rows with no reasoning breakdown — a provider that does not report one,
    /// or a row from before migration 0030. Counted, not read as "spent no
    /// reasoning".
    pub rows_without_reasoning_usage: u64,
    /// Rows with no cost, because the model had no pricing configured or the
    /// row predates the column. Not the same as a call that cost nothing.
    pub rows_without_cost: u64,
    /// Rows with no recorded runtime projection estimate — auxiliary calls, or
    /// rows from before the column existed. Counted, not read as zero.
    pub rows_without_projected_usage: u64,
}

impl SessionUsageTotals {
    /// Prompt tokens the provider billed at the uncached rate: reported input
    /// minus the part it served from its own prefix cache.
    ///
    /// Saturating, so a provider that (mis)reports more cached tokens than
    /// input tokens yields zero rather than a negative number — and the two are
    /// never summed twice.
    pub fn uncached_input_tokens(&self) -> u64 {
        self.input_tokens.saturating_sub(self.cached_input_tokens)
    }

    fn add(&mut self, record: &ModelRequestRecord) {
        self.requests += 1;
        self.input_tokens = self.input_tokens.saturating_add(record.input_tokens);
        self.output_tokens = self.output_tokens.saturating_add(record.output_tokens);
        match record.cached_input_tokens {
            Some(value) => {
                self.cached_input_tokens = self.cached_input_tokens.saturating_add(value)
            }
            None => self.rows_without_cached_usage += 1,
        }
        match record.reasoning_tokens {
            Some(value) => self.reasoning_tokens = self.reasoning_tokens.saturating_add(value),
            None => self.rows_without_reasoning_usage += 1,
        }
        match record.projected_input_tokens {
            Some(value) => {
                self.projected_input_tokens = self.projected_input_tokens.saturating_add(value)
            }
            None => self.rows_without_projected_usage += 1,
        }
        // Summed independently of the input total but counted with it: the two
        // are written by the same projection, so a row with one and not the
        // other is the same "no projection measured" row.
        if let Some(value) = record.projected_reasoning_tokens {
            self.projected_reasoning_tokens = self.projected_reasoning_tokens.saturating_add(value);
        }
        match record.cost_usd_micros {
            Some(value) => self.cost_usd_micros = self.cost_usd_micros.saturating_add(value),
            None => self.rows_without_cost += 1,
        }
    }

    /// Whether every row contributed both a cached-usage figure and a cost. A
    /// caller showing a cost has to be able to say whether it is the whole
    /// bill or part of one.
    ///
    /// Reasoning tokens are deliberately excluded: most providers report no
    /// breakdown at all, so requiring one would report every DeepSeek-only
    /// ledger as incomplete. [`Self::rows_without_reasoning_usage`] carries
    /// that caveat instead.
    pub fn is_complete(&self) -> bool {
        self.rows_without_cached_usage == 0 && self.rows_without_cost == 0
    }
}

/// A session's usage, separated into the root's own calls and each sub-agent's.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SessionUsageReconciliation {
    /// Calls the root session made itself.
    pub root: SessionUsageTotals,
    /// Calls made by sub-agents, keyed by agent id, ordered by id.
    pub by_agent: Vec<(String, SessionUsageTotals)>,
    /// Root plus every agent. This is the figure to compare against a runtime
    /// cumulative ledger.
    pub total: SessionUsageTotals,
}

impl<'a> ModelRequestRepository<'a> {
    /// Add up a session's recorded calls, split by the agent that made them.
    ///
    /// # Errors
    ///
    /// Propagates whatever [`Self::load_for_session`] fails with.
    pub async fn reconcile_session(
        &self,
        session_id: &SessionId,
    ) -> Result<SessionUsageReconciliation, StorageError> {
        let records = self.load_for_session(session_id).await?;
        let mut out = SessionUsageReconciliation::default();
        let mut agents: std::collections::BTreeMap<String, SessionUsageTotals> =
            std::collections::BTreeMap::new();
        for record in &records {
            out.total.add(record);
            match &record.agent_id {
                Some(id) => agents.entry(id.clone()).or_default().add(record),
                None => out.root.add(record),
            }
        }
        out.by_agent = agents.into_iter().collect();
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn record(id: &str, session: &SessionId) -> ModelRequestRecord {
        ModelRequestRecord {
            budget_scope: None,
            estimated_tokens: None,
            id: id.to_string(),
            provider_request_id: None,
            session_id: session.clone(),
            provider: "deepseek".to_string(),
            model: "deepseek-v4-flash".to_string(),
            input_tokens: 1_000,
            output_tokens: 100,
            finish_reason: Some("stop".to_string()),
            error_kind: None,
            latency_ms: Some(10),
            attempt_ms: Some(9),
            connect_ms: Some(4),
            ttft_ms: Some(6),
            max_event_gap_ms: Some(2),
            retry_count: 0,
            kind: ModelCallKind::Round,
            cached_input_tokens: Some(900),
            projected_input_tokens: None,
            projected_reasoning_tokens: None,
            cost_usd_micros: Some(1_234),
            agent_id: None,
            created_at: leveler_core::now(),
            reasoning_effort: None,
            reasoning_tokens: Some(80),
        }
    }

    async fn seeded() -> (Database, SessionId) {
        let db = Database::connect_in_memory().await.unwrap();
        let session =
            SessionRecord::new("/r", "g", "deepseek/deepseek-v4-flash", leveler_core::now());
        SessionRepository::new(&db).create(&session).await.unwrap();
        let id = SessionId::new(session.id);
        (db, id)
    }

    /// T1/T2. What the provider reported is what comes back out — including
    /// the cached share, which used to be dropped between the usage struct
    /// and the row.
    #[tokio::test]
    async fn a_request_round_trips_its_usage_exactly() {
        let (db, session) = seeded().await;
        let repo = ModelRequestRepository::new(&db);
        repo.insert(&record("r-1", &session)).await.unwrap();

        let loaded = repo.load_for_session(&session).await.unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].input_tokens, 1_000);
        assert_eq!(loaded[0].output_tokens, 100);
        assert_eq!(loaded[0].cached_input_tokens, Some(900));
        assert_eq!(loaded[0].cost_usd_micros, Some(1_234));
        assert_eq!(
            loaded[0].reasoning_tokens,
            Some(80),
            "the provider's reasoning breakdown survives the round trip"
        );
    }

    #[tokio::test]
    async fn budget_scope_and_estimate_survive_without_a_progress_event() {
        use crate::ModelRequestStore;
        let (db, session) = seeded().await;
        let repo = ModelRequestRepository::new(&db);
        let mut child = record("child-before-progress", &session);
        child.budget_scope = Some("goal-a".into());
        child.agent_id = Some("reviewer".into());
        child.input_tokens = 0;
        child.output_tokens = 0;
        child.cost_usd_micros = None;
        child.estimated_tokens = Some(37);
        repo.insert(&child).await.unwrap();
        let mut other = record("other-goal", &session);
        other.budget_scope = Some("goal-b".into());
        repo.insert(&other).await.unwrap();
        repo.insert(&record("session-only", &session))
            .await
            .unwrap();

        let recovered = db.load_for_budget_scope(&session, "goal-a").await.unwrap();
        assert_eq!(recovered, vec![child]);
        assert!(
            db.load_for_budget_scope(&session, "new-goal")
                .await
                .unwrap()
                .is_empty()
        );
        let all = repo.load_for_session(&session).await.unwrap();
        let legacy = all.iter().find(|row| row.id == "session-only").unwrap();
        assert_eq!(legacy.budget_scope, None);
        assert_eq!(legacy.estimated_tokens, None);
    }

    /// The reasoning count is a subset of the completion count, so storing it
    /// changes no total: the row still reports 100 output tokens, and the cost
    /// the writer recorded is the cost of those 100.
    #[tokio::test]
    async fn a_reasoning_breakdown_is_stored_without_touching_the_output_total() {
        let (db, session) = seeded().await;
        let repo = ModelRequestRepository::new(&db);
        let mut row = record("r-reasoning", &session);
        row.output_tokens = 1_000;
        row.reasoning_tokens = Some(700);
        repo.insert(&row).await.unwrap();

        let loaded = repo.load_for_session(&session).await.unwrap();
        assert_eq!(loaded[0].output_tokens, 1_000);
        assert_eq!(loaded[0].reasoning_tokens, Some(700));

        let rec = repo.reconcile_session(&session).await.unwrap();
        assert_eq!(rec.total.output_tokens, 1_000);
        assert_eq!(rec.total.reasoning_tokens, 700);
        assert_eq!(rec.total.rows_without_reasoning_usage, 0);
        assert_eq!(rec.total.cost_usd_micros, 1_234);
    }

    /// A row that reported no breakdown is counted, not summed as zero.
    #[tokio::test]
    async fn a_missing_reasoning_breakdown_is_counted_not_read_as_zero() {
        let (db, session) = seeded().await;
        let repo = ModelRequestRepository::new(&db);
        let mut absent = record("r-absent", &session);
        absent.reasoning_tokens = None;
        let mut measured_zero = record("r-zero", &session);
        measured_zero.reasoning_tokens = Some(0);
        repo.insert(&absent).await.unwrap();
        repo.insert(&measured_zero).await.unwrap();

        let loaded = repo.load_for_session(&session).await.unwrap();
        assert_eq!(loaded[0].reasoning_tokens, None);
        assert_eq!(loaded[1].reasoning_tokens, Some(0));

        let rec = repo.reconcile_session(&session).await.unwrap();
        assert_eq!(rec.total.reasoning_tokens, 0);
        assert_eq!(rec.total.rows_without_reasoning_usage, 1);
    }

    /// The projected estimate round-trips beside the provider's own prompt
    /// count, and the two are never collapsed: an absent projection stays
    /// `None` rather than becoming a zero, and the uncached remainder is
    /// derived, not stored twice.
    #[tokio::test]
    async fn projected_input_is_recorded_beside_provider_usage() {
        let (db, session) = seeded().await;
        let repo = ModelRequestRepository::new(&db);
        let mut measured = record("r1", &session);
        measured.input_tokens = 66_282;
        measured.cached_input_tokens = Some(51_000);
        measured.projected_input_tokens = Some(65_900);
        measured.projected_reasoning_tokens = Some(17_100);
        repo.insert(&measured).await.unwrap();
        let mut auxiliary = record("r2", &session);
        auxiliary.input_tokens = 0;
        auxiliary.projected_input_tokens = None;
        auxiliary.projected_reasoning_tokens = None;
        auxiliary.cached_input_tokens = Some(0);
        repo.insert(&auxiliary).await.unwrap();

        let loaded = repo.load_for_session(&session).await.unwrap();
        assert_eq!(loaded[0].projected_input_tokens, Some(65_900));
        assert_eq!(
            loaded[0].projected_reasoning_tokens,
            Some(17_100),
            "the replayed-reasoning slice round-trips with the projection"
        );
        assert_eq!(
            loaded[1].projected_input_tokens, None,
            "an auxiliary call that projected nothing is absent, not zero"
        );
        assert_eq!(loaded[1].projected_reasoning_tokens, None);

        let rec = repo.reconcile_session(&session).await.unwrap();
        assert_eq!(rec.total.projected_input_tokens, 65_900);
        assert_eq!(rec.total.projected_reasoning_tokens, 17_100);
        assert_eq!(rec.total.rows_without_projected_usage, 1);
        assert_eq!(rec.total.input_tokens, 66_282);
        assert_eq!(rec.total.cached_input_tokens, 51_000);
        assert_eq!(rec.total.uncached_input_tokens(), 66_282 - 51_000);
        assert_eq!(
            rec.total.projected_input_tokens - rec.total.uncached_input_tokens(),
            65_900 - (66_282 - 51_000),
            "projected minus uncached is the number the cost question needs"
        );

        // A provider that reports more cache hits than prompt tokens cannot
        // produce a negative uncached figure.
        let impossible = SessionUsageTotals {
            input_tokens: 10,
            cached_input_tokens: 50,
            ..Default::default()
        };
        assert_eq!(impossible.uncached_input_tokens(), 0);
    }

    /// T3/T4. A sub-agent's call is attributable to the agent that made it.
    /// Before this, a reviewer's spend reached the screen and nothing else.
    #[tokio::test]
    async fn a_child_request_is_attributed_to_its_agent() {
        let (db, session) = seeded().await;
        let repo = ModelRequestRepository::new(&db);
        repo.insert(&record("parent-1", &session)).await.unwrap();
        let mut child = record("reviewer-1", &session);
        child.agent_id = Some("reviewer-6d8ab312".to_string());
        repo.insert(&child).await.unwrap();

        let rec = repo.reconcile_session(&session).await.unwrap();
        assert_eq!(rec.root.requests, 1);
        assert_eq!(rec.by_agent.len(), 1);
        assert_eq!(rec.by_agent[0].0, "reviewer-6d8ab312");
        assert_eq!(rec.by_agent[0].1.requests, 1);
        assert_eq!(rec.by_agent[0].1.input_tokens, 1_000);
    }

    /// T5/T9. The total is the root plus every agent, counted once each.
    #[tokio::test]
    async fn reconciliation_sums_root_and_children_without_double_counting() {
        let (db, session) = seeded().await;
        let repo = ModelRequestRepository::new(&db);
        repo.insert(&record("p-1", &session)).await.unwrap();
        for (n, agent) in [
            ("c-1", "reviewer-a"),
            ("c-2", "reviewer-a"),
            ("c-3", "explorer-b"),
        ] {
            let mut r = record(n, &session);
            r.agent_id = Some(agent.to_string());
            repo.insert(&r).await.unwrap();
        }

        let rec = repo.reconcile_session(&session).await.unwrap();
        assert_eq!(rec.total.requests, 4, "four rows, counted once each");
        assert_eq!(rec.total.input_tokens, 4_000);
        assert_eq!(rec.total.cached_input_tokens, 3_600);
        assert_eq!(
            rec.total.reasoning_tokens,
            4 * 80,
            "each logical call contributes its reasoning share exactly once"
        );
        assert_eq!(rec.total.cost_usd_micros, 4 * 1_234);
        assert_eq!(rec.root.requests, 1);
        let child_requests: u64 = rec.by_agent.iter().map(|(_, t)| t.requests).sum();
        assert_eq!(rec.root.requests + child_requests, rec.total.requests);
        assert_eq!(rec.by_agent.len(), 2, "two distinct agents");
        assert!(rec.total.is_complete());
    }

    /// A file written by the previous release upgrades in place. The fixture
    /// is the shape a Phase C formal run left behind: rows with no cached
    /// usage, no cost and no agent attribution. Upgrading must not ask the
    /// user to delete `~/.leveler`, and must not invent facts for rows nobody
    /// measured.
    #[tokio::test]
    async fn a_pre_0022_database_upgrades_in_place_and_keeps_its_rows() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sessions.db");

        let session_id = {
            let db = Database::connect(&path).await.unwrap();
            let session = SessionRecord::new(
                "/repo",
                "goal",
                "deepseek/deepseek-v4-flash",
                leveler_core::now(),
            );
            SessionRepository::new(&db).create(&session).await.unwrap();
            let id = SessionId::new(session.id);
            sqlx::query(
                "INSERT INTO model_requests \
                 (id, session_id, provider, model, input_tokens, output_tokens, \
                  retry_count, created_at, kind) \
                 VALUES ('legacy-1', ?1, 'deepseek', 'deepseek-v4-flash', 6392866, 67547, \
                         0, ?2, 'round')",
            )
            .bind(id.as_str())
            .bind(leveler_core::now().to_rfc3339())
            .execute(db.pool())
            .await
            .unwrap();
            id
        };

        // Reopen the same file: the ordinary "upgrade and start again" path.
        let db = Database::connect(&path).await.unwrap();
        let repo = ModelRequestRepository::new(&db);
        let rows = repo.load_for_session(&session_id).await.unwrap();
        assert_eq!(rows.len(), 1, "the old row is still readable");
        assert_eq!(rows[0].input_tokens, 6_392_866);
        assert_eq!(
            rows[0].cached_input_tokens, None,
            "a row from before the column reads as unrecorded, not as a cache miss"
        );
        assert_eq!(
            rows[0].reasoning_tokens, None,
            "and not as a provider that measured zero reasoning"
        );
        assert_eq!(rows[0].cost_usd_micros, None, "and not as a free call");
        assert_eq!(rows[0].agent_id, None);

        let rec = repo.reconcile_session(&session_id).await.unwrap();
        assert_eq!(rec.total.input_tokens, 6_392_866);
        assert_eq!(rec.total.rows_without_cached_usage, 1);
        assert_eq!(rec.total.rows_without_reasoning_usage, 1);
        assert_eq!(rec.total.rows_without_cost, 1);
        assert!(
            !rec.total.is_complete(),
            "a total resting on an unrecorded row reports itself incomplete"
        );
    }

    /// T6/T7. A row from before the column existed reads as UNRECORDED, not
    /// as a call that hit no cache and cost nothing. Reconciliation says so
    /// rather than reporting a clean total it cannot support.
    #[tokio::test]
    async fn a_pre_migration_row_is_unknown_usage_not_zero_usage() {
        let (db, session) = seeded().await;
        sqlx::query(
            "INSERT INTO model_requests \
             (id, session_id, provider, model, input_tokens, output_tokens, created_at) \
             VALUES ('legacy', ?1, 'p', 'm', 500, 50, ?2)",
        )
        .bind(session.as_str())
        .bind(leveler_core::now().to_rfc3339())
        .execute(db.pool())
        .await
        .unwrap();

        let repo = ModelRequestRepository::new(&db);
        let loaded = repo.load_for_session(&session).await.unwrap();
        assert_eq!(loaded[0].cached_input_tokens, None, "unknown, not zero");
        assert_eq!(loaded[0].reasoning_tokens, None, "unknown, not zero");
        assert_eq!(loaded[0].cost_usd_micros, None);
        assert_eq!(loaded[0].agent_id, None);

        let rec = repo.reconcile_session(&session).await.unwrap();
        assert_eq!(
            rec.total.input_tokens, 500,
            "tokens it did record still count"
        );
        assert_eq!(rec.total.cached_input_tokens, 0);
        assert_eq!(rec.total.rows_without_cached_usage, 1);
        assert_eq!(rec.total.rows_without_reasoning_usage, 1);
        assert_eq!(rec.total.rows_without_cost, 1);
        assert!(
            !rec.total.is_complete(),
            "a total standing on an unrecorded row must not claim to be whole"
        );
    }

    use crate::{SessionRecord, SessionRepository};

    #[tokio::test]
    async fn finish_reason_and_usage_are_persisted() {
        let db = Database::connect_in_memory().await.unwrap();
        let session = SessionRecord::new("/r", "g", "provider/model", leveler_core::now());
        SessionRepository::new(&db).create(&session).await.unwrap();
        let session_id = SessionId::new(session.id);
        let record = ModelRequestRecord {
            budget_scope: None,
            estimated_tokens: None,
            id: "req-1".to_string(),
            provider_request_id: None,
            session_id: session_id.clone(),
            provider: "provider".to_string(),
            model: "model".to_string(),
            input_tokens: 100,
            output_tokens: 20,
            finish_reason: Some("length".to_string()),
            error_kind: None,
            latency_ms: Some(42),
            attempt_ms: Some(40),
            connect_ms: Some(5),
            ttft_ms: Some(8),
            max_event_gap_ms: Some(3),
            retry_count: 1,
            kind: ModelCallKind::Round,
            cached_input_tokens: None,
            projected_input_tokens: None,
            projected_reasoning_tokens: None,
            cost_usd_micros: None,
            agent_id: None,
            created_at: leveler_core::now(),
            reasoning_effort: Some("high".to_string()),
            reasoning_tokens: Some(12),
        };

        let repo = ModelRequestRepository::new(&db);
        repo.insert(&record).await.unwrap();
        let loaded = repo.load_for_session(&session_id).await.unwrap();

        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].finish_reason.as_deref(), Some("length"));
        assert_eq!(
            loaded[0].reasoning_effort.as_deref(),
            Some("high"),
            "the effort a call asked for is what the row says"
        );
        assert_eq!(loaded[0].output_tokens, 20);
        assert_eq!(loaded[0].retry_count, 1);
        assert_eq!(
            loaded[0].reasoning_tokens,
            Some(12),
            "a reasoning count survives alongside the effort metadata"
        );
    }

    /// Existing aggregate rows remain readable with their original retry
    /// counts. New attempt writers emit a separate row for each attempt.
    #[tokio::test]
    async fn legacy_aggregate_call_kinds_and_retry_counts_round_trip() {
        let db = Database::connect_in_memory().await.unwrap();
        let session = SessionRecord::new("/r", "g", "provider/model", leveler_core::now());
        SessionRepository::new(&db).create(&session).await.unwrap();
        let session_id = SessionId::new(session.id);
        let repo = ModelRequestRepository::new(&db);
        for (id, kind, retries) in [
            ("r-1", ModelCallKind::Round, 2u32),
            ("c-1", ModelCallKind::Compaction, 0),
            ("a-1", ModelCallKind::Advisory, 1),
        ] {
            repo.insert(&ModelRequestRecord {
                budget_scope: None,
                estimated_tokens: None,
                id: id.to_string(),
                provider_request_id: None,
                session_id: session_id.clone(),
                provider: "provider".to_string(),
                model: "model".to_string(),
                input_tokens: 10,
                output_tokens: 2,
                finish_reason: Some("stop".to_string()),
                error_kind: None,
                latency_ms: Some(1),
                attempt_ms: None,
                connect_ms: None,
                ttft_ms: None,
                max_event_gap_ms: None,
                retry_count: retries,
                kind,
                cached_input_tokens: None,
                projected_input_tokens: None,
                projected_reasoning_tokens: None,
                cost_usd_micros: None,
                agent_id: None,
                created_at: leveler_core::now(),
                reasoning_effort: None,
                reasoning_tokens: None,
            })
            .await
            .unwrap();
        }

        let loaded = repo.load_for_session(&session_id).await.unwrap();
        assert_eq!(
            loaded.iter().map(|r| r.kind).collect::<Vec<_>>(),
            vec![
                ModelCallKind::Round,
                ModelCallKind::Compaction,
                ModelCallKind::Advisory
            ]
        );
        let logical = loaded.len();
        let physical: u32 = loaded.iter().map(|r| 1 + r.retry_count).sum();
        assert_eq!((logical, physical), (3, 6));
    }

    /// A provider that reports the same request id twice produces two rows.
    /// It used to produce a UNIQUE violation, which the writer returned as a
    /// persistence error and which ended the turn — over a diagnostics row.
    #[tokio::test]
    async fn a_repeated_provider_request_id_is_two_rows_not_a_failure() {
        let db = Database::connect_in_memory().await.unwrap();
        let session = SessionRecord::new("/r", "g", "provider/model", leveler_core::now());
        SessionRepository::new(&db).create(&session).await.unwrap();
        let session_id = SessionId::new(session.id);
        let repo = ModelRequestRepository::new(&db);
        for row in ["row-1", "row-2"] {
            repo.insert(&ModelRequestRecord {
                budget_scope: None,
                estimated_tokens: None,
                id: row.to_string(),
                provider_request_id: Some("the-same-upstream-id".to_string()),
                session_id: session_id.clone(),
                provider: "provider".to_string(),
                model: "model".to_string(),
                input_tokens: 1,
                output_tokens: 1,
                finish_reason: Some("stop".to_string()),
                error_kind: None,
                latency_ms: Some(1),
                attempt_ms: None,
                connect_ms: None,
                ttft_ms: None,
                max_event_gap_ms: None,
                retry_count: 0,
                kind: ModelCallKind::Advisory,
                cached_input_tokens: None,
                projected_input_tokens: None,
                projected_reasoning_tokens: None,
                cost_usd_micros: None,
                agent_id: None,
                created_at: leveler_core::now(),
                reasoning_effort: None,
                reasoning_tokens: None,
            })
            .await
            .expect("a repeated provider id is not a persistence failure");
        }

        let loaded = repo.load_for_session(&session_id).await.unwrap();
        assert_eq!(loaded.len(), 2, "two calls, two rows");
        assert!(
            loaded
                .iter()
                .all(|r| r.provider_request_id.as_deref() == Some("the-same-upstream-id")),
            "and the provider's id survives as the diagnostic it is"
        );
    }

    /// A row written before the column existed is a main-loop round, because
    /// that is all the old writer could produce. The migration's backfill says
    /// so, and reading must agree with it.
    #[tokio::test]
    async fn a_pre_migration_row_reads_as_a_round() {
        let db = Database::connect_in_memory().await.unwrap();
        let session = SessionRecord::new("/r", "g", "provider/model", leveler_core::now());
        SessionRepository::new(&db).create(&session).await.unwrap();
        let session_id = SessionId::new(session.id);
        sqlx::query(
            "INSERT INTO model_requests \
             (id, session_id, provider, model, input_tokens, output_tokens, created_at) \
             VALUES ('legacy', ?1, 'p', 'm', 1, 1, ?2)",
        )
        .bind(session_id.as_str())
        .bind(leveler_core::now().to_rfc3339())
        .execute(db.pool())
        .await
        .unwrap();

        let loaded = ModelRequestRepository::new(&db)
            .load_for_session(&session_id)
            .await
            .unwrap();
        assert_eq!(loaded[0].kind, ModelCallKind::Round);
    }
}
