//! Session repository with create/list/get/delete operations so the CLI's
//! `sessions` commands work against a real table; the orchestrator fills in the
//! rest in later phases.

use std::str::FromStr;

use serde::{Deserialize, Serialize};

use leveler_core::{SessionId, Timestamp};
use leveler_lifecycle::{AgentState, SessionStatus, TaskOutcome, UnknownVariant};

use crate::database::{Database, StorageError};

/// A replacement of one user-selected field, never a stale full-row rewrite.
#[derive(Debug, Clone)]
pub enum SessionEdit {
    /// Session display title.
    Title(String),
    /// Configured provider/model reference.
    Model(String),
    /// Permission profile wire value.
    Permission(String),
    /// Thinking override; None restores inheritance.
    Thinking(Option<String>),
    /// Collaboration mode wire value.
    Collaboration(String),
}

/// Atomic metadata replacement outcome.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SessionEditResult {
    /// Mutation committed at this sequence.
    Applied(i64),
    /// No mutation; current authoritative sequence.
    Conflict(i64),
}

/// Settings and their event-log version observed in one SQLite read snapshot.
pub struct SessionSettingsSnapshot {
    /// Persisted session metadata.
    pub session: SessionRecord,
    /// Permission profile wire value.
    pub mode: String,
    /// Persisted sandbox setting.
    pub sandbox: bool,
    /// Legacy execution kind.
    pub kind: String,
    /// Persisted thinking override.
    pub thinking: Option<String>,
    /// Latest event sequence in the same read transaction.
    pub sequence: Option<i64>,
}

impl From<UnknownVariant> for StorageError {
    fn from(err: UnknownVariant) -> Self {
        StorageError::InvalidData(err.to_string())
    }
}

/// A persisted session row. Status/state/outcome are typed lifecycle vocabulary,
/// not free strings — the repository encodes them to text on write and decodes
/// on read, raising `InvalidData` on any unknown persisted value.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionRecord {
    /// Primary key, generated by the caller.
    pub id: String,
    /// User-selected primary workspace; None grants no directory access.
    /// Existing sessions retain their original absolute workspace path.
    pub repository: Option<String>,
    /// The user's original request, stored verbatim.
    pub goal: String,
    /// Lifecycle status. Round-trips through a wire string; an unrecognized
    /// persisted value fails the read rather than defaulting.
    pub status: SessionStatus,
    /// Model reference (`provider/model`) the session was started with.
    pub model: String,
    /// Agent state, with the same strict decoding as [`Self::status`].
    pub state: AgentState,
    /// Creation time as RFC 3339 text. Unlike other tables this stays a
    /// `String` end to end — the repository neither parses nor validates it,
    /// so the format is whatever the caller wrote.
    pub created_at: String,
    /// Last-modified time, with the same caveat as [`Self::created_at`].
    pub updated_at: String,
    /// Collaboration mode wire value: chat | plan | goal.
    pub collaboration: String,
    /// Legacy database compatibility only; no runtime policy meaning.
    pub work_profile: String,
}

/// The raw text row as stored; decoded into a typed [`SessionRecord`].
#[derive(sqlx::FromRow)]
pub(crate) struct SessionRow {
    id: String,
    repository: Option<String>,
    goal: String,
    status: String,
    model: String,
    state: String,
    created_at: String,
    updated_at: String,
    collaboration: String,
    work_profile: String,
}

impl SessionRow {
    pub(crate) fn decode(self) -> Result<SessionRecord, StorageError> {
        Ok(SessionRecord {
            id: self.id,
            repository: self.repository,
            goal: self.goal,
            status: SessionStatus::from_str(&self.status)?,
            model: self.model,
            state: AgentState::from_str(&self.state)?,
            created_at: self.created_at,
            updated_at: self.updated_at,
            collaboration: self.collaboration,
            work_profile: self.work_profile,
        })
    }
}

/// Read/write access to the `sessions` table.
pub struct SessionRepository<'a> {
    db: &'a Database,
}

impl<'a> SessionRepository<'a> {
    /// Borrow `db` for the lifetime of this repository handle.
    pub fn new(db: &'a Database) -> Self {
        Self { db }
    }

    /// Insert a new session.
    #[allow(clippy::too_many_arguments)]
    pub async fn create(&self, record: &SessionRecord) -> Result<(), StorageError> {
        // Explicit mode/sandbox/kind: migration 0003 DEFAULT is still the obsolete
        // `workspace_write` string; never depend on that for new rows.
        sqlx::query(
            "INSERT INTO sessions \
             (id, repository, goal, status, model, state, created_at, updated_at, \
              collaboration, work_profile, mode, sandbox, kind) \
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, 'assisted', 0, 'direct')",
        )
        .bind(&record.id)
        .bind(&record.repository)
        .bind(&record.goal)
        .bind(record.status.as_str())
        .bind(&record.model)
        .bind(record.state.as_str())
        .bind(&record.created_at)
        .bind(&record.updated_at)
        .bind(&record.collaboration)
        .bind("single")
        .execute(self.db.pool())
        .await?;
        Ok(())
    }

    /// List sessions, most recent first. Archived sessions are excluded —
    /// archiving is exactly "hide from the default list".
    pub async fn list(&self) -> Result<Vec<SessionRecord>, StorageError> {
        let rows = sqlx::query_as::<_, SessionRow>(
            "SELECT id, repository, goal, status, model, state, created_at, updated_at, \
             collaboration, work_profile \
             FROM sessions WHERE archived_at IS NULL ORDER BY created_at DESC",
        )
        .fetch_all(self.db.pool())
        .await?;
        rows.into_iter().map(SessionRow::decode).collect()
    }

    /// Archive (`Some(now)`) or restore (`None`) a session. Archived sessions
    /// keep their full transcript; they only leave the default list.
    pub async fn set_archived(
        &self,
        id: &SessionId,
        archived_at: Option<Timestamp>,
    ) -> Result<(), StorageError> {
        sqlx::query("UPDATE sessions SET archived_at = ?2 WHERE id = ?1")
            .bind(id.as_str())
            .bind(archived_at.map(|t| t.to_rfc3339()))
            .execute(self.db.pool())
            .await?;
        Ok(())
    }

    /// Persist whether this session may admit turns to memory extraction.
    ///
    /// Called at the start of every turn from the project's `memory.enabled`
    /// switch, so a config change is reflected before the turn row is inserted
    /// and the admission trigger reads it. `updated_at` is deliberately not
    /// touched: this is a policy snapshot, not session activity.
    pub async fn set_memory_enabled(
        &self,
        id: &SessionId,
        enabled: bool,
    ) -> Result<(), StorageError> {
        sqlx::query("UPDATE sessions SET memory_enabled = ?2 WHERE id = ?1")
            .bind(id.as_str())
            .bind(i64::from(enabled))
            .execute(self.db.pool())
            .await?;
        Ok(())
    }

    /// Fetch one session by id.
    pub async fn get(&self, id: &SessionId) -> Result<Option<SessionRecord>, StorageError> {
        let row = sqlx::query_as::<_, SessionRow>(
            "SELECT id, repository, goal, status, model, state, created_at, updated_at, \
             collaboration, work_profile \
             FROM sessions WHERE id = ?1",
        )
        .bind(id.as_str())
        .fetch_optional(self.db.pool())
        .await?;
        row.map(SessionRow::decode).transpose()
    }

    /// Compare, replace the selected field, and advance the existing log in
    /// one writer transaction. A conflict changes neither the row nor the log.
    pub async fn edit_at_version(
        &self,
        id: &SessionId,
        expected: i64,
        edit: &SessionEdit,
        now: Timestamp,
    ) -> Result<SessionEditResult, StorageError> {
        self.edit_metadata(id, Some(expected), edit, now).await
    }

    /// A goal/plan submission changes only its collaboration axis, preserving
    /// independently selected model, permission, and thinking fields.
    pub async fn set_turn_collaboration(
        &self,
        id: &SessionId,
        collaboration: &str,
        now: Timestamp,
    ) -> Result<(), StorageError> {
        self.edit_metadata(
            id,
            None,
            &SessionEdit::Collaboration(collaboration.into()),
            now,
        )
        .await?;
        Ok(())
    }

    async fn edit_metadata(
        &self,
        id: &SessionId,
        expected: Option<i64>,
        edit: &SessionEdit,
        now: Timestamp,
    ) -> Result<SessionEditResult, StorageError> {
        let mut tx = self.db.pool().begin_with("BEGIN IMMEDIATE").await?;
        let sequence: i64 = sqlx::query_scalar(
            "SELECT COALESCE(MAX(sequence), 0) FROM events WHERE session_id = ?1",
        )
        .bind(id.as_str())
        .fetch_one(&mut *tx)
        .await?;
        if expected.is_some_and(|expected| sequence != expected) {
            tx.rollback().await?;
            return Ok(SessionEditResult::Conflict(sequence));
        }
        let (sql, value, field) = match edit {
            SessionEdit::Title(value) => (
                "UPDATE sessions SET goal = ?2, updated_at = ?3 WHERE id = ?1",
                Some(value.as_str()),
                "goal",
            ),
            SessionEdit::Model(value) => (
                "UPDATE sessions SET model = ?2, updated_at = ?3 WHERE id = ?1",
                Some(value.as_str()),
                "model",
            ),
            SessionEdit::Permission(value) => (
                "UPDATE sessions SET mode = ?2, updated_at = ?3 WHERE id = ?1",
                Some(value.as_str()),
                "mode",
            ),
            SessionEdit::Thinking(value) => (
                "UPDATE sessions SET thinking = ?2, updated_at = ?3 WHERE id = ?1",
                value.as_deref(),
                "thinking",
            ),
            SessionEdit::Collaboration(value) => (
                "UPDATE sessions SET collaboration = ?2, updated_at = ?3 WHERE id = ?1",
                Some(value.as_str()),
                "collaboration",
            ),
        };
        let changed = sqlx::query(sql)
            .bind(id.as_str())
            .bind(value)
            .bind(now.to_rfc3339())
            .execute(&mut *tx)
            .await?;
        if changed.rows_affected() != 1 {
            return Err(StorageError::InvalidData(format!(
                "session {id} not found for metadata edit"
            )));
        }
        let payload =
            serde_json::json!({"type": "session_metadata_changed", "payload": {"field": field}})
                .to_string();
        sqlx::query("INSERT INTO events (id, session_id, sequence, type, payload, created_at, schema_version) VALUES (?1, ?2, ?3, 'session_metadata_changed', ?4, ?5, ?6)")
            .bind(leveler_core::EventId::generate().as_str()).bind(id.as_str()).bind(sequence + 1)
            .bind(payload).bind(now.to_rfc3339()).bind(crate::event_repo::EVENT_SCHEMA_VERSION)
            .execute(&mut *tx).await?;
        tx.commit().await?;
        Ok(SessionEditResult::Applied(sequence + 1))
    }

    /// Read metadata and its log version from one SQLite snapshot.
    pub async fn settings_snapshot(
        &self,
        id: &SessionId,
    ) -> Result<Option<SessionSettingsSnapshot>, StorageError> {
        let mut tx = self.db.pool().begin().await?;
        let row: Option<SessionRow> = sqlx::query_as("SELECT id, repository, goal, status, model, state, created_at, updated_at, collaboration, work_profile FROM sessions WHERE id = ?1")
            .bind(id.as_str()).fetch_optional(&mut *tx).await?;
        let Some(row) = row else {
            return Ok(None);
        };
        let (mode, sandbox, kind, thinking): (String, bool, String, Option<String>) =
            sqlx::query_as("SELECT mode, sandbox, kind, thinking FROM sessions WHERE id = ?1")
                .bind(id.as_str())
                .fetch_one(&mut *tx)
                .await?;
        let sequence = sqlx::query_scalar("SELECT MAX(sequence) FROM events WHERE session_id = ?1")
            .bind(id.as_str())
            .fetch_one(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(Some(SessionSettingsSnapshot {
            session: row.decode()?,
            mode,
            sandbox,
            kind,
            thinking,
            sequence,
        }))
    }

    /// Persist product axes (collaboration × work profile).
    pub async fn set_axes(
        &self,
        id: &SessionId,
        collaboration: &str,
        _legacy_work_profile: &str,
        now: Timestamp,
    ) -> Result<(), StorageError> {
        sqlx::query(
            "UPDATE sessions SET collaboration = ?2, work_profile = ?3, updated_at = ?4 \
             WHERE id = ?1",
        )
        .bind(id.as_str())
        .bind(collaboration)
        .bind("single")
        .bind(now.to_rfc3339())
        .execute(self.db.pool())
        .await?;
        Ok(())
    }

    /// Read collaboration and the retained legacy column for a session.
    pub async fn axes(&self, id: &SessionId) -> Result<Option<(String, String)>, StorageError> {
        let row: Option<(String, String)> =
            sqlx::query_as("SELECT collaboration, work_profile FROM sessions WHERE id = ?1")
                .bind(id.as_str())
                .fetch_optional(self.db.pool())
                .await?;
        Ok(row)
    }

    /// Update a session's operational status and agent state, bumping
    /// `updated_at`.
    pub async fn update_status(
        &self,
        id: &SessionId,
        status: SessionStatus,
        state: AgentState,
        now: Timestamp,
    ) -> Result<(), StorageError> {
        sqlx::query("UPDATE sessions SET status = ?2, state = ?3, updated_at = ?4 WHERE id = ?1")
            .bind(id.as_str())
            .bind(status.as_str())
            .bind(state.as_str())
            .bind(now.to_rfc3339())
            .execute(self.db.pool())
            .await?;
        Ok(())
    }

    /// Overwrite the goal/title text. Used to name a placeholder interactive
    /// session after its first real message; does not bump `updated_at` (the
    /// message's own turn does that).
    pub async fn update_goal(&self, id: &SessionId, goal: &str) -> Result<(), StorageError> {
        sqlx::query("UPDATE sessions SET goal = ?2 WHERE id = ?1")
            .bind(id.as_str())
            .bind(goal)
            .execute(self.db.pool())
            .await?;
        Ok(())
    }

    /// Persist the model selected for subsequent turns in this session.
    pub async fn update_model(
        &self,
        id: &SessionId,
        model: &str,
        now: Timestamp,
    ) -> Result<(), StorageError> {
        sqlx::query("UPDATE sessions SET model = ?2, updated_at = ?3 WHERE id = ?1")
            .bind(id.as_str())
            .bind(model)
            .bind(now.to_rfc3339())
            .execute(self.db.pool())
            .await?;
        Ok(())
    }

    /// Persist how the session executes (0003 columns). Set at creation time
    /// so resume never has to guess mode/sandbox/kind.
    pub async fn set_execution(
        &self,
        id: &SessionId,
        mode: &str,
        sandbox: bool,
        kind: &str,
        now: Timestamp,
    ) -> Result<(), StorageError> {
        sqlx::query(
            "UPDATE sessions SET mode = ?2, sandbox = ?3, kind = ?4, updated_at = ?5 \
             WHERE id = ?1",
        )
        .bind(id.as_str())
        .bind(mode)
        .bind(sandbox)
        .bind(kind)
        .bind(now.to_rfc3339())
        .execute(self.db.pool())
        .await?;
        Ok(())
    }

    /// Persist this session's Thinking Level override, or clear it.
    ///
    /// `None` clears it: the session inherits the configured level again. An
    /// explicit `auto` is stored as the word `auto`, because a session that
    /// asked for "no override" must not come back as one that never chose.
    pub async fn set_thinking(
        &self,
        id: &SessionId,
        thinking: Option<&str>,
        now: Timestamp,
    ) -> Result<(), StorageError> {
        sqlx::query("UPDATE sessions SET thinking = ?2, updated_at = ?3 WHERE id = ?1")
            .bind(id.as_str())
            .bind(thinking)
            .bind(now.to_rfc3339())
            .execute(self.db.pool())
            .await?;
        Ok(())
    }

    /// Read back this session's Thinking Level override, as stored.
    pub async fn thinking(&self, id: &SessionId) -> Result<Option<String>, StorageError> {
        let row: Option<Option<String>> =
            sqlx::query_scalar("SELECT thinking FROM sessions WHERE id = ?1")
                .bind(id.as_str())
                .fetch_optional(self.db.pool())
                .await?;
        Ok(row.flatten())
    }

    /// Read back `(mode, sandbox, kind, outcome)`. `kind` stays a string
    /// (owned by the engine's `ExecutionKind`, parsed there); the terminal
    /// `outcome` is decoded to the typed lifecycle vocabulary.
    pub async fn execution(
        &self,
        id: &SessionId,
    ) -> Result<Option<(String, bool, String, Option<TaskOutcome>)>, StorageError> {
        let row: Option<(String, bool, String, Option<String>)> =
            sqlx::query_as("SELECT mode, sandbox, kind, outcome FROM sessions WHERE id = ?1")
                .bind(id.as_str())
                .fetch_optional(self.db.pool())
                .await?;
        match row {
            None => Ok(None),
            Some((mode, sandbox, kind, outcome)) => {
                let outcome = outcome.map(|s| TaskOutcome::from_str(&s)).transpose()?;
                Ok(Some((mode, sandbox, kind, outcome)))
            }
        }
    }

    /// Persist the terminal outcome.
    pub async fn set_outcome(
        &self,
        id: &SessionId,
        outcome: TaskOutcome,
        now: Timestamp,
    ) -> Result<(), StorageError> {
        sqlx::query("UPDATE sessions SET outcome = ?2, updated_at = ?3 WHERE id = ?1")
            .bind(id.as_str())
            .bind(outcome.as_str())
            .bind(now.to_rfc3339())
            .execute(self.db.pool())
            .await?;
        Ok(())
    }

    /// Delete a session and all its cascaded rows. Returns whether a row matched.
    pub async fn delete(&self, id: &SessionId) -> Result<bool, StorageError> {
        let result = sqlx::query("DELETE FROM sessions WHERE id = ?1")
            .bind(id.as_str())
            .execute(self.db.pool())
            .await?;
        Ok(result.rows_affected() > 0)
    }
}

impl SessionRecord {
    /// Build a fresh record from the essentials, stamping timestamps.
    pub fn new(
        repository: impl Into<String>,
        goal: impl Into<String>,
        model: impl Into<String>,
        now: Timestamp,
    ) -> Self {
        Self::new_with_workspace(Some(repository.into()), goal, model, now)
    }

    fn new_with_workspace(
        repository: Option<String>,
        goal: impl Into<String>,
        model: impl Into<String>,
        now: Timestamp,
    ) -> Self {
        let ts = now.to_rfc3339();
        Self {
            id: SessionId::generate().into_inner(),
            repository,
            goal: goal.into(),
            status: SessionStatus::Created,
            model: model.into(),
            state: AgentState::Understand,
            created_at: ts.clone(),
            updated_at: ts,
            collaboration: "goal".into(),
            work_profile: "single".into(),
        }
    }

    /// Create a session with no user-authorized primary workspace.
    pub fn without_workspace(
        goal: impl Into<String>,
        model: impl Into<String>,
        now: Timestamp,
    ) -> Self {
        Self::new_with_workspace(None, goal, model, now)
    }

    /// Set collaboration before insert. The legacy profile argument is ignored.
    pub fn with_axes(mut self, collaboration: &str, _legacy_work_profile: &str) -> Self {
        self.collaboration = collaboration.to_string();
        self.work_profile = "single".to_string();
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn concurrent_replacements_compare_and_advance_the_log_atomically() {
        let tmp = tempfile::tempdir().unwrap();
        let db = Database::connect(&tmp.path().join("cas.db")).await.unwrap();
        let record = SessionRecord::without_workspace("original", "m", leveler_core::now());
        let id = SessionId::new(record.id.clone());
        let repo = SessionRepository::new(&db);
        repo.create(&record).await.unwrap();
        let left = SessionEdit::Title("left".into());
        let right = SessionEdit::Title("right".into());
        let (left, right) = tokio::join!(
            repo.edit_at_version(&id, 0, &left, leveler_core::now()),
            repo.edit_at_version(&id, 0, &right, leveler_core::now())
        );
        let results = [left.unwrap(), right.unwrap()];
        assert_eq!(
            results
                .iter()
                .filter(|result| **result == SessionEditResult::Applied(1))
                .count(),
            1
        );
        assert_eq!(
            results
                .iter()
                .filter(|result| **result == SessionEditResult::Conflict(1))
                .count(),
            1
        );
        let snapshot = repo.settings_snapshot(&id).await.unwrap().unwrap();
        assert_eq!(snapshot.sequence, Some(1));
        assert_eq!(
            snapshot.session.goal,
            if results[0] == SessionEditResult::Applied(1) {
                "left"
            } else {
                "right"
            }
        );
        // The loser cannot change another field or append a phantom version.
        assert_eq!(
            repo.edit_at_version(
                &id,
                0,
                &SessionEdit::Model("other".into()),
                leveler_core::now()
            )
            .await
            .unwrap(),
            SessionEditResult::Conflict(1)
        );
        let snapshot = repo.settings_snapshot(&id).await.unwrap().unwrap();
        assert_eq!(snapshot.sequence, Some(1));
        assert_eq!(snapshot.session.model, "m");
        assert_eq!(
            repo.edit_at_version(
                &id,
                1,
                &SessionEdit::Model("selected".into()),
                leveler_core::now()
            )
            .await
            .unwrap(),
            SessionEditResult::Applied(2)
        );
        assert_eq!(
            repo.edit_at_version(
                &id,
                2,
                &SessionEdit::Permission("full_access".into()),
                leveler_core::now()
            )
            .await
            .unwrap(),
            SessionEditResult::Applied(3)
        );
        repo.set_turn_collaboration(&id, "goal", leveler_core::now())
            .await
            .unwrap();
        let merged = repo.settings_snapshot(&id).await.unwrap().unwrap();
        assert_eq!(merged.session.model, "selected");
        assert_eq!(merged.mode, "full_access");
        assert_eq!(merged.session.collaboration, "goal");
        assert_eq!(merged.sequence, Some(4));
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn settings_and_log_version_share_one_read_snapshot() {
        let tmp = tempfile::tempdir().unwrap();
        let db = Database::connect(&tmp.path().join("snapshot.db"))
            .await
            .unwrap();
        let record = SessionRecord::without_workspace("title-0", "m", leveler_core::now());
        let id = SessionId::new(record.id.clone());
        let repo = SessionRepository::new(&db);
        repo.create(&record).await.unwrap();
        let writer = async {
            for version in 0..40 {
                assert_eq!(
                    repo.edit_at_version(
                        &id,
                        version,
                        &SessionEdit::Title(format!("title-{}", version + 1)),
                        leveler_core::now()
                    )
                    .await
                    .unwrap(),
                    SessionEditResult::Applied(version + 1)
                );
            }
        };
        let reader = async {
            for _ in 0..80 {
                let snapshot = repo.settings_snapshot(&id).await.unwrap().unwrap();
                assert_eq!(
                    snapshot.session.goal,
                    format!("title-{}", snapshot.sequence.unwrap_or(0))
                );
            }
        };
        tokio::join!(writer, reader);
        assert_eq!(
            repo.settings_snapshot(&id).await.unwrap().unwrap().sequence,
            Some(40)
        );
    }

    #[tokio::test]
    async fn no_workspace_roundtrips_and_deletes_without_becoming_a_path() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("sessions.db");
        let db = Database::connect(&path).await.unwrap();
        assert_eq!(
            sqlx::query_scalar::<_, i64>("PRAGMA foreign_keys")
                .fetch_one(db.pool())
                .await
                .unwrap(),
            1,
            "runtime pool must enforce FKs after private migration connection closes"
        );
        let row = SessionRecord::without_workspace("translate", "m", leveler_core::now());
        let id = SessionId::new(row.id.clone());
        SessionRepository::new(&db).create(&row).await.unwrap();
        assert_eq!(
            SessionRepository::new(&db)
                .get(&id)
                .await
                .unwrap()
                .unwrap()
                .repository,
            None
        );
        drop(db);
        let db = Database::connect(&path).await.unwrap();
        let repo = SessionRepository::new(&db);
        assert_eq!(repo.list().await.unwrap()[0].repository, None);
        assert!(repo.delete(&id).await.unwrap());
        assert!(repo.get(&id).await.unwrap().is_none());
    }

    #[tokio::test]
    async fn create_list_get_delete_roundtrip() {
        let db = Database::connect_in_memory().await.unwrap();
        let repo = SessionRepository::new(&db);
        assert!(repo.list().await.unwrap().is_empty());

        let record = SessionRecord::new(
            "/repo",
            "fix bug",
            "deepseek/deepseek-flash",
            leveler_core::now(),
        )
        .with_axes("goal", "balanced");
        repo.create(&record).await.unwrap();

        let listed = repo.list().await.unwrap();
        assert_eq!(listed.len(), 1);
        assert_eq!(listed[0].goal, "fix bug");

        let id = SessionId::new(record.id.clone());
        assert!(repo.get(&id).await.unwrap().is_some());
        assert!(repo.delete(&id).await.unwrap());
        assert!(repo.get(&id).await.unwrap().is_none());
    }

    #[tokio::test]
    async fn archived_sessions_leave_the_default_list_and_can_return() {
        let db = Database::connect_in_memory().await.unwrap();
        let repo = SessionRepository::new(&db);
        let record = SessionRecord::new("/repo", "整理", "m", leveler_core::now());
        repo.create(&record).await.unwrap();
        let id = SessionId::new(record.id.clone());

        repo.set_archived(&id, Some(leveler_core::now()))
            .await
            .unwrap();
        assert!(repo.list().await.unwrap().is_empty(), "archived is hidden");
        assert!(
            repo.get(&id).await.unwrap().is_some(),
            "archived is not deleted"
        );

        repo.set_archived(&id, None).await.unwrap();
        assert_eq!(repo.list().await.unwrap().len(), 1, "restore un-hides");
    }

    #[tokio::test]
    async fn update_goal_overwrites_title_without_touching_updated_at() {
        let db = Database::connect_in_memory().await.unwrap();
        let repo = SessionRepository::new(&db);
        let record = SessionRecord::new("/repo", "interactive session", "m", leveler_core::now());
        repo.create(&record).await.unwrap();
        let id = SessionId::new(record.id.clone());

        repo.update_goal(&id, "帮我修复登录超时").await.unwrap();
        let got = repo.get(&id).await.unwrap().unwrap();
        assert_eq!(got.goal, "帮我修复登录超时");
        assert_eq!(
            got.updated_at, record.updated_at,
            "retitle must not reorder the session list"
        );
    }

    #[tokio::test]
    async fn update_status_mutates_status_state_and_timestamp() {
        let db = Database::connect_in_memory().await.unwrap();
        let repo = SessionRepository::new(&db);

        let record = SessionRecord::new("/repo", "fix bug", "openai/gpt-4o", leveler_core::now());
        repo.create(&record).await.unwrap();

        let id = SessionId::new(record.id.clone());
        let updated = leveler_core::now();
        repo.update_status(&id, SessionStatus::Running, AgentState::Plan, updated)
            .await
            .unwrap();

        let fetched = repo.get(&id).await.unwrap().expect("record exists");
        assert_eq!(fetched.status, SessionStatus::Running);
        assert_eq!(fetched.state, AgentState::Plan);
        assert_eq!(fetched.updated_at, updated.to_rfc3339());
    }

    #[test]
    fn session_record_new_stamps_defaults() {
        let now = leveler_core::now();
        let record = SessionRecord::new("/repo", "goal", "model", now);
        assert_eq!(record.repository.as_deref(), Some("/repo"));
        assert_eq!(record.goal, "goal");
        assert_eq!(record.model, "model");
        assert_eq!(record.status, SessionStatus::Created);
        assert_eq!(record.state, AgentState::Understand);
        assert_eq!(record.created_at, now.to_rfc3339());
        assert_eq!(record.updated_at, now.to_rfc3339());
        assert!(!record.id.is_empty());
    }

    #[tokio::test]
    async fn known_string_values_decode_and_unknown_is_corruption() {
        let db = Database::connect_in_memory().await.unwrap();
        let repo = SessionRepository::new(&db);
        let record = SessionRecord::new("/repo", "goal", "m", leveler_core::now());
        repo.create(&record).await.unwrap();
        let id = SessionId::new(record.id);

        // A persisted status string still decodes to the typed enum.
        sqlx::query("UPDATE sessions SET status = 'completed', state = 'review' WHERE id = ?1")
            .bind(id.as_str())
            .execute(db.pool())
            .await
            .unwrap();
        let fetched = repo.get(&id).await.unwrap().unwrap();
        assert_eq!(fetched.status, SessionStatus::Completed);
        assert_eq!(fetched.state, AgentState::Review);

        // An unknown persisted value is a named corruption error, never a
        // silent default.
        sqlx::query("UPDATE sessions SET status = 'bogus' WHERE id = ?1")
            .bind(id.as_str())
            .execute(db.pool())
            .await
            .unwrap();
        let err = repo.get(&id).await.unwrap_err();
        assert!(
            matches!(&err, StorageError::InvalidData(m) if m.contains("bogus")),
            "unexpected error: {err}"
        );
    }

    #[tokio::test]
    async fn execution_config_and_outcome_roundtrip() {
        let db = Database::connect_in_memory().await.unwrap();
        let repo = SessionRepository::new(&db);
        let record = SessionRecord::new("/repo", "goal", "m", leveler_core::now());
        repo.create(&record).await.unwrap();
        let id = SessionId::new(record.id);

        // Fresh rows use the assisted profile (migration 0012/0013),
        // not the obsolete workspace_write string from 0003.
        let (mode, sandbox, kind, outcome) = repo.execution(&id).await.unwrap().unwrap();
        assert_eq!(
            (mode.as_str(), sandbox, kind.as_str(), outcome),
            ("assisted", false, "direct", None)
        );

        repo.set_execution(&id, "full_access", true, "orchestrate", leveler_core::now())
            .await
            .unwrap();
        repo.set_outcome(&id, TaskOutcome::Completed, leveler_core::now())
            .await
            .unwrap();

        let (mode, sandbox, kind, outcome) = repo.execution(&id).await.unwrap().unwrap();
        assert_eq!(mode, "full_access");
        assert!(sandbox);
        assert_eq!(kind, "orchestrate");
        assert_eq!(outcome, Some(TaskOutcome::Completed));
    }

    #[tokio::test]
    async fn product_axes_persist_and_default() {
        let db = Database::connect_in_memory().await.unwrap();
        let repo = SessionRepository::new(&db);
        let record = SessionRecord::new("/repo", "goal", "m", leveler_core::now())
            .with_axes("goal", "delivery");
        repo.create(&record).await.unwrap();
        let id = SessionId::new(record.id.clone());
        let loaded = repo.get(&id).await.unwrap().unwrap();
        assert_eq!(loaded.collaboration, "goal");
        assert_eq!(loaded.work_profile, "single");
        repo.set_axes(&id, "chat", "economy", leveler_core::now())
            .await
            .unwrap();
        let (c, w) = repo.axes(&id).await.unwrap().unwrap();
        assert_eq!((c.as_str(), w.as_str()), ("chat", "single"));
    }
}
