//! Shipping an agent's changes: branch → commit → push → PR.

use tokio_util::sync::CancellationToken;

use leveler_model::ModelRef;
use leveler_vcs::{GitWorkflow, WorkflowOptions, WorkflowOutcome, slugify};

use crate::{AppError, Application};

/// What to do with the changes after a successful run.
#[derive(Debug, Clone, Default)]
pub struct ShipOptions {
    /// Explicit branch name (else auto-generated from the goal when needed).
    pub branch: Option<String>,
    pub commit: bool,
    pub push: bool,
    pub open_pr: bool,
    pub pr_base: Option<String>,
}

impl ShipOptions {
    /// Whether any VCS action was requested.
    pub fn any(&self) -> bool {
        self.commit || self.push || self.open_pr
    }
}

impl Application {
    /// Commit / push / open a PR for the changes produced by a run.
    pub async fn ship_changes(
        &self,
        goal: &str,
        modified_files: &[String],
        verified: bool,
        model: &ModelRef,
        options: &ShipOptions,
        cancellation: CancellationToken,
    ) -> Result<WorkflowOutcome, AppError> {
        let title = commit_title(goal);
        let body = commit_body(goal, modified_files, verified);

        // Any VCS action implies a dedicated branch unless the user chose one.
        let branch = options
            .branch
            .clone()
            .or_else(|| options.any().then(|| format!("leveler/{}", slugify(goal))));

        let workflow_options = WorkflowOptions {
            branch,
            commit_message: commit_message(&title, &body, model, self.config.vcs_co_author),
            commit: options.commit,
            stage_paths: modified_files.to_vec(),
            push: options.push,
            remote: "origin".to_string(),
            open_pr: options.open_pr,
            pr_title: title,
            pr_body: body,
            pr_base: options.pr_base.clone(),
        };

        let workflow =
            GitWorkflow::with_environment(&self.layout.repo_root, self.environment.clone());
        Ok(workflow.run(&workflow_options, &cancellation).await?)
    }
}

/// A concise, imperative commit title from the goal (<= 72 chars).
fn commit_title(goal: &str) -> String {
    let first = goal
        .lines()
        .next()
        .unwrap_or(goal)
        .split(['.', '\n'])
        .next()
        .unwrap_or(goal)
        .trim();
    let mut title = first.to_string();
    if title.len() > 72 {
        let mut end = 69;
        while !title.is_char_boundary(end) {
            end -= 1;
        }
        title.truncate(end);
        title.push('…');
    }
    title
}

fn commit_body(goal: &str, modified_files: &[String], verified: bool) -> String {
    let mut s = String::new();
    s.push_str(goal.trim());
    s.push_str("\n\n");
    if !modified_files.is_empty() {
        s.push_str("Files changed:\n");
        for f in modified_files {
            s.push_str(&format!("- {f}\n"));
        }
        s.push('\n');
    }
    s.push_str(if verified {
        "Verification: passed (format/build/test).\n"
    } else {
        "Verification: not run.\n"
    });
    s.push_str("\n🤖 Generated by CodeLeveler.");
    s
}

fn commit_message(title: &str, body: &str, model: &ModelRef, co_author: bool) -> String {
    let mut message = format!("{title}\n\n{body}");
    if co_author {
        let model_label: String = model
            .to_string()
            .chars()
            .filter(|c| !matches!(c, '\r' | '\n' | '<' | '>'))
            .collect();
        message.push_str(&format!(
            "\n\nCo-Authored-By: CodeLeveler ({model_label}) <noreply@codeleveler.com>"
        ));
    }
    message
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_takes_first_sentence_and_bounds_length() {
        assert_eq!(
            commit_title("Add cancel order. And more."),
            "Add cancel order"
        );
        let long = "x".repeat(100);
        assert!(commit_title(&long).chars().count() <= 70);
    }

    #[test]
    fn body_lists_files_and_verification() {
        let b = commit_body("goal", &["a.rs".into()], true);
        assert!(b.contains("- a.rs"));
        assert!(b.contains("Verification: passed"));
    }

    #[test]
    fn commit_message_adds_model_aware_co_author_by_default() {
        let message = commit_message(
            "feat: goal",
            "body",
            &ModelRef::new("deepseek", "deepseek-v4-pro"),
            true,
        );
        assert!(message.ends_with(
            "Co-Authored-By: CodeLeveler (deepseek/deepseek-v4-pro) <noreply@codeleveler.com>"
        ));
    }

    #[test]
    fn commit_message_omits_co_author_when_disabled() {
        let message = commit_message(
            "feat: goal",
            "body",
            &ModelRef::new("deepseek", "deepseek-v4-pro"),
            false,
        );
        assert!(!message.contains("Co-Authored-By:"));
    }
}
