// Real Desktop/Runtime acceptance with test-only provider and native-picker seam.
// This does not claim an operating-system picker interaction or model quality.
import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,writeFile,readFile,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('..',import.meta.url)),temporary=await mkdtemp('/tmp/leveler-desktop-composer-'),home=path.join(temporary,'home'),output=path.join(root,'acceptance-output/desktop');await mkdir(home);await mkdir(output,{recursive:true});
const note=path.join(temporary,'note.txt'),png=path.join(temporary,'tiny.png');await writeFile(note,'hello');await writeFile(png,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4//8/AAX+Av4N70a4AAAAAElFTkSuQmCC','base64'));
const requests=[],errors=[];const server=createServer(async(req,res)=>{try{if(req.method==='GET'){res.writeHead(200,{'content-type':'text/html'});res.end('<!doctype html><title>Composer permission overlay</title><h1>Real native Browser fixture</h1>');return;}let raw='';for await(const part of req)raw+=part;const body=JSON.parse(raw);if(!(body.tools??[]).length){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'{"candidates":[]}'},finish_reason:'stop'}]}));return;}requests.push(body);res.writeHead(200,{'content-type':'text/event-stream'});for(const [delta,finish_reason] of [[{content:'COMPOSER_IMAGE_ACCEPTED'},null],[{},'stop']])res.write('data: '+JSON.stringify({id:'composer',object:'chat.completion.chunk',created:1,model:'fixture',choices:[{index:0,delta,finish_reason}]})+'\n\n');res.end('data: [DONE]\n\n');}catch(err){errors.push(err.message);res.destroy(err);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const configPath=path.join(home,'config.toml');await writeFile(configPath,`default_model = "fixture/first"\n[providers.fixture]\nprotocol = "openai_chat"\nbase_url = "http://127.0.0.1:${server.address().port}"\napi_key = "test-only"\n[models.first]\nprovider = "fixture"\nmodel_id = "first-model"\ncontext_window = 131072\nvision = true\n[models.second]\nprovider = "fixture"\nmodel_id = "second-model"\ncontext_window = 131072\nvision = true\n`,{mode:0o600});
let app,page;const pageErrors=[],evidence={scope:'isolated real Desktop/Runtime; test-only SSE provider and dialog.showOpenDialog chooser seam; not OS picker acceptance'};
async function capture(name){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot();const bytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));await writeFile(path.join(output,name+'.png'),Buffer.from(bytes,'base64'));}
async function current(){return page.evaluate(async()=>{const id=document.querySelector('.task.selected')?.dataset.sessionId;if(!id)throw Error('Missing selected task');return window.desktop.snapshot(id);});}
async function upload(file){await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.locator('#attachment-add').click();await page.waitForFunction(()=>document.querySelector('.attachment-chip[data-attachment-status="ready"]'));return page.evaluate(()=>globalThis.__composerEvents.filter(f=>f.data?.type==='attachment_added').at(-1).data);}
async function files(dir){const result=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())result.push(...await files(p));else result.push(p);}return result;}
try{
app=await electron.launch({args:[root,'--user-data-dir='+path.join(temporary,'profile')],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,LEVELER_HOME:home,LEVELER_CONFIG_DIR:undefined,LEVELER_BINARY:path.resolve(root,'../../target/debug/leveler'),LEVELER_DAEMON_IDLE_TIMEOUT_SECS:'10'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',err=>pageErrors.push(err.message));await page.waitForFunction(()=>window.desktop&&!document.querySelector('#refresh').disabled);await page.evaluate(()=>{globalThis.__composerEvents=[];globalThis.__composerEventTimes={};window.desktop.onEvent(f=>{globalThis.__composerEvents.push(f);if(f.data?.command_id)globalThis.__composerEventTimes[f.data.command_id]=Date.now();});});
assert.equal(await page.locator('#send').isDisabled(),true);await page.locator('#message').fill('Home draft stays');await page.locator('#model-picker').click();await page.locator('#model-options button').filter({hasText:'second'}).click();assert.equal((await current()).model.model,'second');assert.equal(await page.locator('#message').inputValue(),'Home draft stays');evidence.home_model_snapshot_draft=true;
await page.locator('#workspace-picker').click();await page.locator('#workspace-query').fill('unmatched');await page.locator('#workspace-query').press('Escape');assert.equal(await page.locator('#workspace-menu').isVisible(),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'workspace-picker');evidence.workspace_escape_focus=true;
await page.locator('#message').fill('Chat draft stays');await page.locator('#model-picker').click();await page.locator('#model-options button').filter({hasText:'first'}).click();assert.equal((await current()).model.model,'first');assert.equal(await page.locator('#message').inputValue(),'Chat draft stays');evidence.preturn_model_snapshot_draft=true;
await page.locator('#message').fill('IME draft');await page.locator('#message').evaluate(n=>n.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true})));assert.equal(requests.length,0);assert.equal(await page.locator('#message').inputValue(),'IME draft');await page.locator('#message').press('Shift+Enter');assert.match(await page.locator('#message').inputValue(),/\n/);assert.equal(requests.length,0);evidence.ime_shift_enter_no_send=true;
await page.locator('#message').fill('Keep unsupported file draft');// Timing seam delays only the genuine IPC reply; Runtime events remain unmodified.
await app.evaluate(({ipcMain})=>{const original=ipcMain._invokeHandlers.get('desktop:attachment');if(!original)throw Error('Missing actual attachment IPC handler');globalThis.__composerAttachmentHandler=original;ipcMain.removeHandler('desktop:attachment');ipcMain.handle('desktop:attachment',async(...args)=>{const realResult=await original(...args);await new Promise(r=>setTimeout(r,350));globalThis.__composerDelayedReply={status:realResult.status,import_id:realResult.import_id,time:Date.now()};return realResult;});});
const textResult=await upload(note);evidence.real_upload_event_before_reply_seam=true;const delay=await app.evaluate(()=>globalThis.__composerDelayedReply);assert.equal(delay.import_id,textResult.command_id);assert.ok(await page.evaluate(({id,time})=>globalThis.__composerEventTimes[id]<time,{id:textResult.command_id,time:delay.time}),'real event must precede delayed IPC reply');assert.ok(textResult.command_id);assert.equal(textResult.attachment.kind,'text_file');const storedNote=(await files(home)).find(p=>p.endsWith(textResult.attachment.sha256));assert.ok(storedNote,'Runtime must actually persist note bytes');assert.equal(await readFile(storedNote,'utf8'),'hello');await page.locator('#send').click();await page.waitForFunction(()=>!document.querySelector('#composer-error').hidden);assert.match(await page.locator('#composer-error').textContent(),/普通文件/);assert.doesNotMatch(await page.locator('#composer-error').textContent(),/Error invoking|desktop:deliver|Invalid or unregistered|IPC|data_base64/);evidence.generic_file_product_error_no_internal_ipc=true;assert.equal(await page.locator('#message').inputValue(),'Keep unsupported file draft');assert.equal(await page.locator('.attachment-chip').count(),1);assert.equal(requests.length,0);evidence.file_saved_unsupported_draft_chip_preserved=true;await capture('composer-file-unsupported');await page.getByLabel('移除附件草稿').click();
const imageResult=await upload(png);assert.ok(imageResult.command_id);assert.equal(imageResult.attachment.kind,'image');assert.equal((await current()).vision,true);assert.ok((await files(home)).some(p=>path.basename(p).startsWith(imageResult.attachment.sha256)));await page.locator('#message').fill('Read test image');await page.locator('#send').click();await page.waitForFunction(()=>document.querySelector('.message.assistant .body')?.textContent.includes('COMPOSER_IMAGE_ACCEPTED')&&['已回答','已完成'].includes(document.querySelector('#status').textContent),null,{timeout:60000});assert.equal(await page.locator('.attachment-chip').count(),0);assert.equal(await page.locator('#message').inputValue(),'');assert.ok(requests.some(r=>r.messages.some(m=>Array.isArray(m.content)&&m.content.some(c=>c.type==='image_url'&&c.image_url.url.startsWith('data:image/')))),'actual provider request must contain image bytes');evidence.image_saved_correlated_and_real_provider_input=true;
await page.locator('#message').fill('Chat draft after actual turn');await page.locator('#model-picker').click();await page.locator('#model-options button').filter({hasText:'second'}).click();assert.equal((await current()).model.model,'second');assert.equal(await page.locator('#message').inputValue(),'Chat draft after actual turn');assert.equal(await page.evaluate(()=>document.body.classList.contains('home')),false);evidence.chat_model_snapshot_draft=true;
const configBefore=await readFile(configPath,'utf8');await page.locator('#message').fill('Permission draft unchanged');
const permissionSnapshots=[];for(const mode of ['request_approval','assisted','full_access','assisted']){await page.locator('#permission').click();await page.locator('[data-permission-mode="'+mode+'"]').click();await page.waitForFunction(()=>document.querySelector('#permission-menu').hidden&&!document.querySelector('#refresh').disabled);assert.equal((await current()).mode,mode);permissionSnapshots.push(mode);assert.equal(await page.locator('#message').inputValue(),'Permission draft unchanged');}assert.equal(await readFile(configPath,'utf8'),configBefore);evidence.permission_actual_snapshots=permissionSnapshots;evidence.permission_draft_global_config_preserved=true;
await page.locator('#permission').click();await page.locator('#permission-options button').first().focus();await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.dataset.permissionMode),'assisted');await page.keyboard.press('ArrowUp');assert.equal(await page.evaluate(()=>document.activeElement.dataset.permissionMode),'full_access');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'permission');evidence.permission_keyboard_escape_focus=true;
const labelBefore=await page.locator('#permission-label').textContent();await app.evaluate(({ipcMain})=>{const original=ipcMain._invokeHandlers.get('desktop:deliver');globalThis.__composerDeliverHandler=original;ipcMain.removeHandler('desktop:deliver');ipcMain.handle('desktop:deliver',(event,envelope)=>envelope.command.type==='set_permission_profile'?{ok:false,error:{kind:'rejected',message:'Test-only permission rejection'}}:original(event,envelope));});try{await page.locator('#permission').click();await page.locator('[data-permission-mode="request_approval"]').click();await page.waitForFunction(()=>!document.querySelector('#permission-error').hidden);assert.equal(await page.locator('#permission-label').textContent(),labelBefore);assert.equal((await current()).mode,'assisted');assert.equal(await page.locator('#message').inputValue(),'Permission draft unchanged');evidence.permission_rejection_seam_no_optimistic_label=true;}finally{await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('desktop:deliver');ipcMain.handle('desktop:deliver',globalThis.__composerDeliverHandler);delete globalThis.__composerDeliverHandler;});}await page.keyboard.press('Escape');
// Read-only observation seam retains the actual manager-created tab identity.
await app.evaluate((_,modulePath)=>{const localRequire=process.getBuiltinModule('module').createRequire(modulePath);const {ManualBrowser}=localRequire(modulePath);const original=ManualBrowser.prototype.add;globalThis.__composerBrowserOriginalAdd=original;globalThis.__composerBrowserClass=ManualBrowser;ManualBrowser.prototype.add=function(...args){const tab=original.apply(this,args);globalThis.__composerNativeTab=tab;return tab;};},path.join(root,'src/browser.cjs'));
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1600,860));await page.waitForFunction(()=>innerWidth===1600);await page.locator('#browser-new').click();await page.waitForFunction(()=>window.desktop.browserState().then(state=>state.tabs.length===1));await page.locator('#browser-url').fill('http://127.0.0.1:'+server.address().port+'/composer-browser');await page.locator('#browser-url').press('Enter');await page.waitForFunction(async()=>{const state=await window.desktop.browserState();return state.tabs.some(t=>t.title==='Composer permission overlay'&&!t.loading&&!t.error&&t.id===state.selectedId);});
const nativeVisible=()=>app.evaluate(()=>globalThis.__composerNativeTab.view.getVisible());const nativeIdentity=await app.evaluate(()=>({id:globalThis.__composerNativeTab.id,webContentsId:globalThis.__composerNativeTab.view.webContents.id,urlGetter:globalThis.__composerNativeTab.view.webContents.getURL(),titleGetter:globalThis.__composerNativeTab.view.webContents.getTitle()}));assert.equal(nativeIdentity.id,(await page.evaluate(()=>window.desktop.browserState())).selectedId);evidence.permission_browser_identity=nativeIdentity;evidence.native_url_getter_diagnostic=nativeIdentity.urlGetter?'observed':'empty after observed loaded title; unresolved navigation timing diagnostic; E probe validates selected view identity/visibility, not page body rendering';await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await nativeVisible(),true);await page.locator('#permission').click();await page.waitForFunction(()=>!document.querySelector('#permission-menu').hidden);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await nativeVisible(),false);await capture('composer-permission-browser-overlay');await page.keyboard.press('Escape');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await nativeVisible(),true);evidence.permission_real_browser_surface_hidden_for_menu=true;await page.locator('#workbench-close').click();
await page.locator('#message').fill('Narrow draft');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(700,860));await page.waitForFunction(()=>innerWidth===700);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await capture('composer-narrow');
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1280,860));if(!(await page.locator('#space-add').isVisible()))await page.locator('#sidebar-toggle').click();
const oldId=(await current()).id;const workspaceA=path.join(temporary,'workspace-a'),workspaceB=path.join(temporary,'workspace-b');await mkdir(workspaceA);await mkdir(workspaceB);
async function chooseWorkspaceFixture(folder){await app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});},folder);await page.locator('#space-add').click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='未连接');}
await chooseWorkspaceFixture(workspaceA);assert.notEqual(await page.locator('#message').inputValue(),'Narrow draft');await page.locator('#message').fill('Home workspace draft');await chooseWorkspaceFixture(workspaceB);assert.equal(await page.locator('#message').inputValue(),'Home workspace draft');await page.locator('#send').click();await page.waitForFunction(()=>document.querySelector('.message.assistant .body')?.textContent.includes('COMPOSER_IMAGE_ACCEPTED')&&['已回答','已完成'].includes(document.querySelector('#status').textContent),null,{timeout:60000});await page.locator('.task[data-session-id=\"'+oldId+'\"]').click();await page.waitForFunction(()=>document.querySelector('#status').textContent!=='连接 Runtime…');assert.equal(await page.locator('#message').inputValue(),'Narrow draft');await page.locator('#workspaces button').filter({hasText:'workspace-b'}).click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='未连接');assert.equal(await page.locator('#message').inputValue(),'Home workspace draft');evidence.workspace_home_draft_preserved_old_task_separate=true;await capture('composer-workspace-drafts');assert.deepEqual(errors,[]);assert.deepEqual(pageErrors,[]);Object.assign(evidence,{page_errors:pageErrors,provider_errors:errors,provider_calls:requests.length,narrow_no_horizontal_overflow:true,passed:true});
}catch(err){Object.assign(evidence,{passed:false,error:err.message,page_errors:pageErrors});if(page&&!page.isClosed())await capture('composer-failure').catch(()=>{});throw err;}
finally{await writeFile(path.join(output,'composer-evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));if(app){await app.evaluate(({ipcMain})=>{if(globalThis.__composerBrowserOriginalAdd){globalThis.__composerBrowserClass.prototype.add=globalThis.__composerBrowserOriginalAdd;delete globalThis.__composerBrowserOriginalAdd;delete globalThis.__composerBrowserClass;delete globalThis.__composerNativeTab;delete globalThis.__composerNativeManager;}if(globalThis.__composerAttachmentHandler){ipcMain.removeHandler('desktop:attachment');ipcMain.handle('desktop:attachment',globalThis.__composerAttachmentHandler);delete globalThis.__composerAttachmentHandler;}});await app.close();}await new Promise(r=>server.close(r));}
