// Existing read-only commands, real Main/preload/Rust Runtime in isolated HOME.
import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {provider} from '../test/fixtures/provider.mjs';
const root=fileURLToPath(new URL('..',import.meta.url)),tmp=await mkdtemp('/tmp/leveler-desktop-settings-'),home=path.join(tmp,'home'),workspace=path.join(tmp,'workspace'),output=path.join(root,'acceptance-output/desktop');await mkdir(home);await mkdir(workspace);await mkdir(output,{recursive:true});const fixture=await provider();const config=`default_model="fixture/m"\n[providers.fixture]\nprotocol="openai_chat"\nbase_url="${fixture.baseURL}"\napi_key="test-only"\n[models.m]\nprovider="fixture"\nmodel_id="fixture"\ncontext_window=131072\n`;await writeFile(path.join(home,'config.toml'),config,{mode:0o600});let app,page,id,recentPath;const errors=[],evidence={scope:'Existing settings queries: real Main/preload/Rust Runtime; no inference, isolated HOME; native folder chooser seam'};
async function deliver(command){return page.evaluate(({id,command})=>window.desktop.deliver({command_id:crypto.randomUUID(),session_id:id,expected_version:null,issued_at:new Date().toISOString(),command:{...command,session_id:id}}),{id,command});}
async function query(type,event,extra={}){const query_id=crypto.randomUUID();assert.equal((await deliver({type,query_id,...extra})).ok,true);await page.waitForFunction(({query_id,event})=>globalThis.__settingsFrames.some(f=>f.event==='runtime'&&f.data?.type===event&&f.data.query_id===query_id),{query_id,event});return page.evaluate(query_id=>globalThis.__settingsFrames.find(f=>f.data?.query_id===query_id).data,query_id);}
try{app=await electron.launch({args:[root,'--user-data-dir='+path.join(tmp,'profile')],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,LEVELER_HOME:home,LEVELER_CONFIG_DIR:undefined,LEVELER_BINARY:path.resolve(root,'../../target/debug/leveler'),LEVELER_DAEMON_IDLE_TIMEOUT_SECS:'10'}});page=await app.firstWindow();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>window.desktop&&!document.querySelector('#refresh').disabled);await page.evaluate(()=>{globalThis.__settingsFrames=[];window.desktop.onEvent(f=>globalThis.__settingsFrames.push(f));});id=(await page.evaluate(()=>window.desktop.createTask(null))).session.id;
const agents=await query('list_agents','agents_loaded');assert.ok(Array.isArray(agents.agents));const missing=await query('get_agent','agent_loaded',{name:'acceptance-agent-does-not-exist'});assert.equal(missing.agent??null,null);assert.ok(missing.error);const context=await query('query_context','context_loaded');assert.equal(context.accounting??null,null);const observation=await query('query_observability','observability_loaded',{center_seq:null,before:2,after:2});assert.ok(observation.observation);evidence.queries={agents:{query_id:agents.query_id,count:agents.agents.length},missing_agent:{query_id:missing.query_id,error:missing.error,no_fake_agent:true},context:{query_id:context.query_id,accounting:context.accounting??null},observability:{query_id:observation.query_id,actual_payload:true}};
const memory=await query('list_memory','memory_list',{include_archived:true});assert.ok(memory.memory_dir.startsWith(tmp+path.sep));assert.deepEqual(memory.active,[]);assert.deepEqual(memory.archived,[]);assert.deepEqual(memory.pending,[]);evidence.memory={actual_empty_control_query_id:memory.query_id,failures:[]};
for(const folder of ['active','archive','pending']){const directory=path.join(memory.memory_dir,folder);await mkdir(directory,{recursive:true});const broken=path.join(directory,'broken.json');await writeFile(broken,'not JSON');const start=await page.evaluate(()=>globalThis.__settingsFrames.length),query_id=crypto.randomUUID();assert.equal((await deliver({type:'list_memory',query_id,include_archived:true})).ok,true);await page.waitForFunction(start=>globalThis.__settingsFrames.slice(start).some(f=>f.data?.type==='notification'&&f.data.level==='warning'&&f.data.message.startsWith('memory list failed:')),start);const frames=await page.evaluate(start=>globalThis.__settingsFrames.slice(start),start);assert.equal(frames.some(f=>f.data?.type==='memory_list'&&f.data.query_id===query_id),false);evidence.memory.failures.push({folder,query_id,warning:true,no_fake_empty:true,warning_has_query_id:false});await rm(broken);await query('list_memory','memory_list',{include_archived:true});}
await app.evaluate(({dialog},workspace)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[workspace]});},workspace);const project=await page.evaluate(async()=>{const folder=await window.desktop.chooseFolder();return window.desktop.createTask(folder.id);});id=project.session.id;recentPath=(await page.evaluate(id=>window.desktop.snapshot(id),id)).repository;await page.evaluate(()=>window.desktop.listTasks());const archivedRead=await page.evaluate(()=>window.desktop.listTasks({include_archived:true}));assert.ok(archivedRead.tasks.some(t=>t.id===id));assert.ok((await page.evaluate(workspace=>window.desktop.chooseRecentWorkspace(workspace),recentPath)).id);assert.equal((await deliver({type:'archive_session'})).ok,true);assert.equal((await page.evaluate(()=>window.desktop.listTasks())).tasks.some(t=>t.id===id),false);const archived=await page.evaluate(()=>window.desktop.listTasks({include_archived:true}));const entry=archived.tasks.find(t=>t.id===id);assert.ok(entry.archived_at);await assert.rejects(()=>page.evaluate(workspace=>window.desktop.chooseRecentWorkspace(workspace),recentPath));evidence.archive={default_hidden:true,actual_archived_timestamp:entry.archived_at,archived_read_preserves_existing_grant:true,archived_read_cannot_grant:true};
const bad=path.join(home,'state/projects/corrupt-fixture');await mkdir(bad,{recursive:true});await writeFile(path.join(bad,'sessions.db'),'corrupt');const index=await page.evaluate(()=>window.desktop.listTasks({include_archived:true}));assert.ok(index.source_errors.length>0);assert.ok(index.tasks.some(t=>t.id===id));evidence.source_errors={actual_corrupt_database:true,count:index.source_errors.length,valid_tasks_retained:true};assert.equal(await readFile(path.join(home,'config.toml'),'utf8'),config);assert.equal(fixture.requests.length,0);assert.deepEqual(errors,[]);Object.assign(evidence,{provider_calls:0,page_errors:errors,global_config_unchanged:true,passed:true});
}catch(error){Object.assign(evidence,{passed:false,error:error.message,page_errors:errors});throw error;}finally{if(app)await app.close();await fixture.close();await writeFile(path.join(output,'settings-queries-evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));}
