// G: real Runtime plans and Git diff in an isolated temporary workspace.
// Only provider output and native folder choice use explicit test-only seams.
import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdtemp,mkdir,writeFile,rename,realpath} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const exec=promisify(execFile),root=fileURLToPath(new URL('..',import.meta.url)),temporary=await mkdtemp('/tmp/leveler-desktop-views-'),home=path.join(temporary,'home'),workspace=path.join(temporary,'workspace'),output=path.join(root,'acceptance-output/desktop');await mkdir(home);await mkdir(workspace);await mkdir(output,{recursive:true});
const shortBefore='first\nsecond\n',longBefore=Array.from({length:160},(_,i)=>`original-${i}: `+'x'.repeat(240)).join('\n')+'\n';await writeFile(path.join(workspace,'note.txt'),shortBefore);await writeFile(path.join(workspace,'long.txt'),longBefore);await exec('git',['init'],{cwd:workspace});await exec('git',['add','note.txt','long.txt'],{cwd:workspace});await exec('git',['-c','user.name=Desktop Fixture','-c','user.email=fixture@example.invalid','commit','-m','Test-only fixture baseline'],{cwd:workspace});await writeFile(path.join(workspace,'note.txt'),'first changed\nsecond changed\n');await writeFile(path.join(workspace,'long.txt'),Array.from({length:160},(_,i)=>`updated-${i}: `+'y'.repeat(240)).join('\n')+'\n');
const longStep='Inspect actual diff and preserve readable long descriptions. '.repeat(80);let calls=0,finishPlan;const finalGate=new Promise(resolve=>{finishPlan=resolve;});const providerErrors=[];
const server=createServer(async(req,res)=>{try{let raw='';for await(const part of req)raw+=part;const body=JSON.parse(raw),names=(body.tools??[]).map(t=>t.function?.name);if(!names.length){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'{"candidates":[]}'},finish_reason:'stop'}]}));return;}calls++;assert.ok(names.includes('update_plan'),'Real provider schema must expose registered update_plan');const completed=body.messages.filter(m=>m.role==='tool').length;const plan=completed===0?[{step:'Inspect temporary Git workspace',status:'completed'},{step:longStep,status:'in_progress'},{step:'Verify actual changes',status:'pending'}]:[{step:'Inspect temporary Git workspace',status:'completed'},{step:longStep,status:'completed'},{step:'Verify actual changes',status:'in_progress'}];if(completed>=2)await finalGate;const delta=completed<2?{tool_calls:[{index:0,id:'g-plan-'+completed,type:'function',function:{name:'update_plan',arguments:JSON.stringify({plan,explanation:'Test-only provider requesting the actual registered plan tool'})}}]}:{content:'VIEWS_PLAN_COMPLETE'};res.writeHead(200,{'content-type':'text/event-stream'});for(const [d,finish] of [[delta,null],[{},completed<2?'tool_calls':'stop']])res.write('data: '+JSON.stringify({id:'views',object:'chat.completion.chunk',created:1,model:'fixture',choices:[{index:0,delta:d,finish_reason:finish}]})+'\n\n');res.end('data: [DONE]\n\n');}catch(err){providerErrors.push(err.message);res.writeHead(500);res.end('fixture failed');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
await writeFile(path.join(home,'config.toml'),`default_model = "fixture/m"\n[providers.fixture]\nprotocol = "openai_chat"\nbase_url = "http://127.0.0.1:${server.address().port}"\napi_key = "test-only"\n[models.m]\nprovider = "fixture"\nmodel_id = "fixture-model"\ncontext_window = 131072\nparallel_tool_calls = false\n`,{mode:0o600});
let app,page,id;const errors=[],evidence={scope:'G real Desktop/Runtime, registered update_plan tool and real temporary Git diff; isolated home/workspace; test-only SSE provider and native-folder-picker seam'};
async function capture(name){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot();const bytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));await writeFile(path.join(output,name+'.png'),Buffer.from(bytes,'base64'));}
async function requestDiff(){const count=await page.evaluate(()=>globalThis.__viewsEvents.length);const button=page.locator('#diff-refresh:visible,#diff-retry:visible,#overview-changes:visible').first();await button.click();await page.waitForFunction(count=>globalThis.__viewsEvents.slice(count).some(f=>f.data?.query_id&&['diff_updated','diff_failed'].includes(f.data.type)),count);return page.evaluate(count=>globalThis.__viewsEvents.slice(count).find(f=>f.data?.query_id&&['diff_updated','diff_failed'].includes(f.data.type)).data,count);}

try{
app=await electron.launch({args:[root,'--user-data-dir='+path.join(temporary,'profile')],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,LEVELER_HOME:home,LEVELER_CONFIG_DIR:undefined,LEVELER_BINARY:path.resolve(root,'../../target/debug/leveler'),LEVELER_DAEMON_IDLE_TIMEOUT_SECS:'10'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',err=>errors.push(err.message));await page.waitForFunction(()=>window.desktop&&!document.querySelector('#refresh').disabled);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1600,1000));await page.evaluate(()=>{globalThis.__viewsEvents=[];window.desktop.onEvent(f=>globalThis.__viewsEvents.push(f));});await app.evaluate(({dialog},workspace)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[workspace]});},workspace);await page.locator('#space-add').click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='未连接');await page.locator('#message').fill('Create a real plan for this isolated workspace');await page.locator('#send').click();await page.waitForFunction(()=>globalThis.__viewsEvents.filter(f=>f.data?.type==='plan_updated').length>=2,null,{timeout:60000});id=await page.locator('.task.selected').getAttribute('data-session-id');const snapshot=await page.evaluate(id=>window.desktop.snapshot(id),id);assert.equal(snapshot.repository,await realpath(workspace));assert.equal(snapshot.plan.steps.length,3);const planEvents=await page.evaluate(()=>globalThis.__viewsEvents.filter(f=>f.data?.type==='plan_updated').map(f=>f.data.plan));assert.ok(planEvents.length>=2);assert.ok(planEvents.some(p=>p.steps.some(s=>s.status==='running')));evidence.real_registered_plan_tool_updates=planEvents.length;
await page.locator('#workbench-view').selectOption('plan');await page.waitForFunction(()=>document.querySelector('#workbench-content').textContent.includes('Inspect temporary Git workspace'));assert.match(await page.locator('#workbench-content').textContent(),/完成|进行中|待开始/);await capture('views-plan');finishPlan();await page.waitForFunction(()=>document.querySelector('.message.assistant .body')?.textContent.includes('VIEWS_PLAN_COMPLETE')&&['已回答','已完成'].includes(document.querySelector('#status').textContent),null,{timeout:60000});
await page.locator('#workbench-view').selectOption('overview');const diff=await requestDiff();assert.equal(diff.type,'diff_updated');assert.equal(diff.diff.files.length,2);assert.ok(diff.diff.files.some(f=>f.path==='note.txt'&&f.added===2&&f.removed===2));assert.ok(diff.diff.files.some(f=>f.path==='long.txt'&&f.patch.length>60000));await page.locator('#workbench-view').selectOption('overview');await capture('views-overview');await page.locator('#workbench-view').selectOption('changes');await page.waitForFunction(()=>document.querySelector('#workbench-content').textContent.includes('note.txt'));await page.locator('#workbench-content details').filter({hasText:'long.txt'}).locator('summary').click();const patch=page.locator('#workbench-content details').filter({hasText:'long.txt'}).locator('pre');assert.ok((await patch.textContent()).length>60000);await capture('views-changes');evidence.real_git_diff={files:2,note_added:2,note_removed:2,long_patch_chars:await patch.evaluate(n=>n.textContent.length)};
await rename(path.join(workspace,'.git'),path.join(workspace,'.git-unavailable'));const failed=await requestDiff();assert.equal(failed.type,'diff_failed');await page.waitForFunction(()=>document.querySelector('#workbench-content').textContent.includes('无法'));await capture('views-error');await rename(path.join(workspace,'.git-unavailable'),path.join(workspace,'.git'));const countBefore=await page.evaluate(()=>globalThis.__viewsEvents.filter(f=>f.data?.type==='diff_updated').length);await page.locator('#diff-retry').click();await page.waitForFunction(count=>globalThis.__viewsEvents.filter(f=>f.data?.type==='diff_updated').length>count,countBefore);await page.waitForFunction(()=>document.querySelector('#workbench-content').textContent.includes('note.txt'));evidence.real_diff_error_retry=true;
await writeFile(path.join(workspace,'note.txt'),shortBefore);await writeFile(path.join(workspace,'long.txt'),longBefore);const empty=await requestDiff();assert.equal(empty.type,'diff_updated');assert.equal(empty.diff.files.length,0);await page.waitForFunction(()=>/没有.*变更|暂无.*变更/.test(document.querySelector('#workbench-content').textContent));await capture('views-empty');evidence.real_diff_empty=true;
await writeFile(path.join(workspace,'long.txt'),Array.from({length:160},(_,i)=>`narrow-${i}: `+'z'.repeat(240)).join('\n')+'\n');await requestDiff();await page.waitForFunction(()=>document.querySelector('#workbench-content').textContent.includes('long.txt'));await page.locator('#workbench-content details').filter({hasText:'long.txt'}).locator('summary').click();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(700,1000));await page.waitForFunction(()=>innerWidth===700);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const overflow=await page.locator('#workbench-content pre').evaluate(n=>({x:getComputedStyle(n).overflowX,y:getComputedStyle(n).overflowY,scrolls:n.scrollWidth>n.clientWidth}));assert.equal(overflow.x,'auto');assert.equal(overflow.scrolls,true);await capture('views-narrow-long-patch');Object.assign(evidence,{narrow_patch_internal_overflow:overflow,provider_calls:calls,provider_errors:providerErrors,page_errors:errors,passed:true});assert.deepEqual(providerErrors,[]);assert.deepEqual(errors,[]);
}catch(err){Object.assign(evidence,{passed:false,error:err.message,provider_errors:providerErrors,page_errors:errors});if(page&&!page.isClosed())await capture('views-failure').catch(()=>{});throw err;}
finally{finishPlan();await writeFile(path.join(output,'views-evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));if(app)await app.close();await new Promise(r=>server.close(r));}
