// F layout/interaction acceptance through real Desktop/Runtime and local HTTP.
// The HTTP page is test-only. Full Browser execution/binding acceptance is separate.
import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('..',import.meta.url)),temporary=await mkdtemp('/tmp/leveler-desktop-workbench-'),home=path.join(temporary,'home'),profile=path.join(temporary,'profile'),output=path.join(root,'acceptance-output/desktop');await mkdir(home);await mkdir(output,{recursive:true});let pageRequests=0;
const server=createServer((req,res)=>{if(req.method==='GET'){pageRequests++;res.writeHead(200,{'content-type':'text/html'});res.end('<!doctype html><title>F actual native tab</title><h1>Workbench HTTP fixture</h1>');}else{res.writeHead(500);res.end('F must not invoke a provider');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/';
await writeFile(path.join(home,'config.toml'),`default_model = "fixture/m"\n[providers.fixture]\nprotocol = "openai_chat"\nbase_url = "${url}"\napi_key = "test-only"\n[models.m]\nprovider = "fixture"\nmodel_id = "fixture-model"\ncontext_window = 131072\n`,{mode:0o600});
let app,page;const errors=[],evidence={scope:'F actual Desktop/Runtime layout and manual Browser tab interaction; isolated home/profile, test-only HTTP page; not full Browser or Agent binding acceptance'};
async function launch(){app=await electron.launch({args:[root,'--user-data-dir='+profile],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,LEVELER_HOME:home,LEVELER_CONFIG_DIR:undefined,LEVELER_BINARY:path.resolve(root,'../../target/debug/leveler'),LEVELER_DAEMON_IDLE_TIMEOUT_SECS:'10'}});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>window.desktop&&!document.querySelector('#refresh').disabled);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1600,900));await page.waitForFunction(()=>innerWidth===1600);}
async function frame(){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function width(){return Math.round((await page.locator('#workbench').boundingBox()).width);}
async function capture(name){await frame();await page.screenshot();const bytes=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));await writeFile(path.join(output,name+'.png'),Buffer.from(bytes,'base64'));}
try{
await launch();assert.equal(await page.locator('#workbench').isVisible(),true);assert.equal(await width(),360);assert.equal(await page.locator('#workbench-overview').isVisible(),true);assert.equal(await page.locator('#workbench-overview').getAttribute('aria-selected'),'true');assert.match(await page.locator('#artifacts-group').textContent(),/暂无可展示内容/);await capture('workbench-default-overview');await page.locator('#artifacts-group summary').click();assert.equal(await page.locator('#artifacts-group').evaluate(n=>n.open),true);assert.equal(await page.getByText('暂无可展示内容',{exact:true}).isVisible(),true);await page.locator('#artifacts-group summary').click();assert.equal(await page.locator('#artifacts-group').evaluate(n=>n.open),false);evidence.artifacts_collapsible_truthful_empty=true;evidence.default_fixed_overview_360=true;
await page.locator('#new-task').click();await page.waitForFunction(()=>document.querySelector('.task.selected'));await page.locator('#message').fill('F draft must survive workbench interaction');const id=await page.locator('.task.selected').getAttribute('data-session-id');assert.ok((await page.evaluate(id=>window.desktop.snapshot(id),id)).id===id);
await page.locator('#browser-new').click();await page.waitForFunction(async()=>{const s=await window.desktop.browserState();return s.tabs.length===1;});await page.waitForFunction(()=>document.querySelectorAll('#browser-tabs [role=tab]').length===1&&document.querySelector('#workbench-overview').getAttribute('aria-selected')==='false');assert.equal(await page.locator('#workbench-overview').isVisible(),true);assert.equal(await page.locator('#browser-tabs [role=tab]').count(),1);// F observes real native tab creation/selection with about:blank; H owns navigation/body proof.
assert.equal(await page.locator('#workbench-overview').getAttribute('aria-selected'),'false');await capture('workbench-browser-fixed-entry');evidence.manual_tab_and_fixed_overview_entry=true;
await page.locator('#workbench-overview').click();assert.equal(await page.locator('#workbench-overview').getAttribute('aria-selected'),'true');assert.equal((await page.evaluate(()=>window.desktop.browserState())).tabs.length,1);await page.locator('#browser-tabs [role=tab]').first().click();await page.waitForFunction(()=>document.querySelector('#workbench-overview').getAttribute('aria-selected')==='false');assert.equal(await page.locator('#workbench-overview').getAttribute('aria-selected'),'false');
const beforeFull=await width();await page.locator('#workbench-expand').click();await frame();assert.equal(await page.locator('#sidebar').isVisible(),false);assert.equal(await page.locator('main').isVisible(),false);const rect=await page.locator('#workbench').boundingBox();assert.ok(rect.x<=1&&Math.abs(rect.width-1600)<=2);assert.equal(await page.locator('#workbench-expand').getAttribute('aria-pressed'),'true');await capture('workbench-whole-content-fullscreen');await page.locator('#workbench-expand').click();await frame();assert.equal(await page.locator('#sidebar').isVisible(),true);assert.equal(await page.locator('main').isVisible(),true);assert.equal(await width(),beforeFull);assert.equal(await page.locator('#message').inputValue(),'F draft must survive workbench interaction');evidence.whole_content_fullscreen_restore_draft=true;
await page.locator('#workbench-close').click();assert.equal(await page.locator('#workbench').isVisible(),false);await page.locator('#workbench-toggle').click();await frame();assert.equal(await page.locator('#workbench').isVisible(),true);assert.equal(await width(),beforeFull);assert.equal(await page.locator('#message').inputValue(),'F draft must survive workbench interaction');await capture('workbench-restored');evidence.close_reopen_retains_view_width_draft=true;
await page.locator('#workbench-overview').click();const handle=page.locator('#resize-handle');await handle.focus();const beforeKey=await width();await page.keyboard.press('ArrowLeft');await frame();const afterKey=await width();assert.equal(afterKey,beforeKey+20);const bounds=await handle.boundingBox();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+100);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2-220,bounds.y+100,{steps:8});await page.mouse.up();await frame();const userWidth=await width();assert.ok(userWidth>=afterKey+200);evidence.keyboard_and_pointer_resize={beforeKey,afterKey,userWidth};await capture('workbench-user-width');await page.locator('#browser-tabs [role=tab]').first().click();await page.waitForFunction(()=>document.querySelector('#workbench-overview').getAttribute('aria-selected')==='false');await frame();assert.equal(await page.locator('#overview-pane').isVisible(),true);const contextRect=await page.locator('#overview-pane').boundingBox();assert.ok(Math.abs(contextRect.width-180)<=2);await capture('workbench-browser-context');evidence.wide_browser_context_180=true;await page.locator('#workbench-overview').click();
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(700,900));await page.waitForFunction(()=>innerWidth===700);await frame();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#workbench-backdrop').isVisible(),true);const activeInWorkbench=await page.evaluate(()=>document.querySelector('#workbench').contains(document.activeElement));assert.equal(activeInWorkbench,true,'resize into overlay must retain focus within Workbench');const focusable=page.locator('#workbench button:visible:not(:disabled),#workbench select:visible:not(:disabled),#workbench [tabindex="0"]:visible');await focusable.last().focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.querySelector('#workbench').contains(document.activeElement)),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#workbench').isVisible(),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'workbench-toggle');await page.locator('#workbench-toggle').click();await frame();assert.equal(await page.evaluate(()=>document.querySelector('#workbench').contains(document.activeElement)),true);await capture('workbench-narrow-overlay');evidence.narrow_overlay_focus_escape_no_overflow=true;
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1600,900));await frame();assert.equal(await width(),userWidth);await app.close();app=null;await launch();assert.equal(await width(),userWidth);evidence.user_width_persists_restart=true;assert.deepEqual(errors,[]);Object.assign(evidence,{page_errors:errors,http_page_requests:pageRequests,passed:true});
}catch(err){Object.assign(evidence,{passed:false,error:err.message,page_errors:errors});if(page&&!page.isClosed())await capture('workbench-failure').catch(()=>{});throw err;}
finally{await writeFile(path.join(output,'workbench-evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));if(app)await app.close();await new Promise(r=>server.close(r));}
