import {renderMarkdown} from './markdown.mjs';
import {modelLabel,workspaceLabel,toolLabel,toolTarget,browserActivity,sourceErrorSummary,relativeActivity,permissionLabel,recentWorkspaces,filterTasks,taskSearchResults,renameCommand,conversationMatches,messageKind,messageRoleLabel,historyQuestions,planStepLabel,availableWorkbenchViews,browserTabIndex,browserChrome,browserSurfaceBounds,focusWorkbenchEntry,retainBrowserAddressOnBlur,workspaceTaskGroups,attachmentErrorPresentation,focusRestoreIndex,slashIntent,commandCandidates,activateSettingsShortcut,groupExecutionRounds,roundGlyph,roundHeadline,contractToolStatus,failureReason,displayPreview} from './presentation.mjs';
import {projectSnapshot,applySessionMetadata,applyEvent,commandEnvelope,terminalEvents,approvalDecisions,clarificationAnswer,uploadDraft,applyUploadEvent,reconcileUploadReply,workspaceDraftText,attachmentSubmissionError,permissionCommand,permissionConfirmed,workbenchLayout,beginDiffQuery,expireDiffQuery,beginReadQuery,applyReadResult,expireReadQuery} from './state.mjs';
const api=window.desktop;
const $=id=>document.getElementById(id);
let currentSource=null;let tasks=[],current=null,selection=null,history=[],loading=false,busy=0,opening=0,uncertain=null;
let settingsComposing=false;let settingsRenderedOwner=null,settingsWarnings=[];let settingsSection='appearance',settingsFocus=null,archiveRead=null,archiveReadVersion=0,commandSelected=0,commandDismissed=false;const settingsReads=new Map(),settingsTimers=new Map();let sourceErrors=[];let diffTimer=null;let paintPending=false,taskFilter={status:'all',time:'all'},searchResults=[],searchSelected=0,searchFocus=null;const foldedWorkspaces=new Set();const drafts=new Map();const attachmentDrafts=new Map();let uploadingKey=null,earlyUpload=null;const renderedSources=new WeakMap();let titleEditingSession=null,taskMenuSession=null,archiveTarget=null,findMatches=[],findSelected=0,titleComposing=false;
const labels={idle:'就绪',running:'运行中',waiting_user:'等待你处理',answered:'已回答',completed:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断',blocked:'受阻',incomplete:'未完成',unknown:'未知'};
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
const iconPaths={menu:'M4 6h16M4 12h16M4 18h16',sidebar:'M4 4h16v16H4zM9 4v16',search:'M10.5 4a6.5 6.5 0 1 0 0 13a6.5 6.5 0 0 0 0-13M16 16l4 4',filter:'M4 5h16l-6 7v6l-4 2v-8z',plus:'M12 5v14M5 12h14',folder:'M3 7h7l2-3h9v16H3z',more:'M5 12h.01M12 12h.01M19 12h.01',edit:'M5 16l-1 4 4-1L20 7l-3-3zM14 7l3 3',close:'M6 6l12 12M18 6L6 18',up:'M12 19V5M5 12l7-7 7 7',down:'M12 5v14M5 12l7 7 7-7',back:'M19 12H5M12 5l-7 7 7 7',forward:'M5 12h14M12 5l7 7-7 7',reload:'M20 8a8 8 0 1 0 1 6M20 3v5h-5',external:'M14 4h6v6M20 4l-9 9M10 4H4v16h16v-6',expand:'M9 3H3v6M15 3h6v6M21 15v6h-6M9 21H3v-6',restore:'M3 9h6V3M15 3v6h6M21 15h-6v6M9 21v-6H3',collapse:'M7 4l8 8-8 8M20 4v16',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z',history:'M3 4v5h5M3 9a9 9 0 1 1 1 8M12 7v5l3 2',workbench:'M3 4h18v16H3zM15 4v16',check:'M5 12l4 4L19 6',chevron:'M6 9l6 6 6-6',copy:'M9 8h11v13H9zM5 16H3V3h11v2',settings:'M4 7h16M4 17h16M8 4v6M16 14v6'};
function svgIcon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.setAttribute('focusable','false');svg.setAttribute('class','ui-icon');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',iconPaths[name]??iconPaths.menu);svg.append(path);return svg;}
function setIcon(id,name){$(id).replaceChildren(svgIcon(name));}
function restoreFocus(origin){const overlay=workbenchOpen&&(workbenchExpanded||document.body.classList.contains('workbench-overlay'));const candidates=[origin,$('workbench-overview'),$('sidebar-toggle'),$('workbench-toggle'),$('message')];const facts=candidates.map(node=>({connected:!!node?.isConnected,visible:!!node?.getClientRects().length,enabled:!!node&&!node.disabled,inWorkbench:!!node&&$('workbench').contains(node)}));candidates[focusRestoreIndex(facts,overlay)]?.focus();}
function error(message){$('error').textContent=message;$('error').hidden=!message;}
async function action(callback,{onError=null,clearGlobal=true}={}){if(clearGlobal)error('');busy++;loading=true;controls();try{return await callback();}catch(err){if(onError)onError(err.message);else error(err.message);}finally{loading=--busy>0;controls();}}
function controls(){
  const uploadPending=attachments().some(item=>['uploading','queued','unknown'].includes(item.status));
  $('send').disabled=loading||!!uncertain||uploadPending||(!$('message').value.trim()&&!attachments().some(item=>item.status==='ready'));
  $('attachment-add').disabled=loading||uploadPending;
  $('workspace-picker').disabled=loading||uploadPending;
  $('model-picker').disabled=loading||!!uncertain||uploadPending;
  $('new-task').disabled=loading||uploadPending;
  $('folder').disabled=loading||uploadPending;
  $('refresh').disabled=loading;
  $('clear-folder').disabled=loading||uploadPending;
  $('cancel').hidden=!['running','waiting_user'].includes(current?.status);
  $('cancel').disabled=loading;
  for(const button of document.querySelectorAll('#tasks button,#workspaces button:not(.workspace-fold):not(.workspace-name),#interactions button'))button.disabled=loading||!!uncertain||uploadPending;
  for(const button of document.querySelectorAll('#model-options button,#permission-options button'))button.disabled=loading||!!uncertain||uploadPending;
  $('permission').disabled=loading||!!uncertain||uploadPending;$('home-permission').disabled=loading||!!uncertain||uploadPending;
  for(const id of ['title-save','title-cancel','title-input','title-edit','task-history','archive-confirm','task-menu-rename','task-menu-archive','search-toggle'])$(id).disabled=loading||!!uncertain||uploadPending;
  $('archive-cancel').disabled=loading;
  for(const button of document.querySelectorAll('#settings-content button[data-session-action]'))button.disabled=!current||loading||!!uncertain||uploadPending;
  const retry=document.querySelector('#interactions [data-retry]');if(retry)retry.disabled=loading;
  $('status').textContent=loading?'连接 Runtime…':current?(current.approvals.length||current.clarifications.length?'等待你处理':current.activity||labels[current.status]||current.status):'未连接';
}
function basename(path){return String(path??'').split(/[\\/]/).filter(Boolean).at(-1)||'Workspace';}
function taskRow(task){
 const button=el('button',undefined,'task'+(task.id===current?.session.id?' selected':''));button.dataset.sessionId=task.id;button.title=task.title||'未命名任务';button.append(el('strong',task.title||'未命名任务'),el('small',relativeActivity(task.last_activity_at??task.updated_at)));button.disabled=loading||!!uncertain||uploadPending();button.addEventListener('click',()=>action(()=>openTask(task)));
 const row=el('div',undefined,'task-row'),more=el('button',undefined,'task-more');more.append(svgIcon('more'));more.setAttribute('aria-label',`任务操作：${task.title||'未命名任务'}`);more.title='任务操作';more.setAttribute('aria-haspopup','menu');more.disabled=button.disabled;more.addEventListener('click',()=>openTaskMenu(task,more));row.addEventListener('contextmenu',event=>{event.preventDefault();openTaskMenu(task,more,{x:event.clientX,y:event.clientY});});row.append(button,more);return row;
}
function renderTasks(){
 const nav=$('tasks'),workspaces=$('workspaces'),all=workspaceTaskGroups(tasks),filtered=workspaceTaskGroups(filterTasks(tasks,taskFilter));nav.replaceChildren();workspaces.replaceChildren();
 $('task-count').textContent=`(${all.loose.length})`;$('space-count').textContent=`(${all.spaces.length})`;$('tasks-toggle').setAttribute('aria-label',`任务：${all.loose.length} 个独立任务，当前筛选 ${filtered.loose.length} 个`);$('spaces-toggle').setAttribute('aria-label',`空间：${all.spaces.length} 个真实工作空间`);
 if(!filtered.loose.length)nav.append(el('p',all.loose.length?'当前筛选没有匹配的独立任务':'暂无独立任务','empty'));for(const task of filtered.loose)nav.append(taskRow(task));
 for(const space of all.spaces){const group=el('section',undefined,'workspace-group');group.dataset.workspacePath=space.path;const heading=el('div',undefined,'workspace-heading'),fold=el('button',undefined,'workspace-fold'),name=el('button',undefined,'workspace-name');const expanded=!foldedWorkspaces.has(space.path);fold.append(svgIcon('chevron'));fold.setAttribute('aria-label',`${expanded?'折叠':'展开'}空间 ${space.name}`);fold.setAttribute('aria-expanded',String(expanded));const toggle=origin=>{if(foldedWorkspaces.has(space.path))foldedWorkspaces.delete(space.path);else foldedWorkspaces.add(space.path);renderTasks();[...workspaces.querySelectorAll('.workspace-group')].find(node=>node.dataset.workspacePath===space.path)?.querySelector('.'+origin)?.focus();};fold.addEventListener('click',()=>toggle('workspace-fold'));name.append(svgIcon('folder'),el('span',space.name));name.title=space.path;name.setAttribute('aria-expanded',String(expanded));name.addEventListener('click',()=>toggle('workspace-name'));const create=el('button',undefined,'workspace-new');create.append(svgIcon('plus'));create.title='在此工作空间新建任务';create.setAttribute('aria-label',`在空间 ${space.name} 新建任务`);create.disabled=loading||!!uncertain||uploadPending();create.addEventListener('click',()=>action(()=>chooseWorkspace(space.path)));heading.append(fold,name,create);group.append(heading);const list=el('div',undefined,'workspace-tasks');list.hidden=!expanded;const matches=filtered.spaces.find(item=>item.path===space.path)?.tasks??[];for(const task of matches)list.append(taskRow(task));if(!matches.length)list.append(el('p','当前筛选没有匹配的对话','workspace-empty'));group.append(list);workspaces.append(group);}
}
function selectWorkspace(folder){const text=workspaceDraftText({isHome:document.body.classList.contains('home'),text:$('message').value,homeDraft:drafts.get('new-task')});stashDraft();selection=folder;currentSource=null;current=null;history=[];uncertain=null;$('message').value=text;drafts.set('new-task',text);composerError('');render();$('message').focus();}
async function chooseWorkspace(path){if(uploadPending())throw new Error('附件处理尚未完成，请先处理当前上传');const folder=await api.chooseRecentWorkspace(path);if(folder)selectWorkspace(folder);}
function uploadPending(){return attachments().some(item=>['uploading','queued','unknown'].includes(item.status));}
function draftKey(){return current?.session.id??'new-task';}
function stashDraft(){drafts.set(draftKey(),$('message').value);}
async function refreshTasks(){const index=await api.listTasks();tasks=index.tasks;sourceErrors=index.source_errors??[];renderTasks();renderFilterMenu();if($('search-dialog').open)renderSearchResults();if(index.source_errors?.length){const summary=sourceErrorSummary(index.source_errors);const banner=$('error');banner.replaceChildren(el('div',summary.summary));const details=el('details',undefined,'source-errors');details.append(el('summary','查看错误详情'));for(const item of summary.details)details.append(el('p',`${item.count} 个来源：${item.message}`));banner.append(details);banner.hidden=false;}}
function renderConversation(){
 const list=$('conversation'),nearBottom=list.scrollHeight-list.scrollTop-list.clientHeight<100;
 document.body.classList.toggle('home',!current||(!current.messages.length&&!current.tools.length&&!current.approvals.length&&!current.clarifications.length));
 if(!current){list.replaceChildren();return;}
 const existing=new Map([...list.children].filter(n=>n.dataset.key).map(n=>[n.dataset.key,n]));const nodes=[];
 for(const message of current.messages){const key='message:'+message.id;let row=existing.get(key);if(!row){row=el('article',undefined,`message ${message.role} ${message.kind??''}`);row.dataset.key=key;row.dataset.messageId=message.id;row.append(el('div',messageRoleLabel(message),'role'),el('div','','body'));}row.className=`message ${message.role} ${message.kind??''} presentation-${messageKind(message)}`;const body=row.querySelector('.body');if(renderedSources.get(body)!==message.text){renderedSources.set(body,message.text);if(messageKind(message)==='assistant'){renderMarkdown(body,message.text,{onLink:url=>openMessageLink(url)});addCodeActions(body);}else body.textContent=message.text;}decorateMessage(row,message);nodes.push(row);}
 if(current.tools.length){let progress=existing.get('progress');if(!progress){progress=el('div','执行过程','progress-label');progress.dataset.key='progress';}const finalIndex=nodes.findLastIndex(n=>n.classList.contains('assistant'));const insert=finalIndex>=0?finalIndex:nodes.length;const rounds=groupExecutionRounds(current.tools);const placed=[];
 for(const round of rounds){const key='round:'+(round.modelStep??'legacy')+':'+round.tools[0].id;let host=existing.get(key);if(!host){host=el('div',undefined,'execution-round');host.dataset.key=key;host.append(el('div','','round-head'));}host.dataset.status=round.status;const head=host.querySelector('.round-head');const waitingInRound=round.tools.some(tool=>current.approvals.some(a=>a.call_id===tool.id));head.replaceChildren(el('span',waitingInRound?'等待审批':roundGlyph(round),'round-glyph'),el('span',waitingInRound?'等待审批':roundHeadline(round),'round-label'));
  const rows=[];for(const tool of round.tools){const toolKey='tool:'+tool.id;let row=existing.get(toolKey);if(!row){row=el('details',undefined,'tool');row.dataset.key=toolKey;row.dataset.toolId=tool.id;const summary=el('summary');summary.append(el('span','','tool-status'),el('span','','tool-label'),el('span','','tool-target'));row.append(summary);row.addEventListener('toggle',()=>{if(row.open)renderToolDetails(row,tool.id);});}if(browserActivity(tool)&&!row.querySelector('.browser-activity-link')){const link=el('button','查看活动','browser-activity-link');link.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();selectedBrowserActivity=tool.id;openWorkbench('overview');});row.querySelector('summary').append(link);}const status=contractToolStatus(tool.status);row.dataset.status=status;const waiting=current.approvals.some(a=>a.call_id===tool.id);row.querySelector('.tool-status').textContent=waiting?'等待审批':({ok:'✓ 成功',failed:'✕ 失败',running:'● 运行中',cancelled:'已停止',unknown:'结果未知'}[status]??'结果未知');row.querySelector('.tool-label').textContent=toolLabel(tool);row.querySelector('.tool-target').textContent=String(toolTarget(tool))||(status==='failed'?failureReason(tool.preview??'')??'':'');if(row.open)renderToolDetails(row,tool.id);rows.push(row);}
  while(head.nextSibling)head.nextSibling.remove();for(const row of rows)host.append(row);placed.push({host,anchor:round.tools[0].anchor});}
 nodes.splice(insert,0,progress);
 const anchors=new Map();for(const {host,anchor} of placed){const anchorNode=anchors.get(anchor)??nodes.find(n=>n.dataset.messageId===anchor);const position=anchorNode?nodes.indexOf(anchorNode)+1:nodes.indexOf(progress)+1;nodes.splice(position,0,host);anchors.set(anchor,host);}
 nodes.splice(nodes.indexOf(progress),1);nodes.splice(nodes.indexOf(placed[0].host),0,progress);}
 const keep=new Set(nodes);for(const child of [...list.children])if(!keep.has(child))child.remove();for(let i=0;i<nodes.length;i++)if(list.children[i]!==nodes[i])list.insertBefore(nodes[i],list.children[i]??null);
 if(nearBottom)list.scrollTop=list.scrollHeight;if(!$('conversation-search-bar').hidden)updateConversationSearch();
}
function decorateMessage(row,message){
 if(messageKind(message)==='notice'){row.querySelector('.role').textContent=messageRoleLabel(message);row.querySelector('.message-actions')?.remove();}
 if(message.role==='assistant'&&messageKind(message)!=='notice'){const role=row.querySelector('.role');if(!role.querySelector('.assistant-mark')){role.replaceChildren(el('span','C','assistant-mark'),el('span','CodeLeveler'),el('span','','message-stream-state'));}role.querySelector('.message-stream-state').textContent=current.streamingMessageId===message.id?'正在生成':'';}
 if(['user','assistant'].includes(messageKind(message))&&!row.querySelector('.message-actions')){const actions=el('div',undefined,'message-actions');const button=el('button','复制','message-copy');button.prepend(svgIcon('copy'));button.dataset.copyMessage=message.id;button.setAttribute('aria-label','复制消息');button.title='复制消息';button.addEventListener('click',()=>copyText(current?.messages.find(item=>item.id===message.id)?.text??'',button));actions.append(button);row.append(actions);}
}
function addCodeActions(body){for(const pre of body.querySelectorAll('pre')){const code=pre.querySelector('code');if(!code)continue;const button=el('button','复制代码','code-copy');button.prepend(svgIcon('copy'));button.dataset.copyCode='true';button.dataset.uiAction='true';button.setAttribute('aria-label','复制代码');button.type='button';button.addEventListener('click',()=>copyText(code.textContent,button));pre.append(button);}}
async function copyText(text,button){const label=button.getAttribute('aria-label')||button.textContent,contents=[...button.childNodes].map(node=>node.cloneNode(true));button.disabled=true;try{await api.copyText(text);button.textContent='已复制';button.setAttribute('aria-label','已复制');}catch(err){button.textContent='复制失败';button.title=err.message;button.setAttribute('aria-label','复制失败');}finally{button.disabled=false;setTimeout(()=>{button.replaceChildren(...contents);button.setAttribute('aria-label',label);},1500);}}
async function openMessageLink(url){try{browserData=await api.browserCommand({type:'new',url});openWorkbench('browser');renderBrowser();scheduleBrowserSurface();}catch(err){error(`无法打开链接：${err.message}`);}}
function renderToolDetails(row,id){const tool=current?.tools.find(t=>t.id===id);if(!tool)return;let detail=row.querySelector('.tool-details');if(!detail){detail=el('div',undefined,'tool-details');detail.append(el('pre','','tool-output'));if(browserActivity(tool)){const link=el('button','查看 Agent 浏览器活动 →');link.addEventListener('click',()=>{selectedBrowserActivity=id;openWorkbench('overview');});detail.append(link);}const raw=el('details',undefined,'diagnostics');raw.append(el('summary','技术详情'),el('pre'));detail.append(raw);row.append(detail);}const output=detail.querySelector('.tool-output');const text=displayPreview(tool)||'暂无输出';if(output.textContent!==text)output.textContent=text;const raw=detail.querySelector('.diagnostics pre');const args=typeof tool.arguments==='string'?tool.arguments:JSON.stringify(tool.arguments,null,2);raw.textContent=`工具：${tool.name}\n调用：${tool.id}\n参数：${args??''}\n${tool.exit_code!==undefined?'退出码：'+tool.exit_code:''}`;}
function scheduleConversation(){if(paintPending)return;paintPending=true;requestAnimationFrame(()=>{paintPending=false;renderConversation();});}
function renderHeader(){
  if(titleEditingSession&&titleEditingSession!==current?.session.id)cancelTitleEdit();
  $('title').textContent=current?.session.goal||'新建任务';
  $('title-edit').hidden=!current||!!titleEditingSession;
  $('task-history').hidden=!current;$('conversation-search-toggle').hidden=!current;if(!$('task-history-popup').hidden)renderTaskHistory();
  $('subtitle').textContent=current?.session.repository?basename(current.session.repository):selection?.path?basename(selection.path):'直接聊天，或打开工作区';
  $('workspace').textContent=current?.session.repository||selection?.path?workspaceLabel(current?.session.repository||selection?.path):'选择工作空间';
  $('clear-folder').hidden=!selection||!!current;
  $('folder').textContent='打开本地文件夹…';
  $('model-label').textContent=modelLabel(current?.session.model)||'选择模型';
  const permission=permissionLabel(current?.session.mode);$('permission-label').textContent=permission;$('home-permission').replaceChildren(svgIcon('shield'),el('span',permission));$('permission-description').textContent='当前会话 · '+permission;if(!$('permission-menu').hidden)renderPermissionOptions();
  renderAttachments();
  renderWorkbench();
  controls();
}
async function deliver(command,envelope=commandEnvelope(current.session.id,command)){
  const result=await api.deliver(envelope);
  if(!result.ok){if(['outcome_unknown','transport'].includes(result.error.kind)){uncertain=envelope;renderInteractions();}throw new Error(result.error.message);}
  if(uncertain?.command_id===envelope.command_id)uncertain=null;
  if(command.type==='submit_message'&&command.session_id===current?.session.id){if($('message').value.trim()===command.content)$('message').value='';const sent=new Set((command.attachments??[]).map(ref=>ref.id));attachmentDrafts.set(draftKey(),attachments().filter(item=>!sent.has(item.attachment?.id)));renderAttachments();}
  renderInteractions();return result;
}
function approvalButton(label,command,container){const button=el('button',label);button.disabled=loading;button.addEventListener('click',()=>action(async()=>{button.disabled=true;await deliver(command);await refreshMetadata();}));container.append(button);}
function renderInteractions(){
  const container=$('interactions');container.replaceChildren();
  if(uncertain){const row=el('div',undefined,'approval');row.append(el('h3','发送结果未知'),el('p','Runtime 可能已经接收此操作。重试将复用同一 command_id，避免重复执行。'));const retry=el('button','重试原操作');retry.dataset.retry='true';retry.addEventListener('click',()=>action(async()=>{await deliver(uncertain.command,uncertain);await refreshSnapshot();}));row.append(retry);container.append(row);}
  if(!current)return;
  for(const request of current.approvals){const row=el('div',undefined,'approval');row.append(el('h3','需要审批'),el('p',request.summary));if(request.command)row.append(el('p',request.command));for(const risk of request.risks??[])row.append(el('p',risk));const buttons=el('div',undefined,'actions');for(const decision of approvalDecisions(request))approvalButton({approve_once:'允许一次',approve_session:'本会话允许',approve_always:'始终允许',deny:'拒绝'}[decision],{type:'approval_decision',request_id:request.id,decision},buttons);row.append(buttons);container.append(row);}
  for(const request of current.clarifications){const row=el('div',undefined,'approval');row.append(el('h3','需要你的回答'),el('p',request.question));const questions=request.questions?.length?request.questions:[{question:request.question,options:request.options,kind:'single',allow_other:true}];const fields=[];
    for(const [index,question] of questions.entries()){
      const group=el('fieldset');group.append(el('legend',question.question));const picks=[];
      for(const option of question.options??[]){const label=el('label',undefined,'choice'),input=el('input');input.type=question.kind==='multi'?'checkbox':'radio';input.name=`clarification-${request.id}-${index}`;input.value=option;label.append(input,document.createTextNode(option));group.append(label);picks.push(input);}
      let input=null;if(question.kind==='text'||question.allow_other){input=el('input');input.type='text';input.setAttribute('aria-label',question.question);input.placeholder=question.kind==='text'?'输入回答':'其他回答';group.append(input);}
      row.append(group);fields.push({question,input,picks});
    }
    const send=el('button','提交回答');send.addEventListener('click',()=>action(async()=>{const answers=fields.map(({question,input,picks})=>clarificationAnswer(question,{picks:picks.filter(p=>p.checked).map(p=>p.value),text:input?.value??''}));const answer=request.questions?.length?fields.map(({question},i)=>`${question.header||question.question}: ${answers[i]}`).join('\n'):answers[0];await deliver({type:'answer_clarification',request_id:request.id,answer});await refreshMetadata();}));row.append(send);container.append(row);}
}
function render(){renderHeader();renderTasks();renderConversation();renderInteractions();renderCommands();if($('settings-dialog').open){if(settingsRenderedOwner!==settingsOwner())renderSettings();else updateSettingsSession();}}
async function loadHistory(){await deliver({type:'query_session_history',session_id:current.session.id,query_id:crypto.randomUUID()});}
async function refreshMetadata(){if(!current)return;const id=current.session.id,snapshot=await api.snapshot(id);if(current?.session.id!==id)return;current=applySessionMetadata(current,snapshot);renderHeader();}
async function refreshSnapshot(){if(!current)return;const id=current.session.id,snapshot=await api.snapshot(id);if(current?.session.id!==id)return;const diffError=current.diffError,diffQuery=current.diffQuery;current=projectSnapshot(snapshot,history);current.diffQuery=diffQuery;if(!snapshot.diff)current.diffError=diffError;render();}
async function createTask(){const result=await api.createTask(selection?.id??null);history=[];uncertain=null;currentSource=result.source_id??null;current=projectSnapshot(result.session);$('conversation').replaceChildren();render();await refreshTasks();$('message').focus();}
async function openTask(task){if(uploadPending())throw new Error('附件处理尚未完成，请先处理当前上传');closeConversationSearch();$('task-history-popup').hidden=true;stashDraft();const version=++opening;const result=await api.openTask({id:task.id,source_id:task.source_id});if(version!==opening)return;history=[];selection=null;uncertain=null;if(task.primary_workspace)foldedWorkspaces.delete(task.primary_workspace);currentSource=result.source_id??task.source_id;current=projectSnapshot(result.session);$('message').value=drafts.get(current.session.id)??'';$('conversation').replaceChildren();render();await loadHistory();$('conversation').scrollTop=$('conversation').scrollHeight;}
api.onEvent(frame=>{
 consumeSettingsEvent(frame);
  if(earlyUpload&&frame.session_id===earlyUpload.sessionId&&frame.event==='runtime'&&['attachment_added','attachment_processing_failed'].includes(frame.data.type)&&frame.data.command_id&&!earlyUpload.events.some(event=>event.command_id===frame.data.command_id)){if(earlyUpload.events.length<16)earlyUpload.events.push(frame.data);}
  if(frame.event==='error'){if(current?.diffQuery?.status==='pending'){current=expireDiffQuery(current,current.diffQuery.id,'Runtime 连接中断，变更结果未确认');clearTimeout(diffTimer);renderWorkbench();}error(frame.error.message);return;}
  if(frame.event==='handoff'){$('status').textContent=`Runtime: ${String(frame.data).slice(0,120)}`;return;}
  if(frame.session_id===current?.session.id&&frame.event==='runtime'&&['attachment_added','attachment_processing_failed'].includes(frame.data.type)){
    const previous=attachments(),next=applyUploadEvent(previous,frame.data);
    if(next!==previous){attachmentDrafts.set(draftKey(),next);uploadingKey=null;renderAttachments();controls();}
  }
  if(frame.session_id!==current?.session.id)return;
  if(frame.event==='snapshot'){const diffError=current.diffError,diffQuery=current.diffQuery;current=projectSnapshot(frame.data,history);current.diffQuery=diffQuery;if(!frame.data.diff)current.diffError=diffError;render();return;}
  if(frame.event!=='runtime')return;
  const event=frame.data;
  if(event.type==='session_history_loaded'){history=event.entries;renderTaskHistory();const restored=projectSnapshot(current.session,history);current={...current,tools:restored.tools,lastTerminal:restored.lastTerminal??current.lastTerminal};renderConversation();return;}
  if(event.type==='session_opened'){current=projectSnapshot(event.session,history);render();return;}
  if(event.type==='session_updated'){current=applySessionMetadata(current,event.session);renderHeader();renderTasks();return;}
  const pendingDiff=current.diffQuery?.status==='pending'&&event.query_id===current.diffQuery.id;current=applyEvent(current,event);if(['diff_updated','diff_failed'].includes(event.type)&&event.query_id===current.diffQuery?.id&&['confirmed','failed'].includes(current.diffQuery.status)){clearTimeout(diffTimer);if(pendingDiff&&['overview','changes'].includes(workbenchView))workbenchView='changes';}controls();scheduleConversation();if((['plan_updated','diff_updated','diff_failed'].includes(event.type)||(['tool_call_started','tool_call_completed'].includes(event.type)&&current.tools.some(t=>t.id===event.id&&browserActivity(t)))))renderWorkbench();
  if(['approval_requested','approval_resolved','clarification_requested','clarification_resolved'].includes(event.type))renderInteractions();
  if($('settings-dialog').open&&settingsSection==='session')updateSettingsSession();
  if(terminalEvents.has(event.type))action(async()=>{await refreshSnapshot();await loadHistory();await refreshTasks();});
  if(event.type==='turn_failed')error(event.failure?.message||event.error||'Runtime 执行失败');
});
$('new-task').addEventListener('click',()=>action(async()=>{stashDraft();$('message').value=drafts.get('new-task')??'';selection=null;current=null;history=[];await createTask();}));
$('folder').addEventListener('click',()=>action(async()=>{const folder=await api.chooseFolder();if(folder){selectWorkspace(folder);closeComposerMenus();}}));
$('clear-folder').addEventListener('click',()=>{selection=null;renderHeader();});
$('refresh').addEventListener('click',()=>action(async()=>{await refreshTasks();await refreshSnapshot();}));
$('cancel').addEventListener('click',()=>action(()=>deliver({type:'cancel_current_turn',session_id:current.session.id})));
$('composer').addEventListener('submit',event=>{event.preventDefault();const content=$('message').value.trim();const intent=slashIntent(content,commandCatalog());if(intent.kind==='action'){executeCommand(intent.id);return;}if(intent.kind==='blocked'){composerError(intent.reason);return;}const refs=attachments().filter(item=>item.status==='ready').map(item=>item.attachment);if((!content&&!refs.length)||loading||uncertain||attachments().some(item=>['uploading','queued','unknown'].includes(item.status)))return;const unsupported=attachmentSubmissionError(refs);if(unsupported){composerError(unsupported);return;}composerError('');action(async()=>{if(!current)await createTask();await deliver({type:'submit_message',session_id:current.session.id,content,attachments:refs});if($('message').value.trim()===content)$('message').value='';const sent=new Set(refs.map(ref=>ref.id));attachmentDrafts.set(draftKey(),attachments().filter(item=>!sent.has(item.attachment?.id)));renderAttachments();await refreshMetadata();},{onError:message=>composerError(message),clearGlobal:false});});
$('message').addEventListener('input',()=>{commandDismissed=false;composerError('');controls();renderCommands();});
$('message').addEventListener('keydown',event=>{if(commandKeys(event))return;if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing&&event.keyCode!==229){event.preventDefault();$('composer').requestSubmit();}});

function attachments(){return attachmentDrafts.get(draftKey())??[];}
function composerError(message){$('composer-error').textContent=message;$('composer-error').hidden=!message;}
function updateUploads(update){attachmentDrafts.set(draftKey(),uploadDraft(attachments(),update));renderAttachments();controls();}
function renderAttachments(){const list=$('attachment-chips');list.replaceChildren();for(const item of attachments()){const row=el('div',undefined,'attachment-chip');row.dataset.attachmentStatus=item.status;const status={uploading:'选择 / 上传中…',queued:'正在处理…',unknown:'上传结果未知',failed:'上传失败',ready:item.attachment?.kind==='image'?'已上传':'已上传 · 当前不能发送给模型'}[item.status];const problem=item.error?.message?attachmentErrorPresentation(item.error.message):null;row.append(el('span',item.attachment?.name??'附件'),el('small',item.status==='unknown'?'上传结果未确认，可重试原上传或放弃等待。':problem?.label??status));if(problem){const details=el('details',undefined,'attachment-error-details');details.append(el('summary','技术详情'),el('pre',problem.detail));row.append(details);}if(item.status==='unknown'&&item.import_id){const discard=el('button','放弃等待');discard.type='button';discard.title='只放弃本地等待，不会取消 Runtime 上传；文件可能仍会保存。';discard.dataset.discardUpload=item.import_id;discard.addEventListener('click',()=>action(async()=>{const id=current.session.id,ownerKey=draftKey(),result=await api.discardUpload(id,item.import_id);if(!result?.ok)throw new Error('未能放弃本地等待');attachmentDrafts.set(ownerKey,uploadDraft(attachmentDrafts.get(ownerKey)??[],{remove:item.key}));if(current?.session.id===id){renderAttachments();controls();}},{onError:message=>composerError(message),clearGlobal:false}));row.append(discard);}if(['unknown','failed'].includes(item.status)){const retry=el('button',item.status==='unknown'?'重试原上传':'重新选择');retry.type='button';retry.addEventListener('click',()=>uploadAttachment(item));row.append(retry);}if(!['queued','unknown','uploading'].includes(item.status)){const remove=el('button','×');remove.type='button';remove.setAttribute('aria-label','移除附件草稿');remove.addEventListener('click',()=>updateUploads({remove:item.attachment?.id??item.key}));row.append(remove);}list.append(row);}}
async function uploadAttachment(previous=null){composerError('');await action(async()=>{if(!current)await createTask();uploadingKey=previous?.key??crypto.randomUUID();const key=uploadingKey,sessionId=current.session.id;const receiving={sessionId,key,events:[]};earlyUpload=receiving;updateUploads({status:'uploading',key,import_id:previous?.status==='unknown'?previous.import_id:undefined});try{const result=await api.chooseAttachment(sessionId);const draft=attachmentDrafts.get(sessionId)??[];const next=result.status==='cancelled'?uploadDraft(draft,{remove:key}):reconcileUploadReply(draft,{...result,key},receiving.events);attachmentDrafts.set(sessionId,next);if(current?.session.id===sessionId){renderAttachments();controls();}if(!next.some(item=>item.key===key&&['queued','unknown'].includes(item.status)))uploadingKey=null;}catch(err){attachmentDrafts.set(sessionId,uploadDraft(attachmentDrafts.get(sessionId)??[],{status:'failed',key,error:{message:err.message}}));if(current?.session.id===sessionId){renderAttachments();controls();}uploadingKey=null;}finally{if(earlyUpload===receiving)earlyUpload=null;}},{onError:message=>composerError(message),clearGlobal:false});}
$('attachment-add').addEventListener('click',()=>uploadAttachment());
function closeComposerMenus(){for(const id of ['workspace-menu','model-menu','permission-menu'])$(id).hidden=true;scheduleBrowserSurface();}
function showComposerMenu(id){const wasOpen=!$(id).hidden;closeComposerMenus();$(id).hidden=wasOpen;if(!wasOpen)$(id).querySelector('input,button')?.focus();scheduleBrowserSurface();}
function renderWorkspaceOptions(){const list=$('workspace-options');list.replaceChildren();const query=$('workspace-query').value.toLocaleLowerCase().trim();const spaces=recentWorkspaces(tasks).filter(space=>space.path.toLocaleLowerCase().includes(query));for(const space of spaces){const button=el('button',space.name);button.title=space.path;button.type='button';button.append(el('small',space.path));button.addEventListener('click',()=>action(async()=>{await chooseWorkspace(space.path);closeComposerMenus();}));list.append(button);}if(!spaces.length)list.append(el('p','没有匹配的最近工作空间','empty'));}
$('workspace-picker').addEventListener('click',()=>{renderWorkspaceOptions();showComposerMenu('workspace-menu');});
$('workspace-query').addEventListener('input',renderWorkspaceOptions);
$('model-picker').addEventListener('click',()=>action(async()=>{if(!current)await createTask();const list=$('model-options');list.replaceChildren();$('model-error').hidden=true;for(const model of current.session.available_models??[]){const button=el('button',modelLabel(model)+(current.session.model?.provider===model.provider&&current.session.model?.model===model.model?' ✓':''));button.type='button';button.title=model.provider;button.addEventListener('click',()=>action(async()=>{if(uploadPending())throw new Error('附件处理尚未完成，暂不能切换模型');await deliver({type:'select_model',session_id:current.session.id,model});await refreshMetadata();if(current.session.model?.provider!==model.provider||current.session.model?.model!==model.model)throw new Error('Runtime 尚未确认模型切换');closeComposerMenus();},{onError:message=>{$('model-error').textContent=message;$('model-error').hidden=false;},clearGlobal:false}));list.append(button);}if(!list.children.length)list.append(el('p','Runtime 没有提供可用模型','empty'));showComposerMenu('model-menu');}));
function renderPermissionOptions(){const list=$('permission-options');list.replaceChildren();for(const [mode,label,description] of [['full_access','全量访问 · Full','已实现能力完全放开，不进行权限审批。'],['assisted','自动权限 · Auto','普通开发动作默认允许；危险或敏感动作先审批。'],['request_approval','受限权限 · Restricted','按资源边界执行，超出边界时审批或明确不支持。']]){const button=el('button',label+(current?.session.mode===mode?' ✓':''));button.type='button';button.dataset.permissionMode=mode;button.setAttribute('aria-pressed',String(current?.session.mode===mode));button.append(el('small',description));button.addEventListener('click',()=>action(async()=>{if(uploadPending()||uncertain)throw new Error('请先处理当前未完成的操作');const id=current.session.id;await deliver(permissionCommand(id,mode));await refreshMetadata();if(!permissionConfirmed(current,id,mode))throw new Error('Runtime 尚未确认权限模式切换');$('permission-error').hidden=true;closeComposerMenus();},{onError:message=>{$('permission-error').textContent=message;$('permission-error').hidden=false;},clearGlobal:false}));button.disabled=loading||!!uncertain||uploadPending();list.append(button);}}
function openPermissionMenu(){return action(async()=>{if(!current)await createTask();$('permission-error').hidden=true;renderPermissionOptions();showComposerMenu('permission-menu');}).then(()=>{if(!$('permission-menu').hidden)$('permission-options').querySelector('button:not(:disabled)')?.focus();});}
$('permission').addEventListener('click',openPermissionMenu);
$('home-permission').addEventListener('click',openPermissionMenu);
document.addEventListener('keydown',event=>{const menu=['workspace-menu','model-menu','permission-menu'].map(id=>$(id)).find(node=>!node.hidden);if(!menu||event.isComposing)return;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();const origin=menu.id==='model-menu'?'model-picker':menu.id==='workspace-menu'?'workspace-picker':document.body.classList.contains('home')?'home-permission':'permission';closeComposerMenus();$(origin).focus();}else if(['ArrowUp','ArrowDown'].includes(event.key)){const buttons=[...menu.querySelectorAll('button:not(:disabled)')];if(!buttons.length)return;event.preventDefault();const index=buttons.indexOf(document.activeElement);buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length].focus();}});
document.addEventListener('pointerdown',event=>{if(!event.target.closest('#composer-area'))closeComposerMenus();});

let selectedBrowserActivity=null,workbenchOpen=true,workbenchView='overview',workbenchWidth=360,workbenchDock=true,workbenchExpanded=false,workbenchFocus=null,artifactsOpen=false,browserData={tabs:[],selectedId:null},browserFrame=false,browserURLDirty=false,browserCommandError=null;
function saved(key,fallback){try{return localStorage.getItem(key)??fallback;}catch{return fallback;}}
function save(key,value){try{localStorage.setItem(key,String(value));}catch{/* UI preferences are optional on restricted storage. */}}
function setTheme(value){if($('settings-theme'))$('settings-theme').value=value;save('theme',value);$('theme').value=value;document.documentElement.dataset.theme=value==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;}
function layoutWorkbench(){
 const layout=workbenchLayout({viewport:innerWidth,sidebarWidth:document.body.classList.contains('sidebar-collapsed')?56:260,width:workbenchWidth,docked:workbenchDock,expanded:workbenchExpanded});
 document.body.classList.toggle('workbench-overlay',layout.overlay);document.body.classList.toggle('workbench-expanded',workbenchExpanded);$('workbench-backdrop').hidden=!workbenchOpen||!layout.overlay;$('workbench').hidden=!workbenchOpen;
 $('overview-pane').hidden=workbenchView==='browser'&&!layout.showContext;$('workbench').classList.toggle('with-context',workbenchView==='browser'&&layout.showContext);
 document.documentElement.style.setProperty('--workbench-width',`${layout.width}px`);$('workbench-toggle').setAttribute('aria-expanded',String(workbenchOpen));$('workbench-expand').setAttribute('aria-pressed',String(workbenchExpanded));$('workbench-expand').setAttribute('aria-label',workbenchExpanded?'恢复工作台':'展开工作台');$('workbench-expand').title=workbenchExpanded?'恢复工作台':'展开工作台';$('workbench-expand').replaceChildren(svgIcon(workbenchExpanded?'restore':'expand'));$('resize-handle').hidden=workbenchExpanded;$('resize-handle').setAttribute('aria-valuenow',String(layout.width));scheduleBrowserSurface();
}
function openWorkbench(view=workbenchView){const wasOpen=workbenchOpen,focusInside=$('workbench').contains(document.activeElement);if(!wasOpen)workbenchFocus=document.activeElement;workbenchOpen=true;workbenchView=view;renderWorkbench();layoutWorkbench();if(focusWorkbenchEntry({wasOpen,focusInside,overlay:document.body.classList.contains('workbench-overlay')}))$('workbench-overview').focus();}
function closeWorkbench(){workbenchExpanded=false;workbenchOpen=false;layoutWorkbench();if(workbenchFocus?.isConnected&&workbenchFocus.getClientRects().length)workbenchFocus.focus();else $('workbench-toggle').focus();}
function toggleWorkbenchExpansion(){workbenchExpanded=!workbenchExpanded;layoutWorkbench();$('workbench-expand').focus();}
function renderWorkbench(){
 const select=$('workbench-view'),hasWorkspace=!!current?.session.repository,views=availableWorkbenchViews({...current,hasWorkspace});const hasPlan=views.includes('plan'),hasDiff=views.includes('changes');
 const actual=[...select.options].map(option=>option.value);if(actual.join(',')!==views.join(',')){select.replaceChildren();for(const view of views){const option=el('option',({overview:'概览',plan:'计划',changes:'变更'})[view]);option.value=view;select.append(option);}}
 if(workbenchView!=='browser'&&!views.includes(workbenchView))workbenchView='overview';$('browser-new').hidden=!api.browserState;
 select.value=workbenchView==='browser'?'overview':workbenchView;const browser=workbenchView==='browser';$('workbench-overview').setAttribute('aria-selected',String(!browser));$('browser').hidden=!browser;renderBrowser();
 const container=$('workbench-content');container.replaceChildren();if(current?.diffQuery?.status==='pending'){const notice=el('p','正在读取工作区变更…已有内容为此前确认的结果。','diff-query-status');notice.setAttribute('role','status');container.append(notice);}else if(current?.diffQuery?.status==='unknown'){const notice=el('p',current.diffQuery.error||'变更结果未确认，请重新读取。','diff-query-status warning');notice.setAttribute('role','alert');container.append(notice);}
 if(workbenchView==='changes'&&current?.diffError){const section=el('section',undefined,'workbench-section');section.append(el('h3','无法读取工作区变更'));const technical=el('details',undefined,'diagnostics');technical.append(el('summary','技术详情'),el('pre',current.diffError));section.append(technical);const retry=el('button','重新读取变更');retry.id='diff-retry';retry.disabled=loading||!!uncertain||current.diffQuery?.status==='pending';retry.addEventListener('click',requestDiff);section.append(retry);container.append(section);}
 else if(workbenchView==='changes'){const section=el('section',undefined,'workbench-section');section.append(el('h3','工作区变更'));const refresh=el('button','重新读取');refresh.id='diff-refresh';refresh.disabled=loading||!!uncertain||current.diffQuery?.status==='pending';refresh.addEventListener('click',requestDiff);section.append(refresh);for(const file of current.diff.files){const row=el('details',undefined,'diagnostics diff-file');const summary=el('summary');const name=el('span',file.path,'diff-path');name.title=file.path;summary.append(name,el('span',`+${file.added} −${file.removed}`,'diff-counts'));row.append(summary);if(file.patch){row.addEventListener('toggle',()=>{if(row.open&&!row.querySelector('pre'))row.append(el('pre',file.patch,'diff-patch'));});}else row.append(el('p','当前快照未包含补丁正文'));section.append(row);}if(!current.diff.files.length)section.append(el('p','工作区没有变更'));container.append(section);}
 else if(workbenchView==='plan'){const section=el('section',undefined,'workbench-section');section.append(el('h3','执行计划'));for(const step of current.plan.steps){const row=el('div',undefined,'plan-step');row.dataset.planStatus=step.status;const text=el('div',undefined,'plan-step-content');text.append(el('p',step.description),el('small',planStepLabel(step.status),'plan-step-status'));row.append(el('span',({pending:'○',running:'●',done:'✓',failed:'✕',skipped:'–'}[step.status]??'?')),text);section.append(row);}container.append(section);}
 else {if(current?.session.repository){const section=el('section',undefined,'workbench-section');section.append(el('h3','工作区'),el('p',basename(current.session.repository)));const detail=el('details',undefined,'diagnostics');detail.append(el('summary','技术详情'),el('pre',current.session.repository));section.append(detail);container.append(section);}if(hasPlan){const section=el('section',undefined,'workbench-section');section.append(el('h3','计划'),el('p',`${current.plan.steps.filter(s=>s.status==='done').length} / ${current.plan.steps.length} 步骤已完成`));const button=el('button','查看计划 →');button.addEventListener('click',()=>openWorkbench('plan'));section.append(button);container.append(section);}if(hasWorkspace){const section=el('section',undefined,'workbench-section');section.append(el('h3','变更'));if(hasDiff)section.append(el('p',current.diffError?'无法读取变更':`${current.diff.files.length} 个文件`));const button=el('button',hasDiff?'查看变更 →':'读取工作区变更');button.id='overview-changes';button.disabled=loading||!!uncertain||current.diffQuery?.status==='pending';button.addEventListener('click',hasDiff?()=>openWorkbench('changes'):requestDiff);section.append(button);if(current.diffQuery?.status==='unknown'){const retry=el('button','重新读取');retry.id='diff-retry';retry.addEventListener('click',requestDiff);section.append(retry);}container.append(section);}const activities=(current?.tools??[]).map(browserActivity).filter(Boolean);if(activities.length){const section=el('section',undefined,'workbench-section agent-browser-activity');section.append(el('h3','Agent 浏览器活动'),el('p','工具调用时报告 · 当前网页未同步，未绑定手动浏览器'));for(const activity of activities){const detail=el('details',undefined,'diagnostics');detail.dataset.activityId=activity.id;detail.open=activity.id===selectedBrowserActivity;detail.append(el('summary',`${activity.label} · ${labels[activity.status]??activity.status} ${activity.target}`),el('pre',activity.preview||'暂无工具输出'));section.append(detail);}container.append(section);}if(browserData.tabs.length){const section=el('section',undefined,'workbench-section');section.append(el('h3','手动浏览器'),el('p',`${browserData.tabs.length} 个标签 · 未绑定 Agent`));const button=el('button','打开浏览器 →');button.addEventListener('click',()=>openWorkbench('browser'));section.append(button);container.append(section);}}
 const artifacts=el('details',undefined,'artifacts-group');artifacts.id='artifacts-group';artifacts.open=artifactsOpen;artifacts.addEventListener('toggle',()=>{artifactsOpen=artifacts.open;});artifacts.append(el('summary','产物'),el('p','暂无可展示内容'));container.append(artifacts);layoutWorkbench();
}
async function requestDiff(){if(!current?.session.repository||current.diffQuery?.status==='pending'||loading||uncertain)return;const sessionId=current.session.id,queryId=crypto.randomUUID();clearTimeout(diffTimer);current=beginDiffQuery(current,queryId);renderWorkbench();diffTimer=setTimeout(()=>{if(current?.session.id!==sessionId)return;current=expireDiffQuery(current,queryId,'15 秒内未收到读取结果，变更结果未确认。可以重新读取。');renderWorkbench();},15000);await action(async()=>{await deliver({type:'request_diff',session_id:sessionId,query_id:queryId});},{onError:message=>{if(current?.session.id!==sessionId)return;current=expireDiffQuery(current,queryId,'无法确认读取结果：'+message);clearTimeout(diffTimer);renderWorkbench();},clearGlobal:false});renderWorkbench();}
async function browserCommand(type,extra={}){browserCommandError=null;if(['select','back','forward','reload','new','close'].includes(type))browserURLDirty=false;try{browserData=await api.browserCommand({type,id:browserData.selectedId??undefined,...extra});renderBrowser();if(!browserData.tabs.length&&workbenchView==='browser')workbenchView='overview';renderWorkbench();return true;}catch(err){browserCommandError={tabId:browserData.selectedId,address:['navigate','new'].includes(type),message:['navigate','new'].includes(type)?'无法打开此地址，请使用不含用户名或密码的 HTTP / HTTPS 地址。':'浏览器操作未完成。',detail:err.message};if(['navigate','new'].includes(type)&&extra.url)browserURLDirty=true;renderBrowser();if(workbenchView!=='browser')error(browserCommandError.message);return false;}finally{scheduleBrowserSurface();}}
function renderBrowser(){
 const selected=browserData.tabs.find(t=>t.id===browserData.selectedId);const focusedTab=document.activeElement?.dataset?.tabId;const tabs=$('browser-tabs');tabs.replaceChildren();for(const tab of browserData.tabs){const group=el('div',undefined,'browser-tab'+(workbenchView==='browser'&&tab.id===browserData.selectedId?' selected':''));const chrome=browserChrome(tab);const button=el('button',`${chrome.loading?'◌ ':''}${chrome.title}`);button.title=chrome.title;button.setAttribute('aria-busy',String(chrome.loading));button.setAttribute('role','tab');button.setAttribute('aria-selected',String(workbenchView==='browser'&&tab.id===browserData.selectedId));button.dataset.tabId=tab.id;button.addEventListener('click',async()=>{if(await browserCommand('select',{id:tab.id}))openWorkbench('browser');});const close=el('button');close.append(svgIcon('close'));close.setAttribute('aria-label','关闭标签');close.title='关闭 '+chrome.title;close.dataset.closeTab=tab.id;close.addEventListener('click',async()=>{if(await browserCommand('close',{id:tab.id})){const selected=[...$('browser-tabs').querySelectorAll('[data-tab-id]')].find(button=>button.dataset.tabId===browserData.selectedId);(selected??$('workbench-overview')).focus();}});group.append(button,close);tabs.append(group);}
 if(focusedTab)[...tabs.querySelectorAll('[data-tab-id]')].find(tab=>tab.dataset.tabId===focusedTab)?.focus();
 if(!browserURLDirty)$('browser-url').value=selected?.url==='about:blank'?'':selected?.url??'';
 const chrome=browserChrome(selected??null);$('browser-back').disabled=!chrome.back;$('browser-forward').disabled=!chrome.forward;$('browser-reload').disabled=!chrome.reload;$('browser-external').disabled=!chrome.external;$('browser-status').hidden=!chrome.loading;$('browser-status').textContent=chrome.loading?'正在打开网页…':'';$('browser').setAttribute('aria-busy',String(chrome.loading));
 const commandError=browserCommandError?.tabId===browserData.selectedId?browserCommandError:null;const browserError=selected?.error||commandError?.detail;$('browser-error').hidden=!browserError;$('browser-error').replaceChildren();if(browserError){$('browser-error').append(el('strong',commandError?.message||'网页无法打开'));const details=el('details',undefined,'diagnostics');details.append(el('summary','技术详情'),el('pre',browserError));$('browser-error').append(details);const retry=el('button',commandError?(commandError.address?'修改地址':'关闭提示'):'重试');retry.addEventListener('click',commandError?()=>{if(commandError.address){$('browser-url').focus();$('browser-url').select();}else{browserCommandError=null;renderBrowser();scheduleBrowserSurface();}}:()=>browserCommand('reload'));$('browser-error').append(retry);}
 const empty=$('browser-surface').querySelector('.browser-empty');empty.hidden=!!selected&&selected.url!=='about:blank'&&!selected.error;empty.querySelector('h3').textContent=selected?.error?'网页未能打开':'打开一个网页';empty.querySelector('p').textContent=selected?.error?'可使用上方重试，或输入其他地址。':'在上方输入 HTTP / HTTPS 地址，或新建标签。';
}
function scheduleBrowserSurface(){if(!api.browserSurface||browserFrame)return;browserFrame=true;requestAnimationFrame(()=>{browserFrame=false;const bounds=browserSurfaceBounds($('browser-surface').getBoundingClientRect(),{width:innerWidth,height:innerHeight});const selected=browserData.tabs.find(t=>t.id===browserData.selectedId);const visible=['workspace-menu','model-menu','permission-menu','command-menu'].every(id=>$(id).hidden)&&!$('search-dialog').open&&!$('archive-dialog').open&&!$('settings-dialog').open&&workbenchOpen&&workbenchView==='browser'&&!!selected&&!selected.error&&selected.url!=='about:blank'&&!!bounds;const safeBounds=visible?bounds:{x:0,y:0,width:1,height:1};api.browserSurface({visible,bounds:safeBounds}).catch(err=>error(err.message));});}
function renderFilterMenu(){
 const status=$('status-filters'),time=$('time-filters');status.replaceChildren();time.replaceChildren();
 const statuses=['all',...new Set(tasks.map(task=>task.status).filter(Boolean))];if(!statuses.includes(taskFilter.status))taskFilter.status='all';
 for(const [group,values] of [[status,statuses.map(value=>[value,value==='all'?'全部状态':labels[value]??value])],[time,[['all','全部时间'],['today','今天'],['7d','最近 7 天'],['30d','最近 30 天']]]])for(const [value,label] of values){const row=el('label',undefined,'filter-choice');const input=el('input');const key=group===status?'status':'time';input.type='radio';input.name='filter-'+key;input.value=value;input.checked=taskFilter[key]===value;input.addEventListener('change',()=>{taskFilter[key]=value;$('task-filter').setAttribute('aria-pressed',String(taskFilter.status!=='all'||taskFilter.time!=='all'));renderTasks();});row.append(input,document.createTextNode(label));group.append(row);}
 $('task-filter').setAttribute('aria-pressed',String(taskFilter.status!=='all'||taskFilter.time!=='all'));
}
function openSearch(){searchFocus=document.activeElement;searchSelected=0;$('task-search').value='';renderSearchResults();$('search-dialog').showModal();$('task-search').focus();scheduleBrowserSurface();}
function closeSearch(){$('search-dialog').close();$('task-search').removeAttribute('aria-activedescendant');restoreFocus(searchFocus);scheduleBrowserSurface();}
function renderSearchResults(){searchResults=taskSearchResults(tasks,$('task-search').value);searchSelected=Math.max(0,Math.min(searchSelected,searchResults.length-1));const list=$('search-results');list.replaceChildren();let group='';for(const [index,result] of searchResults.entries()){if(result.type!==group){group=result.type;list.append(el('div',group==='task'?'任务':'工作空间','search-group'));}const button=el('button',undefined,'search-result');button.id='search-result-'+index;button.setAttribute('role','option');button.setAttribute('aria-selected',String(index===searchSelected));button.dataset.resultIndex=String(index);if(result.type==='task'){button.append(el('span','◯','search-result-icon'),el('strong',result.task.title||'未命名任务'),el('small',result.task.primary_workspace?workspaceLabel(result.task.primary_workspace):'No Workspace'));}else button.append(el('span','▱','search-result-icon'),el('strong',result.workspace.name),el('small','工作空间'));button.addEventListener('focus',()=>{searchSelected=index;updateSearchSelection();});button.addEventListener('click',()=>chooseSearchResult(index));list.append(button);}if(!searchResults.length)list.append(el('p','没有匹配的任务或工作空间','empty'));updateSearchSelection();}
function updateSearchSelection(){const input=$('task-search');const selected=$('search-result-'+searchSelected);if(selected)input.setAttribute('aria-activedescendant',selected.id);else input.removeAttribute('aria-activedescendant');for(const button of $('search-results').querySelectorAll('[data-result-index]'))button.setAttribute('aria-selected',String(Number(button.dataset.resultIndex)===searchSelected));selected?.scrollIntoView({block:'nearest'});}
function chooseSearchResult(index){const result=searchResults[index];if(!result)return;closeSearch();action(()=>result.type==='task'?openTask(result.task):chooseWorkspace(result.workspace.path));}
function searchKeys(event){if(event.isComposing)return;if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeSearch();}else if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();searchSelected=Math.max(0,Math.min(searchResults.length-1,searchSelected+(event.key==='ArrowDown'?1:-1)));updateSearchSelection();}else if(event.key==='Enter'&&event.target!==$('search-close')){event.preventDefault();chooseSearchResult(searchSelected);}}
function startTitleEdit(){if(!current||loading||uncertain)return;closeTaskMenu();titleEditingSession=current.session.id;$('title').hidden=true;$('title-edit').hidden=true;$('title-form').hidden=false;$('title-input').value=current.session.goal??'';$('rename-error').hidden=true;$('title-input').focus();$('title-input').select();}
function cancelTitleEdit(){titleEditingSession=null;$('title-form').hidden=true;$('title').hidden=false;$('rename-error').hidden=true;$('title-edit').hidden=!current;}
function renameError(message){$('rename-error').textContent=message;$('rename-error').hidden=!message;}
async function submitTitle(){
 if(loading||uncertain)return;let command;
 try{command=renameCommand(titleEditingSession,$('title-input').value);if(current?.session.id!==titleEditingSession)throw new Error('任务已切换，请重新编辑标题');}catch(err){renameError(err.message);return;}
 renameError('');await action(async()=>{await deliver(command);await refreshMetadata();if(current.session.goal!==command.name)throw new Error('Runtime 尚未返回更新后的标题，请刷新任务记录');cancelTitleEdit();await refreshTasks();restoreFocus($('title-edit'));},{onError:renameError,clearGlobal:false});
}
async function openTaskMenu(task,anchor,point){if(loading||uncertain||uploadPending())return;closeTaskMenu();if(current?.session.id!==task.id)await action(()=>openTask(task));if(current?.session.id!==task.id)return;taskMenuSession=task.id;const actualAnchor=document.querySelector('.task.selected')?.parentElement.querySelector('.task-more')??anchor;const rect=actualAnchor.getBoundingClientRect();const menu=$('task-menu');menu.hidden=false;const {width,height}=menu.getBoundingClientRect();menu.style.left=`${Math.max(8,Math.min(innerWidth-width-8,point?.x??rect.right-8))}px`;menu.style.top=`${Math.max(8,Math.min(innerHeight-height-8,point?.y??rect.bottom))}px`;$('task-menu-rename').focus();}
function closeTaskMenu(){taskMenuSession=null;$('task-menu').hidden=true;}
function requestArchive(){if(loading||uncertain||!current||current.session.id!==taskMenuSession)return;archiveTarget=taskMenuSession;closeTaskMenu();$('archive-error').hidden=true;$('archive-dialog').showModal();$('archive-cancel').focus();scheduleBrowserSurface();}
function closeArchive(){$('archive-dialog').close();archiveTarget=null;restoreFocus(document.querySelector('.task.selected'));scheduleBrowserSurface();}
async function archiveTask(){if(loading||uncertain||!current||current.session.id!==archiveTarget)return;const id=archiveTarget;await action(async()=>{try{await deliver({type:'archive_session',session_id:id});await refreshTasks();if(tasks.some(task=>task.id===id))throw new Error('Runtime 尚未确认任务归档，请刷新列表');stashDraft();current=null;history=[];selection=null;closeArchive();cancelTitleEdit();render();$('new-task').focus();}catch(err){$('archive-error').textContent=err.message;$('archive-error').hidden=false;throw err;}});}
function renderTaskHistory(){const container=$('task-history-content');container.replaceChildren();const questions=historyQuestions(current?.messages??[]);if(!questions.length)container.append(el('p','当前任务还没有提问','empty'));for(const question of questions){const button=el('button',question.text,'history-prompt');button.addEventListener('click',()=>{const row=[...$('conversation').querySelectorAll('.message')].find(node=>node.dataset.messageId===question.id);row?.scrollIntoView({block:'center'});$('task-history-popup').hidden=true;restoreFocus($('task-history'));});container.append(button);}}
function openConversationSearch(){if(!current)return;$('conversation-search-bar').hidden=false;$('conversation-query').focus();$('conversation-query').select();updateConversationSearch(true);}
function closeConversationSearch(){$('conversation-search-bar').hidden=true;window.CSS.highlights?.delete('conversation-search');window.CSS.highlights?.delete('conversation-current');}
function bodyTextNodes(body){const walk=document.createTreeWalker(body,window.NodeFilter.SHOW_TEXT),nodes=[];let node;while((node=walk.nextNode()))if(!node.parentElement.closest('[data-ui-action]'))nodes.push(node);return nodes;}
function textRange(body,start,end){const textNodes=bodyTextNodes(body);let offset=0,first=null,last=null;for(const node of textNodes){const length=node.textContent.length;if(first===null&&start<offset+length)first={node,offset:start-offset};if(end<=offset+length){last={node,offset:end-offset};break;}offset+=length;}if(!first||!last)return null;const range=document.createRange();range.setStart(first.node,first.offset);range.setEnd(last.node,last.offset);return range;}
function updateConversationSearch(scroll=false){const rows=[...$('conversation').querySelectorAll('.message')];findMatches=conversationMatches(rows.map(row=>({id:row.dataset.messageId,text:bodyTextNodes(row.querySelector('.body')).map(node=>node.textContent).join('')})),$('conversation-query').value);findSelected=Math.max(0,Math.min(findSelected,findMatches.length-1));$('conversation-match-count').textContent=`${findMatches.length?findSelected+1:0} / ${findMatches.length}`;for(const id of ['conversation-find-prev','conversation-find-next'])$(id).disabled=!findMatches.length;const ranges=[],selected=[];for(const [index,match] of findMatches.entries()){const row=rows.find(node=>node.dataset.messageId===match.id);const range=textRange(row.querySelector('.body'),match.start,match.end);if(range){ranges.push(range);if(index===findSelected)selected.push(range);}if(scroll&&index===findSelected)row.scrollIntoView({block:'center'});}if(window.CSS.highlights&&window.Highlight){window.CSS.highlights.set('conversation-search',new window.Highlight(...ranges));window.CSS.highlights.set('conversation-current',new window.Highlight(...selected));}}
function moveConversationSearch(direction){if(!findMatches.length)return;findSelected=(findSelected+direction+findMatches.length)%findMatches.length;updateConversationSearch(true);}
function initProductUI(){
 for(const [id,name] of Object.entries({'sidebar-toggle':'sidebar','search-toggle':'search','task-filter':'filter','refresh':'reload','space-add':'plus','title-edit':'edit','title-save':'check','title-cancel':'close','conversation-search-toggle':'search','task-history':'history','workbench-toggle':'workbench','conversation-find-prev':'up','conversation-find-next':'down','conversation-search-close':'close','attachment-add':'plus','send':'up','clear-folder':'close','search-close':'close','task-history-close':'close','workbench-overview':'menu','browser-new':'plus','workbench-close':'collapse','browser-back':'back','browser-forward':'forward','browser-reload':'reload','browser-external':'external'}))setIcon(id,name);
 for(const node of document.querySelectorAll('[data-icon]'))node.replaceChildren(svgIcon(node.dataset.icon));

 $('conversation-search-toggle').addEventListener('click',openConversationSearch);$('conversation-search-close').addEventListener('click',()=>{closeConversationSearch();restoreFocus($('conversation-search-toggle'));});$('conversation-query').addEventListener('input',()=>{findSelected=0;updateConversationSearch(true);});$('conversation-query').addEventListener('keydown',event=>{if(event.isComposing)return;if(event.key==='Enter'){event.preventDefault();moveConversationSearch(event.shiftKey?-1:1);}if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeConversationSearch();restoreFocus($('conversation-search-toggle'));}});$('conversation-find-prev').addEventListener('click',()=>moveConversationSearch(-1));$('conversation-find-next').addEventListener('click',()=>moveConversationSearch(1));
 document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='f'&&current){event.preventDefault();openConversationSearch();}});

 $('title-edit').addEventListener('click',startTitleEdit);$('title-cancel').addEventListener('click',()=>{cancelTitleEdit();restoreFocus($('title-edit'));});$('title-form').addEventListener('submit',event=>{event.preventDefault();if(!titleComposing)submitTitle();});$('title-input').addEventListener('compositionstart',()=>{titleComposing=true;});$('title-input').addEventListener('compositionend',()=>{titleComposing=false;});$('title-input').addEventListener('keydown',event=>{if(event.key==='Escape'&&!event.isComposing){event.preventDefault();event.stopPropagation();cancelTitleEdit();restoreFocus($('title-edit'));}});
 $('task-menu').addEventListener('keydown',event=>{if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const buttons=[...$('task-menu').querySelectorAll('button')];const at=buttons.indexOf(document.activeElement);buttons[(at+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length].focus();}});
 $('task-menu-rename').addEventListener('click',()=>{if(current?.session.id===taskMenuSession)startTitleEdit();});$('task-menu-archive').addEventListener('click',requestArchive);$('archive-confirm').addEventListener('click',archiveTask);$('archive-cancel').addEventListener('click',closeArchive);$('archive-dialog').addEventListener('keydown',event=>{if(event.key==='Escape')event.stopPropagation();});$('archive-dialog').addEventListener('cancel',event=>{event.preventDefault();if(!loading)closeArchive();});
 $('task-history').addEventListener('click',()=>{const popup=$('task-history-popup');popup.hidden=!popup.hidden;if(!popup.hidden){const rect=$('task-history').getBoundingClientRect();popup.style.right=`${Math.max(16,innerWidth-rect.right)}px`;popup.style.top=`${rect.bottom+8}px`;renderTaskHistory();$('task-history-close').focus();}});$('task-history-close').addEventListener('click',()=>{$('task-history-popup').hidden=true;restoreFocus($('task-history'));});
 document.addEventListener('click',event=>{if(!event.target.closest('#task-menu,.task-more'))closeTaskMenu();if(!event.target.closest('#task-history-popup,#task-history'))$('task-history-popup').hidden=true;});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('task-menu').hidden){event.preventDefault();event.stopImmediatePropagation();closeTaskMenu();restoreFocus(document.querySelector('.task.selected'));}else if(event.key==='Escape'&&!$('task-history-popup').hidden){event.preventDefault();event.stopImmediatePropagation();$('task-history-popup').hidden=true;restoreFocus($('task-history'));}});

 $('search-toggle').addEventListener('click',openSearch);$('search-close').addEventListener('click',closeSearch);$('task-search').addEventListener('input',()=>{searchSelected=0;renderSearchResults();});$('search-dialog').addEventListener('cancel',event=>{event.preventDefault();closeSearch();});$('search-dialog').addEventListener('click',event=>{if(event.target===$('search-dialog'))closeSearch();});$('search-dialog').addEventListener('keydown',searchKeys);
 $('task-filter').addEventListener('click',()=>{$('filter-menu').hidden=!$('filter-menu').hidden;if(!$('filter-menu').hidden){renderFilterMenu();$('filter-menu').querySelector('input')?.focus();}});$('filter-reset').addEventListener('click',()=>{taskFilter={status:'all',time:'all'};renderFilterMenu();renderTasks();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('filter-menu').hidden){event.preventDefault();event.stopImmediatePropagation();$('filter-menu').hidden=true;$('task-filter').focus();}});
 for(const [id,target] of [['tasks-toggle','tasks'],['spaces-toggle','workspaces']])$(id).addEventListener('click',()=>{$(target).hidden=!$(target).hidden;$(id).setAttribute('aria-expanded',String(!$(target).hidden));});
 $('space-add').addEventListener('click',()=>{$('folder').click();});
 document.addEventListener('click',event=>{if(!event.target.closest('#filter-menu,#task-filter'))$('filter-menu').hidden=true;});
 if(api.appInfo)api.appInfo().then(info=>{$('desktop-version').textContent=`v${info.version}`;}).catch(err=>error(err.message));

 initSettingsCommands();setTheme(saved('theme','system'));$('theme').addEventListener('change',e=>setTheme(e.target.value));matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(saved('theme','system')==='system')setTheme('system');});
 document.body.classList.toggle('sidebar-collapsed',saved('sidebar-collapsed','false')==='true');if(innerWidth<800)document.body.classList.add('sidebar-collapsed');workbenchWidth=Math.max(360,Math.min(700,Number(saved('workbench-width','360'))||360));
 const toggleSidebar=()=>{document.body.classList.toggle('sidebar-collapsed');save('sidebar-collapsed',document.body.classList.contains('sidebar-collapsed'));layoutWorkbench();};$('sidebar-toggle').addEventListener('click',toggleSidebar);
 $('workbench-toggle').addEventListener('click',()=>workbenchOpen?closeWorkbench():openWorkbench());$('workbench-close').addEventListener('click',closeWorkbench);$('workbench-backdrop').addEventListener('click',closeWorkbench);$('workbench-expand').addEventListener('click',toggleWorkbenchExpansion);$('workbench-overview').addEventListener('click',()=>openWorkbench('overview'));$('workbench-view').addEventListener('change',e=>openWorkbench(e.target.value));
 document.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key)||!event.target.closest('#workbench-overview,#browser-tabs [data-tab-id]'))return;event.preventDefault();const tabs=[$('workbench-overview'),...document.querySelectorAll('#browser-tabs [data-tab-id]')];const index=tabs.indexOf(document.activeElement),next=tabs[browserTabIndex(tabs.length,index,event.key)];next.focus();next.click();});
 document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='b'){e.preventDefault();toggleSidebar();}if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==='i'){e.preventDefault();workbenchOpen?closeWorkbench():openWorkbench();}if(e.key==='Escape'&&workbenchOpen){e.preventDefault();if(workbenchExpanded)toggleWorkbenchExpansion();else closeWorkbench();}if(e.key==='Tab'&&workbenchOpen&&(workbenchExpanded||document.body.classList.contains('workbench-overlay'))){const focusable=[...$('workbench').querySelectorAll('button,input,select,[tabindex]')].filter(n=>!n.disabled&&n.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
 const handle=$('resize-handle');handle.addEventListener('pointerdown',e=>{handle.setPointerCapture(e.pointerId);const start=e.clientX,width=$('workbench').getBoundingClientRect().width;const move=event=>{workbenchWidth=Math.max(360,Math.min(700,width+start-event.clientX));layoutWorkbench();};const finish=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',finish);handle.removeEventListener('pointercancel',finish);save('workbench-width',workbenchWidth);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',finish,{once:true});handle.addEventListener('pointercancel',finish,{once:true});});handle.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();workbenchWidth=Math.max(360,Math.min(700,workbenchWidth+(e.key==='ArrowLeft'?20:-20)));save('workbench-width',workbenchWidth);layoutWorkbench();}});
 window.addEventListener('resize',()=>{if(innerWidth<800&&!workbenchExpanded)document.body.classList.add('sidebar-collapsed');layoutWorkbench();});new ResizeObserver(scheduleBrowserSurface).observe($('browser-surface'));
 $('browser-url').addEventListener('input',()=>{browserURLDirty=true;});$('browser-url').addEventListener('blur',()=>{browserURLDirty=retainBrowserAddressOnBlur({dirty:browserURLDirty,rejected:browserCommandError?.tabId===browserData.selectedId&&!!browserCommandError?.address});if(!browserURLDirty){const tab=browserData.tabs.find(item=>item.id===browserData.selectedId);$('browser-url').value=tab?.url==='about:blank'?'':tab?.url??'';}});
 $('browser-new').addEventListener('click',async()=>{if(await browserCommand('new'))openWorkbench('browser');});$('browser-navigation').addEventListener('submit',e=>{e.preventDefault();const url=$('browser-url').value.trim();browserURLDirty=false;if(url)browserCommand(browserData.selectedId?'navigate':'new',{url});});for(const type of ['back','forward','reload','external'])$('browser-'+type).addEventListener('click',()=>browserCommand(type));
 if(api.browserState){api.browserState().then(data=>{browserData=data;renderWorkbench();}).catch(err=>error(err.message));api.onBrowserState(data=>{browserData=data;if(!data.tabs.length&&workbenchView==='browser')workbenchView='overview';renderWorkbench();scheduleBrowserSurface();});}layoutWorkbench();
}
function commandCatalog(){const frozen=loading||!!uncertain||uploadPending(),session=!!current;return [['new','新建任务',true],['find','搜索对话',session],['rename','重命名任务',session],['diff','读取工作区变更',!!current?.session.repository],['agents','查看智能体目录',session],['memory','查看项目记忆',session],['context','查看上下文统计',session],['observability','查看运行观测',session],['settings','打开设置',true]].map(([id,label,available])=>({id,label,enabled:available&&!frozen,reason:frozen?'请先处理当前未完成操作':id==='diff'?'需要当前任务的工作空间':'请先选择或新建任务'}));}
function renderCommands(){const options=commandCandidates($('message').value,commandCatalog()),show=!commandDismissed&&/^\/[a-z-]*$/.test($('message').value.trim());$('command-menu').hidden=!show;$('message').setAttribute('aria-expanded',String(show));$('command-count').textContent=String(options.length);const list=$('command-options');list.replaceChildren();commandSelected=Math.max(0,Math.min(commandSelected,options.length-1));for(const [index,command] of options.entries()){const button=el('button',`/${command.id} · ${command.label}`);button.type='button';button.dataset.commandId=command.id;button.id='command-'+command.id;button.setAttribute('role','option');button.setAttribute('aria-selected',String(index===commandSelected));button.disabled=!command.enabled;if(!command.enabled)button.append(el('small',command.reason));button.addEventListener('click',()=>insertCommand(command.id));list.append(button);}if(!options.length)list.append(el('p','没有匹配的命令'));$('message').setAttribute('aria-controls','command-options');if(show&&options[commandSelected])$('message').setAttribute('aria-activedescendant','command-'+options[commandSelected].id);else $('message').removeAttribute('aria-activedescendant');scheduleBrowserSurface();}
function insertCommand(id){const command=commandCatalog().find(item=>item.id===id);if(!command?.enabled)return;$('message').value='/'+id;commandDismissed=true;renderCommands();$('message').focus();controls();}
function commandKeys(event){if(event.isComposing||event.keyCode===229||$('command-menu').hidden)return false;const candidates=commandCandidates($('message').value,commandCatalog());if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();commandDismissed=true;renderCommands();return true;}if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();if(candidates.length)commandSelected=(commandSelected+(event.key==='ArrowDown'?1:-1)+candidates.length)%candidates.length;renderCommands();return true;}if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();const selected=candidates[commandSelected];if(selected?.enabled)insertCommand(selected.id);else composerError(selected?.reason??'没有匹配的命令');return true;}return false;}
async function executeCommand(id){const command=commandCatalog().find(item=>item.id===id);if(!command?.enabled){composerError(command?.reason??'命令当前不可用');return;}$('message').value='';commandDismissed=true;renderCommands();composerError('');controls();if(id==='new'){$('new-task').click();return;}if(id==='find'){openConversationSearch();return;}if(id==='rename'){startTitleEdit();return;}if(id==='diff'){await requestDiff();return;}openSettings(id==='settings'?'appearance':id);if(id!=='settings')await readSettings(id);}
const settingsGroups=[['appearance','外观'],['session','当前会话'],['agents','智能体'],['memory','项目记忆'],['context','上下文'],['observability','运行观测'],['archives','归档记录'],['diagnostics','连接与快捷键']];
function openSettings(section='appearance'){settingsFocus=document.activeElement;settingsSection=section;closeComposerMenus();renderSettings();if(!$('settings-dialog').open)$('settings-dialog').showModal();$('settings-close').focus();scheduleBrowserSurface();}
function closeSettings(){$('settings-dialog').close();restoreFocus(settingsFocus);scheduleBrowserSurface();}
function settingCard(title,description){const card=el('section',undefined,'setting-card');card.append(el('h3',title));if(description)card.append(el('p',description));$('settings-content').append(card);return card;}
function settingButton(parent,label,handler,id){const button=el('button',label);button.type='button';if(id)button.id=id;button.addEventListener('click',handler);parent.append(button);return button;}
function renderSettings(){settingsRenderedOwner=settingsOwner();const nav=$('settings-nav'),content=$('settings-content');nav.replaceChildren();content.replaceChildren();for(const [id,label] of settingsGroups){const button=el('button',label);button.type='button';button.dataset.settingsSection=id;button.setAttribute('aria-current',String(id===settingsSection));button.addEventListener('click',()=>{settingsSection=id;renderSettings();$('settings-nav').querySelector(`[data-settings-section="${id}"]`)?.focus();});nav.append(button);}content.append(el('h2',settingsGroups.find(([id])=>id===settingsSection)?.[1]??'设置'));
 if(settingsSection==='appearance'){const card=settingCard('外观','跟随系统使用本机的明暗外观；选择浅色或深色会保存到当前桌面。');const select=el('select');select.id='settings-theme';select.setAttribute('aria-label','设置外观');for(const [value,label] of [['system','跟随系统'],['light','浅色'],['dark','深色']]){const option=el('option',label);option.value=value;select.append(option);}select.value=saved('theme','system');select.addEventListener('change',()=>setTheme(select.value));card.append(select);return;}
 if(settingsSection==='session'){const card=settingCard('当前任务');const facts=el('div');facts.id='settings-session-facts';card.append(facts);updateSettingsSession();for(const [label,id] of [['在会话中切换模型','model-picker'],['在会话中调整权限','permission']]){const button=settingButton(card,label,()=>{closeSettings();if(workbenchExpanded||document.body.classList.contains('workbench-overlay'))closeWorkbench();$(id).click();});button.dataset.sessionAction='true';button.disabled=!current||loading||!!uncertain||uploadPending();}return;}
 if(settingsSection==='diagnostics'){const card=settingCard('桌面与连接','数据来源读取失败会保留错误，不会当作成功。');card.append(el('p',`CodeLeveler ${$('desktop-version').textContent}`),el('p',$('status').textContent));if(sourceErrors.length){const summary=sourceErrorSummary(sourceErrors);card.append(el('p',summary.summary));for(const item of summary.details){const details=el('details');details.append(el('summary',`${item.count} 个来源读取失败`),el('pre',item.message));card.append(details);}}else card.append(el('p','最近一次任务索引读取未报告来源错误。'));settingCard('快捷键','⌘ / Ctrl + , 打开设置；⌘ / Ctrl + B 切换侧栏；⌘ / Ctrl + F 搜索当前对话；⌘ / Ctrl + Shift + I 切换工作台；Enter 发送；Shift + Enter 换行；/ 打开命令候选。');settingCard('技能目录','当前桌面尚不能读取独立技能目录。智能体定义里的技能声明不代表已安装技能清单。');return;}
 if(settingsSection==='archives'){const card=settingCard('归档记录','仅查看及打开保留的会话记录；打开不会取消归档。');settingButton(card,'读取归档记录',readArchives,'settings-read-archives');card.append(el('div',undefined,'settings-results'));renderArchiveResults();return;}
 const descriptions={agents:'读取 Runtime 智能体定义及读取问题。定义中的技能声明不代表已安装技能目录。',memory:'查看 Runtime 返回的活动、归档及待确认记忆。读取可能包含 Runtime 的恢复处理；此页面不修改、批准或删除记忆。',context:'上次真实模型请求的上下文统计；估计 token 保持估计含义，不是实时费用或精确用量。',observability:'查看 Runtime 持久化的有限事件窗口与相关统计。'};const card=settingCard(settingsGroups.find(([id])=>id===settingsSection)?.[1],descriptions[settingsSection]);const button=settingButton(card,'读取最新数据',()=>readSettings(settingsSection),'settings-read');button.dataset.sessionAction='true';button.disabled=!current||loading||!!uncertain||uploadPending();if(!current){card.append(el('p','请先选择任务，或明确新建一个任务后读取。'));settingButton(card,'新建任务',()=>{closeSettings();$('new-task').click();},'settings-new-task').disabled=loading||uploadPending();}card.append(el('div',undefined,'settings-results'));renderSettingsRead();
}
function updateSettingsSession(){const node=$('settings-session-facts');if(!node)return;node.replaceChildren();if(!current){node.append(el('p','尚未选择任务。打开设置不会自动创建任务。'));return;}node.append(el('p',current.session.goal||'未命名任务'),el('p',`模型：${modelLabel(current.session.model)}`),el('p',`权限：${permissionLabel(current.session.mode)}`));}
function settingsOwner(){return JSON.stringify([currentSource,current?.session.id??null,current?.session.repository??null]);}
function readKey(section,name=''){return JSON.stringify([settingsOwner(),section,name]);}
function readState(section,name=''){return settingsReads.get(readKey(section,name));}
async function readSettings(section,name=''){if(!current||loading||uncertain||uploadPending())return;const types={agents:['list_agents','agents_loaded'],agent:['get_agent','agent_loaded'],memory:['list_memory','memory_list'],context:['query_context','context_loaded'],observability:['query_observability','observability_loaded']};const pair=types[section];if(!pair)return;const sessionId=current.session.id,owner=settingsOwner(),id=crypto.randomUUID(),key=readKey(section,name);clearTimeout(settingsTimers.get(key));settingsReads.set(key,{...beginReadQuery(settingsReads.get(key),sessionId,id,pair[1]),owner});while(settingsReads.size>32){const oldest=settingsReads.keys().next().value;clearTimeout(settingsTimers.get(oldest));settingsTimers.delete(oldest);settingsReads.delete(oldest);}settingsTimers.set(key,setTimeout(()=>{settingsReads.set(key,expireReadQuery(settingsReads.get(key),id,'15 秒内未收到结果，读取结果未确认。'));if(settingsOwner()===owner)renderSettingsRead();},15000));renderSettingsRead();const command={type:pair[0],session_id:sessionId,query_id:id};if(section==='agent')command.name=name;if(section==='memory')command.include_archived=true;if(section==='observability')Object.assign(command,{center_seq:null,before:30,after:30});await action(()=>deliver(command),{onError:message=>{settingsReads.set(key,expireReadQuery(settingsReads.get(key),id,'无法确认读取结果：'+message));clearTimeout(settingsTimers.get(key));if(settingsOwner()===owner)renderSettingsRead();},clearGlobal:false});controls();}
function consumeSettingsEvent(frame){if(frame.event==='error'&&(!frame.session_id||frame.session_id===current?.session.id)){for(const [key,read] of settingsReads)if(read.owner===settingsOwner()){settingsReads.set(key,expireReadQuery(read,read.id,'连接中断，读取结果未确认。'));clearTimeout(settingsTimers.get(key));}renderSettingsRead();return;}if(frame.session_id!==current?.session.id)return;if(frame.event==='runtime'&&frame.data.type==='notification'){settingsWarnings.push({owner:settingsOwner(),level:frame.data.level,message:frame.data.message});settingsWarnings=settingsWarnings.slice(-16);if($('settings-dialog').open)renderSettingsRead();}if(frame.event==='snapshot'||frame.event==='runtime'&&['session_updated','session_opened'].includes(frame.data.type))Promise.resolve().then(updateSettingsSession);for(const [key,read] of settingsReads){if(read.owner!==settingsOwner())continue;const next=applyReadResult(read,frame);if(next!==read){settingsReads.set(key,next);clearTimeout(settingsTimers.get(key));if($('settings-dialog').open)renderSettingsRead();}}if(frame.event==='error'){for(const [key,read] of settingsReads)if(read.sessionId===frame.session_id&&read.owner===settingsOwner()){settingsReads.set(key,expireReadQuery(read,read.id,'连接中断，读取结果未确认。'));clearTimeout(settingsTimers.get(key));}renderSettingsRead();}}
function readNotice(container,read){const status=el('p',!read?'尚未读取':read.status==='pending'?'正在读取…已有内容为此前确认的结果。':read.status==='unknown'?read.error:'已收到当前查询结果。','settings-query-status');status.dataset.queryStatus=read?.status??'idle';status.setAttribute('role','status');container.append(status);const warnings=settingsWarnings.filter(item=>item.owner===settingsOwner());if(warnings.length){const details=el('details',undefined,'settings-warning');details.append(el('summary','Runtime 提示（未关联此查询）'));for(const item of warnings)details.append(el('pre',`${item.level}: ${item.message}`));container.append(details);}return read?.data;}
function technicalData(container,title,data){const details=el('details',undefined,'settings-data');if(data?.source_id)details.dataset.resultKey=JSON.stringify([data.source_id,data.kind]);details.append(el('summary',title),el('pre',JSON.stringify(data,null,2)));container.append(details);}
function settingsResultFocus(container){const active=document.activeElement;if(!container.contains(active))return null;const article=active.closest('[data-result-key]');return {tag:active.tagName,label:active.textContent,key:article?.dataset.resultKey??''};}
function restoreSettingsResultFocus(container,target){if(!target)return;const node=[...container.querySelectorAll('button,summary')].find(item=>item.tagName===target.tag&&item.textContent===target.label&&(item.closest('[data-result-key]')?.dataset.resultKey??'')===target.key);(node??$('settings-read')??$('settings-close')).focus();}
function retainSettingsResults(container){return {focus:settingsResultFocus(container),details:[...container.querySelectorAll('details[open]')].map(node=>({label:node.querySelector('summary')?.textContent,key:node.closest('[data-result-key]')?.dataset.resultKey??''}))};}
function restoreSettingsResults(container,retained){for(const node of container.querySelectorAll('details'))if(retained.details.some(item=>item.label===node.querySelector('summary')?.textContent&&item.key===(node.closest('[data-result-key]')?.dataset.resultKey??'')))node.open=true;restoreSettingsResultFocus(container,retained.focus);}
function renderSettingsRead(){if(!$('settings-dialog').open&&$('settings-content').children.length===0)return;const container=$('settings-content').querySelector('.settings-results');if(!container||settingsSection==='archives')return;const retained=retainSettingsResults(container);container.replaceChildren();const data=readNotice(container,readState(settingsSection));
 if(data&&settingsSection==='agents'){for(const agent of data.agents??[]){const row=el('article',undefined,'settings-item');row.dataset.resultKey=agent.name;row.append(el('strong',agent.name),el('p',agent.description||'没有描述'),el('small',`来源 ${agent.source} · ${agent.status}${agent.reason?' · '+agent.reason:''}`));const button=settingButton(row,'查看定义',()=>readSettings('agent',agent.name));button.dataset.agentName=agent.name;button.dataset.sessionAction='true';button.disabled=loading||!!uncertain||uploadPending();const detail=readState('agent',agent.name);if(detail){const result=readNotice(row,detail);if(result?.error)row.append(el('p',result.error,'settings-failure'));if(result?.agent)technicalData(row,'定义详情',result.agent);}container.append(row);}if(!data.agents?.length)container.append(el('p','本次结果没有智能体定义。'));for(const problem of data.problems??[]){const details=el('details',undefined,'settings-failure');details.append(el('summary',`定义读取失败 · ${problem.source}`),el('pre',`${problem.location}\n${problem.error}`));container.append(details);}}
 if(data&&settingsSection==='memory'){for(const [key,label] of [['active','活动记忆'],['archived','归档记忆'],['pending','待确认候选']]){const section=el('section');section.append(el('h4',`${label} (${data[key]?.length??0})`));for(const item of data[key]??[]){const row=el('article',undefined,'settings-item');row.append(el('strong',item.title),el('p',`${item.kind??'类型未提供'}${item.sensitive?' · 敏感，不会自动注入':''}`));if(item.body){const details=el('details');details.append(el('summary','候选正文'),el('pre',item.body));row.append(details);}section.append(row);}if(!data[key]?.length)section.append(el('p','本次结果为空。'));container.append(section);}technicalData(container,'记忆目录',data.memory_dir);}
 if(data&&settingsSection==='context'){if(!data.accounting)container.append(el('p','尚无上次模型请求的上下文统计。'));else{const accounting=data.accounting;container.append(el('p',`输入统计：${accounting.used_tokens} tokens · 统计方式 ${{exact:'精确分词',estimated:'估计',mixed:'模型报告总量，分类为估计'}[accounting.token_count_kind]??accounting.token_count_kind}`),el('p',`模型声明上下文窗口：${accounting.context_window_tokens??'未提供'} · 剩余统计：${accounting.free_tokens??'未提供'}`));technicalData(container,'分类与统计详情',accounting);}}
 if(data&&settingsSection==='observability'){const observation=data.observation;container.append(el('p',`事件窗口 ${observation.window_from}—${observation.window_to}`));for(const row of observation.window??[]){const item=el('article',undefined,'settings-item');item.append(el('strong',`${row.sequence} · ${row.title}`),el('p',`${row.class} · ${row.status} · ${row.target}`));if(row.fields?.length)technicalData(item,'事件详情',row.fields);container.append(item);}if(!observation.window?.length)container.append(el('p','本次事件窗口为空。'));technicalData(container,'会话与请求统计',observation);}
 restoreSettingsResults(container,retained);}
async function readArchives(){const version=++archiveReadVersion;archiveRead={...archiveRead,status:'pending',error:null};renderArchiveResults();try{const index=await api.listTasks({include_archived:true});if(version!==archiveReadVersion)return;archiveRead={status:'confirmed',data:index,error:null};}catch(err){if(version!==archiveReadVersion)return;archiveRead={...archiveRead,status:'unknown',error:'无法读取归档列表。',detail:err.message};}if($('settings-dialog').open&&settingsSection==='archives')renderArchiveResults();}
function renderArchiveResults(){const container=$('settings-content').querySelector('.settings-results');if(!container||settingsSection!=='archives')return;const retained=retainSettingsResults(container);container.replaceChildren();const data=readNotice(container,archiveRead);if(archiveRead?.detail)technicalData(container,'技术详情',archiveRead.detail);if(!data){restoreSettingsResults(container,retained);return;}const archived=data.tasks.filter(task=>task.archived===true||task.archived_at);for(const task of archived){const row=el('article',undefined,'settings-item');row.dataset.resultKey=JSON.stringify([task.source_id,task.id]);row.append(el('strong',task.title||'未命名任务'));const button=settingButton(row,'打开保留记录',()=>{closeSettings();action(()=>openTask(task));});button.dataset.sessionAction='true';button.disabled=loading||!!uncertain||uploadPending();container.append(row);}if(!archived.length)container.append(el('p','本次索引中没有归档记录。'));for(const problem of data.source_errors??[])technicalData(container,'来源读取失败',problem);restoreSettingsResults(container,retained);}
function initSettingsCommands(){document.addEventListener('compositionstart',()=>{settingsComposing=true;});document.addEventListener('compositionend',()=>{settingsComposing=false;});api.onOpenSettings?.(()=>activateSettingsShortcut({composing:settingsComposing,settingsOpen:$('settings-dialog').open,modalOpen:!!document.querySelector('dialog[open]:not(#settings-dialog)')},()=>openSettings()));$('settings-open').addEventListener('click',()=>openSettings());$('settings-close').addEventListener('click',closeSettings);$('settings-dialog').addEventListener('cancel',event=>{event.preventDefault();closeSettings();});$('settings-dialog').addEventListener('keydown',event=>{if(event.key==='Escape')event.stopPropagation();});document.addEventListener('pointerdown',event=>{if(!event.target.closest('#command-menu,#message')){commandDismissed=true;renderCommands();}});}

initProductUI();
action(async()=>{await refreshTasks();renderHeader();renderConversation();});
